// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: airport_transfers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAirportTransfer = `-- name: CancelAirportTransfer :one
UPDATE airport_transfers
SET status = 'cancelled',
    notes = COALESCE(NULLIF($2::text, ''), notes),
    updated_at = NOW()
WHERE id = $1 AND status NOT IN ('completed', 'cancelled', 'no_show')
RETURNING id, ride_id, airport_id, is_pickup, flight_number, airline, scheduled_arrival, actual_arrival, passenger_name, passenger_phone, meet_and_greet, waiting_minutes, waiting_fee_cents, fixed_fare_cents, status, notes, created_at, updated_at
`

type CancelAirportTransferParams struct {
	ID     uuid.UUID
	Reason string
}

func (q *Queries) CancelAirportTransfer(ctx context.Context, arg CancelAirportTransferParams) (AirportTransfer, error) {
	row := q.db.QueryRow(ctx, cancelAirportTransfer, arg.ID, arg.Reason)
	var i AirportTransfer
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.AirportID,
		&i.IsPickup,
		&i.FlightNumber,
		&i.Airline,
		&i.ScheduledArrival,
		&i.ActualArrival,
		&i.PassengerName,
		&i.PassengerPhone,
		&i.MeetAndGreet,
		&i.WaitingMinutes,
		&i.WaitingFeeCents,
		&i.FixedFareCents,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAirportTransfer = `-- name: CreateAirportTransfer :one
INSERT INTO airport_transfers (
    ride_id, airport_id, is_pickup, flight_number, airline,
    scheduled_arrival, actual_arrival, passenger_name, passenger_phone,
    meet_and_greet, waiting_minutes, waiting_fee_cents,
    fixed_fare_cents, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14)
RETURNING id, ride_id, airport_id, is_pickup, flight_number, airline, scheduled_arrival, actual_arrival, passenger_name, passenger_phone, meet_and_greet, waiting_minutes, waiting_fee_cents, fixed_fare_cents, status, notes, created_at, updated_at
`

type CreateAirportTransferParams struct {
	RideID           uuid.UUID
	AirportID        uuid.UUID
	IsPickup         bool
	FlightNumber     pgtype.Text
	Airline          pgtype.Text
	ScheduledArrival pgtype.Timestamptz
	ActualArrival    pgtype.Timestamptz
	PassengerName    pgtype.Text
	PassengerPhone   pgtype.Text
	MeetAndGreet     bool
	WaitingMinutes   int32
	WaitingFeeCents  int32
	FixedFareCents   int32
	Notes            pgtype.Text
}

func (q *Queries) CreateAirportTransfer(ctx context.Context, arg CreateAirportTransferParams) (AirportTransfer, error) {
	row := q.db.QueryRow(ctx, createAirportTransfer,
		arg.RideID,
		arg.AirportID,
		arg.IsPickup,
		arg.FlightNumber,
		arg.Airline,
		arg.ScheduledArrival,
		arg.ActualArrival,
		arg.PassengerName,
		arg.PassengerPhone,
		arg.MeetAndGreet,
		arg.WaitingMinutes,
		arg.WaitingFeeCents,
		arg.FixedFareCents,
		arg.Notes,
	)
	var i AirportTransfer
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.AirportID,
		&i.IsPickup,
		&i.FlightNumber,
		&i.Airline,
		&i.ScheduledArrival,
		&i.ActualArrival,
		&i.PassengerName,
		&i.PassengerPhone,
		&i.MeetAndGreet,
		&i.WaitingMinutes,
		&i.WaitingFeeCents,
		&i.FixedFareCents,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAirport = `-- name: GetAirport :one
SELECT id, iata, name, city, country, country_code, latitude, longitude, timezone, terminal_count, pickup_zones, created_at, updated_at FROM airports
WHERE id = $1
`

func (q *Queries) GetAirport(ctx context.Context, id uuid.UUID) (Airport, error) {
	row := q.db.QueryRow(ctx, getAirport, id)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.Iata,
		&i.Name,
		&i.City,
		&i.Country,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.TerminalCount,
		&i.PickupZones,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAirportByIATA = `-- name: GetAirportByIATA :one
SELECT id, iata, name, city, country, country_code, latitude, longitude, timezone, terminal_count, pickup_zones, created_at, updated_at FROM airports
WHERE iata = $1
`

func (q *Queries) GetAirportByIATA(ctx context.Context, iata string) (Airport, error) {
	row := q.db.QueryRow(ctx, getAirportByIATA, iata)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.Iata,
		&i.Name,
		&i.City,
		&i.Country,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.TerminalCount,
		&i.PickupZones,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAirportTransfer = `-- name: GetAirportTransfer :one
SELECT id, ride_id, airport_id, is_pickup, flight_number, airline, scheduled_arrival, actual_arrival, passenger_name, passenger_phone, meet_and_greet, waiting_minutes, waiting_fee_cents, fixed_fare_cents, status, notes, created_at, updated_at FROM airport_transfers
WHERE id = $1
`

func (q *Queries) GetAirportTransfer(ctx context.Context, id uuid.UUID) (AirportTransfer, error) {
	row := q.db.QueryRow(ctx, getAirportTransfer, id)
	var i AirportTransfer
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.AirportID,
		&i.IsPickup,
		&i.FlightNumber,
		&i.Airline,
		&i.ScheduledArrival,
		&i.ActualArrival,
		&i.PassengerName,
		&i.PassengerPhone,
		&i.MeetAndGreet,
		&i.WaitingMinutes,
		&i.WaitingFeeCents,
		&i.FixedFareCents,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAirportTransferByRideID = `-- name: GetAirportTransferByRideID :one
SELECT id, ride_id, airport_id, is_pickup, flight_number, airline, scheduled_arrival, actual_arrival, passenger_name, passenger_phone, meet_and_greet, waiting_minutes, waiting_fee_cents, fixed_fare_cents, status, notes, created_at, updated_at FROM airport_transfers
WHERE ride_id = $1
LIMIT 1
`

func (q *Queries) GetAirportTransferByRideID(ctx context.Context, rideID uuid.UUID) (AirportTransfer, error) {
	row := q.db.QueryRow(ctx, getAirportTransferByRideID, rideID)
	var i AirportTransfer
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.AirportID,
		&i.IsPickup,
		&i.FlightNumber,
		&i.Airline,
		&i.ScheduledArrival,
		&i.ActualArrival,
		&i.PassengerName,
		&i.PassengerPhone,
		&i.MeetAndGreet,
		&i.WaitingMinutes,
		&i.WaitingFeeCents,
		&i.FixedFareCents,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAirportTransfers = `-- name: ListAirportTransfers :many
SELECT id, ride_id, airport_id, is_pickup, flight_number, airline, scheduled_arrival, actual_arrival, passenger_name, passenger_phone, meet_and_greet, waiting_minutes, waiting_fee_cents, fixed_fare_cents, status, notes, created_at, updated_at FROM airport_transfers
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAirportTransfers(ctx context.Context) ([]AirportTransfer, error) {
	rows, err := q.db.Query(ctx, listAirportTransfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AirportTransfer
	for rows.Next() {
		var i AirportTransfer
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.AirportID,
			&i.IsPickup,
			&i.FlightNumber,
			&i.Airline,
			&i.ScheduledArrival,
			&i.ActualArrival,
			&i.PassengerName,
			&i.PassengerPhone,
			&i.MeetAndGreet,
			&i.WaitingMinutes,
			&i.WaitingFeeCents,
			&i.FixedFareCents,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAirports = `-- name: ListAirports :many

SELECT id, iata, name, city, country, country_code, latitude, longitude, timezone, terminal_count, pickup_zones, created_at, updated_at FROM airports
ORDER BY name ASC, id ASC
`

// Airport transfer queries used by the airport package. Kept in sqlc
// -- name: format so the generated db layer stays synchronized.
func (q *Queries) ListAirports(ctx context.Context) ([]Airport, error) {
	rows, err := q.db.Query(ctx, listAirports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Airport
	for rows.Next() {
		var i Airport
		if err := rows.Scan(
			&i.ID,
			&i.Iata,
			&i.Name,
			&i.City,
			&i.Country,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.TerminalCount,
			&i.PickupZones,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAirportTransfer = `-- name: UpdateAirportTransfer :one
UPDATE airport_transfers
SET status = $2,
    actual_arrival = $3,
    waiting_minutes = $4,
    notes = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, ride_id, airport_id, is_pickup, flight_number, airline, scheduled_arrival, actual_arrival, passenger_name, passenger_phone, meet_and_greet, waiting_minutes, waiting_fee_cents, fixed_fare_cents, status, notes, created_at, updated_at
`

type UpdateAirportTransferParams struct {
	ID             uuid.UUID
	Status         AirportTransferStatus
	ActualArrival  pgtype.Timestamptz
	WaitingMinutes int32
	Notes          pgtype.Text
}

func (q *Queries) UpdateAirportTransfer(ctx context.Context, arg UpdateAirportTransferParams) (AirportTransfer, error) {
	row := q.db.QueryRow(ctx, updateAirportTransfer,
		arg.ID,
		arg.Status,
		arg.ActualArrival,
		arg.WaitingMinutes,
		arg.Notes,
	)
	var i AirportTransfer
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.AirportID,
		&i.IsPickup,
		&i.FlightNumber,
		&i.Airline,
		&i.ScheduledArrival,
		&i.ActualArrival,
		&i.PassengerName,
		&i.PassengerPhone,
		&i.MeetAndGreet,
		&i.WaitingMinutes,
		&i.WaitingFeeCents,
		&i.FixedFareCents,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
