// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeAlertEvent = `-- name: AcknowledgeAlertEvent :one
UPDATE alert_events
SET acknowledged = TRUE, acknowledged_by = $2, acknowledged_at = NOW()
WHERE id = $1
RETURNING id, rule_id, severity, title, message, data, acknowledged, acknowledged_by, acknowledged_at, created_at
`

type AcknowledgeAlertEventParams struct {
	ID             uuid.UUID
	AcknowledgedBy pgtype.UUID
}

func (q *Queries) AcknowledgeAlertEvent(ctx context.Context, arg AcknowledgeAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlertEvent, arg.ID, arg.AcknowledgedBy)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.Data,
		&i.Acknowledged,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAlertEvent = `-- name: CreateAlertEvent :one
INSERT INTO alert_events (rule_id, severity, title, message, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, rule_id, severity, title, message, data, acknowledged, acknowledged_by, acknowledged_at, created_at
`

type CreateAlertEventParams struct {
	RuleID   uuid.UUID
	Severity string
	Title    string
	Message  string
	Data     []byte
}

func (q *Queries) CreateAlertEvent(ctx context.Context, arg CreateAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, createAlertEvent,
		arg.RuleID,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.Data,
	)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.Data,
		&i.Acknowledged,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (name, description, condition, threshold, severity, action, recipients, cooldown_min)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, condition, threshold, severity, action, recipients, active, cooldown_min, last_triggered, created_at, updated_at
`

type CreateAlertRuleParams struct {
	Name        string
	Description pgtype.Text
	Condition   string
	Threshold   pgtype.Numeric
	Severity    string
	Action      string
	Recipients  []string
	CooldownMin int32
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.Name,
		arg.Description,
		arg.Condition,
		arg.Threshold,
		arg.Severity,
		arg.Action,
		arg.Recipients,
		arg.CooldownMin,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Condition,
		&i.Threshold,
		&i.Severity,
		&i.Action,
		&i.Recipients,
		&i.Active,
		&i.CooldownMin,
		&i.LastTriggered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM alert_rules
WHERE id = $1
`

func (q *Queries) DeleteAlertRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlertRule, id)
	return err
}

const deleteOldAlertEvents = `-- name: DeleteOldAlertEvents :exec
DELETE FROM alert_events
WHERE created_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldAlertEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldAlertEvents)
	return err
}

const getAlertEventByID = `-- name: GetAlertEventByID :one
SELECT id, rule_id, severity, title, message, data, acknowledged, acknowledged_by, acknowledged_at, created_at FROM alert_events
WHERE id = $1
`

func (q *Queries) GetAlertEventByID(ctx context.Context, id uuid.UUID) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, getAlertEventByID, id)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.Severity,
		&i.Title,
		&i.Message,
		&i.Data,
		&i.Acknowledged,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAlertRuleByID = `-- name: GetAlertRuleByID :one
SELECT id, name, description, condition, threshold, severity, action, recipients, active, cooldown_min, last_triggered, created_at, updated_at FROM alert_rules
WHERE id = $1
`

func (q *Queries) GetAlertRuleByID(ctx context.Context, id uuid.UUID) (AlertRule, error) {
	row := q.db.QueryRow(ctx, getAlertRuleByID, id)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Condition,
		&i.Threshold,
		&i.Severity,
		&i.Action,
		&i.Recipients,
		&i.Active,
		&i.CooldownMin,
		&i.LastTriggered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAlertRules = `-- name: ListActiveAlertRules :many
SELECT id, name, description, condition, threshold, severity, action, recipients, active, cooldown_min, last_triggered, created_at, updated_at FROM alert_rules
WHERE active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listActiveAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Condition,
			&i.Threshold,
			&i.Severity,
			&i.Action,
			&i.Recipients,
			&i.Active,
			&i.CooldownMin,
			&i.LastTriggered,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertEvents = `-- name: ListAlertEvents :many
SELECT id, rule_id, severity, title, message, data, acknowledged, acknowledged_by, acknowledged_at, created_at FROM alert_events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAlertEventsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAlertEvents(ctx context.Context, arg ListAlertEventsParams) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlertEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertEvent
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.Data,
			&i.Acknowledged,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, name, description, condition, threshold, severity, action, recipients, active, cooldown_min, last_triggered, created_at, updated_at FROM alert_rules
ORDER BY created_at DESC
`

func (q *Queries) ListAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Condition,
			&i.Threshold,
			&i.Severity,
			&i.Action,
			&i.Recipients,
			&i.Active,
			&i.CooldownMin,
			&i.LastTriggered,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsBySeverity = `-- name: ListAlertsBySeverity :many
SELECT id, rule_id, severity, title, message, data, acknowledged, acknowledged_by, acknowledged_at, created_at FROM alert_events
WHERE severity = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAlertsBySeverityParams struct {
	Severity string
	Limit    int32
}

func (q *Queries) ListAlertsBySeverity(ctx context.Context, arg ListAlertsBySeverityParams) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlertsBySeverity, arg.Severity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertEvent
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.Data,
			&i.Acknowledged,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnacknowledgedAlerts = `-- name: ListUnacknowledgedAlerts :many
SELECT id, rule_id, severity, title, message, data, acknowledged, acknowledged_by, acknowledged_at, created_at FROM alert_events
WHERE acknowledged = FALSE
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListUnacknowledgedAlerts(ctx context.Context, limit int32) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listUnacknowledgedAlerts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertEvent
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.Severity,
			&i.Title,
			&i.Message,
			&i.Data,
			&i.Acknowledged,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules
SET name = $2, description = $3, condition = $4, threshold = $5, severity = $6, action = $7, recipients = $8, cooldown_min = $9, active = $10, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, condition, threshold, severity, action, recipients, active, cooldown_min, last_triggered, created_at, updated_at
`

type UpdateAlertRuleParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	Condition   string
	Threshold   pgtype.Numeric
	Severity    string
	Action      string
	Recipients  []string
	CooldownMin int32
	Active      bool
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, updateAlertRule,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Condition,
		arg.Threshold,
		arg.Severity,
		arg.Action,
		arg.Recipients,
		arg.CooldownMin,
		arg.Active,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Condition,
		&i.Threshold,
		&i.Severity,
		&i.Action,
		&i.Recipients,
		&i.Active,
		&i.CooldownMin,
		&i.LastTriggered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlertRuleLastTriggered = `-- name: UpdateAlertRuleLastTriggered :exec
UPDATE alert_rules
SET last_triggered = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAlertRuleLastTriggered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAlertRuleLastTriggered, id)
	return err
}
