// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveRideAuthorization = `-- name: ApproveRideAuthorization :one
UPDATE ride_authorizations
SET status = 'approved', authorized_by = $2, decision_note = $3,
    decided_at = NOW(), updated_at = NOW()
WHERE ride_id = $1 AND status = 'pending'
RETURNING id, ride_id, account_id, member_id, status, requested_amount_cents, authorized_by, decision_note, created_at, updated_at, decided_at
`

type ApproveRideAuthorizationParams struct {
	RideID       uuid.UUID
	AuthorizedBy pgtype.UUID
	DecisionNote pgtype.Text
}

func (q *Queries) ApproveRideAuthorization(ctx context.Context, arg ApproveRideAuthorizationParams) (RideAuthorization, error) {
	row := q.db.QueryRow(ctx, approveRideAuthorization, arg.RideID, arg.AuthorizedBy, arg.DecisionNote)
	var i RideAuthorization
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.AccountID,
		&i.MemberID,
		&i.Status,
		&i.RequestedAmountCents,
		&i.AuthorizedBy,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const createBusinessAccount = `-- name: CreateBusinessAccount :one
INSERT INTO business_accounts (owner_id, name, currency, monthly_limit_cents, require_ride_approval)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, currency, monthly_limit_cents, require_ride_approval, is_active, created_at, updated_at
`

type CreateBusinessAccountParams struct {
	OwnerID             uuid.UUID
	Name                string
	Currency            string
	MonthlyLimitCents   pgtype.Numeric
	RequireRideApproval bool
}

func (q *Queries) CreateBusinessAccount(ctx context.Context, arg CreateBusinessAccountParams) (BusinessAccount, error) {
	row := q.db.QueryRow(ctx, createBusinessAccount,
		arg.OwnerID,
		arg.Name,
		arg.Currency,
		arg.MonthlyLimitCents,
		arg.RequireRideApproval,
	)
	var i BusinessAccount
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Currency,
		&i.MonthlyLimitCents,
		&i.RequireRideApproval,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBusinessMember = `-- name: CreateBusinessMember :one
INSERT INTO business_members (account_id, user_id, role, spending_limit_cents, status)
VALUES ($1, $2, $3, $4, 'active')
ON CONFLICT (account_id, user_id)
DO UPDATE SET role = EXCLUDED.role,
              spending_limit_cents = EXCLUDED.spending_limit_cents,
              status = 'active',
              updated_at = NOW()
RETURNING account_id, user_id, role, spending_limit_cents, status, created_at, updated_at
`

type CreateBusinessMemberParams struct {
	AccountID          uuid.UUID
	UserID             uuid.UUID
	Role               string
	SpendingLimitCents pgtype.Numeric
}

func (q *Queries) CreateBusinessMember(ctx context.Context, arg CreateBusinessMemberParams) (BusinessMember, error) {
	row := q.db.QueryRow(ctx, createBusinessMember,
		arg.AccountID,
		arg.UserID,
		arg.Role,
		arg.SpendingLimitCents,
	)
	var i BusinessMember
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.Role,
		&i.SpendingLimitCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRideAuthorization = `-- name: CreateRideAuthorization :one
INSERT INTO ride_authorizations (
    ride_id, account_id, member_id, status, requested_amount_cents
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (ride_id)
DO UPDATE SET updated_at = ride_authorizations.updated_at
RETURNING id, ride_id, account_id, member_id, status, requested_amount_cents, authorized_by, decision_note, created_at, updated_at, decided_at
`

type CreateRideAuthorizationParams struct {
	RideID               uuid.UUID
	AccountID            uuid.UUID
	MemberID             uuid.UUID
	Status               string
	RequestedAmountCents pgtype.Numeric
}

func (q *Queries) CreateRideAuthorization(ctx context.Context, arg CreateRideAuthorizationParams) (RideAuthorization, error) {
	row := q.db.QueryRow(ctx, createRideAuthorization,
		arg.RideID,
		arg.AccountID,
		arg.MemberID,
		arg.Status,
		arg.RequestedAmountCents,
	)
	var i RideAuthorization
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.AccountID,
		&i.MemberID,
		&i.Status,
		&i.RequestedAmountCents,
		&i.AuthorizedBy,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getBusinessAccount = `-- name: GetBusinessAccount :one
SELECT id, owner_id, name, currency, monthly_limit_cents, require_ride_approval, is_active, created_at, updated_at FROM business_accounts
WHERE id = $1
`

func (q *Queries) GetBusinessAccount(ctx context.Context, id uuid.UUID) (BusinessAccount, error) {
	row := q.db.QueryRow(ctx, getBusinessAccount, id)
	var i BusinessAccount
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Currency,
		&i.MonthlyLimitCents,
		&i.RequireRideApproval,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessMember = `-- name: GetBusinessMember :one
SELECT account_id, user_id, role, spending_limit_cents, status, created_at, updated_at FROM business_members
WHERE account_id = $1 AND user_id = $2
`

type GetBusinessMemberParams struct {
	AccountID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetBusinessMember(ctx context.Context, arg GetBusinessMemberParams) (BusinessMember, error) {
	row := q.db.QueryRow(ctx, getBusinessMember, arg.AccountID, arg.UserID)
	var i BusinessMember
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.Role,
		&i.SpendingLimitCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessMonthlyUsage = `-- name: GetBusinessMonthlyUsage :one
SELECT
    COUNT(*)::bigint AS ride_count,
    COALESCE(SUM(COALESCE(r.accepted_fare_cents, r.suggested_fare_cents)), 0)::numeric AS total_cents,
    COALESCE(SUM(CASE WHEN r.status = 'completed'
        THEN COALESCE(r.accepted_fare_cents, r.suggested_fare_cents) ELSE 0 END), 0)::numeric AS completed_cents
FROM rides r
WHERE r.business_account_id = $1
  AND r.status <> 'cancelled'
  AND NOT EXISTS (
      SELECT 1 FROM ride_authorizations ra
      WHERE ra.ride_id = r.id AND ra.status = 'rejected'
  )
  AND r.created_at >= date_trunc('month', $2::date)
  AND r.created_at < date_trunc('month', $2::date) + INTERVAL '1 month'
`

type GetBusinessMonthlyUsageParams struct {
	BusinessAccountID pgtype.UUID
	Column2           pgtype.Date
}

type GetBusinessMonthlyUsageRow struct {
	RideCount      int64
	TotalCents     pgtype.Numeric
	CompletedCents pgtype.Numeric
}

func (q *Queries) GetBusinessMonthlyUsage(ctx context.Context, arg GetBusinessMonthlyUsageParams) (GetBusinessMonthlyUsageRow, error) {
	row := q.db.QueryRow(ctx, getBusinessMonthlyUsage, arg.BusinessAccountID, arg.Column2)
	var i GetBusinessMonthlyUsageRow
	err := row.Scan(&i.RideCount, &i.TotalCents, &i.CompletedCents)
	return i, err
}

const getRideAuthorization = `-- name: GetRideAuthorization :one
SELECT id, ride_id, account_id, member_id, status, requested_amount_cents, authorized_by, decision_note, created_at, updated_at, decided_at FROM ride_authorizations
WHERE ride_id = $1
`

func (q *Queries) GetRideAuthorization(ctx context.Context, rideID uuid.UUID) (RideAuthorization, error) {
	row := q.db.QueryRow(ctx, getRideAuthorization, rideID)
	var i RideAuthorization
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.AccountID,
		&i.MemberID,
		&i.Status,
		&i.RequestedAmountCents,
		&i.AuthorizedBy,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listBusinessAccountsForUser = `-- name: ListBusinessAccountsForUser :many
SELECT DISTINCT ba.id, ba.owner_id, ba.name, ba.currency, ba.monthly_limit_cents, ba.require_ride_approval, ba.is_active, ba.created_at, ba.updated_at
FROM business_accounts ba
JOIN business_members bm ON bm.account_id = ba.id
WHERE bm.user_id = $1 AND ba.is_active
ORDER BY ba.created_at DESC, ba.id DESC
LIMIT $2 OFFSET $3
`

type ListBusinessAccountsForUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListBusinessAccountsForUser(ctx context.Context, arg ListBusinessAccountsForUserParams) ([]BusinessAccount, error) {
	rows, err := q.db.Query(ctx, listBusinessAccountsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessAccount
	for rows.Next() {
		var i BusinessAccount
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Currency,
			&i.MonthlyLimitCents,
			&i.RequireRideApproval,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessMembers = `-- name: ListBusinessMembers :many
SELECT account_id, user_id, role, spending_limit_cents, status, created_at, updated_at FROM business_members
WHERE account_id = $1
ORDER BY created_at ASC, user_id ASC
LIMIT $2 OFFSET $3
`

type ListBusinessMembersParams struct {
	AccountID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListBusinessMembers(ctx context.Context, arg ListBusinessMembersParams) ([]BusinessMember, error) {
	rows, err := q.db.Query(ctx, listBusinessMembers, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessMember
	for rows.Next() {
		var i BusinessMember
		if err := rows.Scan(
			&i.AccountID,
			&i.UserID,
			&i.Role,
			&i.SpendingLimitCents,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRideAuthorizations = `-- name: ListPendingRideAuthorizations :many
SELECT id, ride_id, account_id, member_id, status, requested_amount_cents, authorized_by, decision_note, created_at, updated_at, decided_at FROM ride_authorizations
WHERE account_id = $1 AND status = 'pending'
ORDER BY created_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type ListPendingRideAuthorizationsParams struct {
	AccountID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListPendingRideAuthorizations(ctx context.Context, arg ListPendingRideAuthorizationsParams) ([]RideAuthorization, error) {
	rows, err := q.db.Query(ctx, listPendingRideAuthorizations, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideAuthorization
	for rows.Next() {
		var i RideAuthorization
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.AccountID,
			&i.MemberID,
			&i.Status,
			&i.RequestedAmountCents,
			&i.AuthorizedBy,
			&i.DecisionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRideAuthorization = `-- name: RejectRideAuthorization :one
UPDATE ride_authorizations
SET status = 'rejected', authorized_by = $2, decision_note = $3,
    decided_at = NOW(), updated_at = NOW()
WHERE ride_id = $1 AND status = 'pending'
RETURNING id, ride_id, account_id, member_id, status, requested_amount_cents, authorized_by, decision_note, created_at, updated_at, decided_at
`

type RejectRideAuthorizationParams struct {
	RideID       uuid.UUID
	AuthorizedBy pgtype.UUID
	DecisionNote pgtype.Text
}

func (q *Queries) RejectRideAuthorization(ctx context.Context, arg RejectRideAuthorizationParams) (RideAuthorization, error) {
	row := q.db.QueryRow(ctx, rejectRideAuthorization, arg.RideID, arg.AuthorizedBy, arg.DecisionNote)
	var i RideAuthorization
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.AccountID,
		&i.MemberID,
		&i.Status,
		&i.RequestedAmountCents,
		&i.AuthorizedBy,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const updateBusinessAccountLimits = `-- name: UpdateBusinessAccountLimits :one
UPDATE business_accounts
SET monthly_limit_cents = $2,
    require_ride_approval = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, name, currency, monthly_limit_cents, require_ride_approval, is_active, created_at, updated_at
`

type UpdateBusinessAccountLimitsParams struct {
	ID                  uuid.UUID
	MonthlyLimitCents   pgtype.Numeric
	RequireRideApproval bool
}

func (q *Queries) UpdateBusinessAccountLimits(ctx context.Context, arg UpdateBusinessAccountLimitsParams) (BusinessAccount, error) {
	row := q.db.QueryRow(ctx, updateBusinessAccountLimits, arg.ID, arg.MonthlyLimitCents, arg.RequireRideApproval)
	var i BusinessAccount
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Currency,
		&i.MonthlyLimitCents,
		&i.RequireRideApproval,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBusinessMemberLimit = `-- name: UpdateBusinessMemberLimit :one
UPDATE business_members
SET spending_limit_cents = $3, status = $4, updated_at = NOW()
WHERE account_id = $1 AND user_id = $2
RETURNING account_id, user_id, role, spending_limit_cents, status, created_at, updated_at
`

type UpdateBusinessMemberLimitParams struct {
	AccountID          uuid.UUID
	UserID             uuid.UUID
	SpendingLimitCents pgtype.Numeric
	Status             string
}

func (q *Queries) UpdateBusinessMemberLimit(ctx context.Context, arg UpdateBusinessMemberLimitParams) (BusinessMember, error) {
	row := q.db.QueryRow(ctx, updateBusinessMemberLimit,
		arg.AccountID,
		arg.UserID,
		arg.SpendingLimitCents,
		arg.Status,
	)
	var i BusinessMember
	err := row.Scan(
		&i.AccountID,
		&i.UserID,
		&i.Role,
		&i.SpendingLimitCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
