// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"
)

const getAllConfig = `-- name: GetAllConfig :many
SELECT key, value, updated_at FROM config
ORDER BY key
`

func (q *Queries) GetAllConfig(ctx context.Context) ([]Config, error) {
	rows, err := q.db.Query(ctx, getAllConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfig = `-- name: GetConfig :one
SELECT key, value, updated_at FROM config
WHERE key = $1
`

func (q *Queries) GetConfig(ctx context.Context, key string) (Config, error) {
	row := q.db.QueryRow(ctx, getConfig, key)
	var i Config
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
