// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: corporate_billing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addInvoiceItem = `-- name: AddInvoiceItem :one
INSERT INTO corporate_invoice_items (invoice_id, description, ride_id, date, amount_cents, cost_center_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, invoice_id, description, ride_id, date, amount_cents, cost_center_id, created_at
`

type AddInvoiceItemParams struct {
	InvoiceID    uuid.UUID
	Description  string
	RideID       pgtype.UUID
	Date         pgtype.Timestamptz
	AmountCents  int64
	CostCenterID pgtype.UUID
}

func (q *Queries) AddInvoiceItem(ctx context.Context, arg AddInvoiceItemParams) (CorporateInvoiceItem, error) {
	row := q.db.QueryRow(ctx, addInvoiceItem,
		arg.InvoiceID,
		arg.Description,
		arg.RideID,
		arg.Date,
		arg.AmountCents,
		arg.CostCenterID,
	)
	var i CorporateInvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Description,
		&i.RideID,
		&i.Date,
		&i.AmountCents,
		&i.CostCenterID,
		&i.CreatedAt,
	)
	return i, err
}

const createCorporateInvoice = `-- name: CreateCorporateInvoice :one
INSERT INTO corporate_invoices (account_id, period_start, period_end, ride_count, total_cents, tax_cents, grand_total, status, due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, account_id, period_start, period_end, ride_count, total_cents, tax_cents, grand_total, status, due_date, sent_at, paid_at, created_at, updated_at
`

type CreateCorporateInvoiceParams struct {
	AccountID   uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	RideCount   int32
	TotalCents  int64
	TaxCents    int64
	GrandTotal  int64
	Status      string
	DueDate     pgtype.Timestamptz
}

func (q *Queries) CreateCorporateInvoice(ctx context.Context, arg CreateCorporateInvoiceParams) (CorporateInvoice, error) {
	row := q.db.QueryRow(ctx, createCorporateInvoice,
		arg.AccountID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RideCount,
		arg.TotalCents,
		arg.TaxCents,
		arg.GrandTotal,
		arg.Status,
		arg.DueDate,
	)
	var i CorporateInvoice
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.RideCount,
		&i.TotalCents,
		&i.TaxCents,
		&i.GrandTotal,
		&i.Status,
		&i.DueDate,
		&i.SentAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCostCenter = `-- name: CreateCostCenter :one
INSERT INTO cost_centers (account_id, name, code, budget_cents)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, name, code, budget_cents, spent_cents, active, created_at, updated_at
`

type CreateCostCenterParams struct {
	AccountID   uuid.UUID
	Name        string
	Code        string
	BudgetCents int64
}

func (q *Queries) CreateCostCenter(ctx context.Context, arg CreateCostCenterParams) (CostCenter, error) {
	row := q.db.QueryRow(ctx, createCostCenter,
		arg.AccountID,
		arg.Name,
		arg.Code,
		arg.BudgetCents,
	)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Code,
		&i.BudgetCents,
		&i.SpentCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCostCenter = `-- name: DeleteCostCenter :exec
DELETE FROM cost_centers
WHERE id = $1 AND account_id = $2
`

type DeleteCostCenterParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteCostCenter(ctx context.Context, arg DeleteCostCenterParams) error {
	_, err := q.db.Exec(ctx, deleteCostCenter, arg.ID, arg.AccountID)
	return err
}

const getCorporateInvoiceByID = `-- name: GetCorporateInvoiceByID :one
SELECT id, account_id, period_start, period_end, ride_count, total_cents, tax_cents, grand_total, status, due_date, sent_at, paid_at, created_at, updated_at FROM corporate_invoices
WHERE id = $1
`

func (q *Queries) GetCorporateInvoiceByID(ctx context.Context, id uuid.UUID) (CorporateInvoice, error) {
	row := q.db.QueryRow(ctx, getCorporateInvoiceByID, id)
	var i CorporateInvoice
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.RideCount,
		&i.TotalCents,
		&i.TaxCents,
		&i.GrandTotal,
		&i.Status,
		&i.DueDate,
		&i.SentAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCostCenterByID = `-- name: GetCostCenterByID :one
SELECT id, account_id, name, code, budget_cents, spent_cents, active, created_at, updated_at FROM cost_centers
WHERE id = $1
`

func (q *Queries) GetCostCenterByID(ctx context.Context, id uuid.UUID) (CostCenter, error) {
	row := q.db.QueryRow(ctx, getCostCenterByID, id)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Code,
		&i.BudgetCents,
		&i.SpentCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCorporateInvoicesByAccount = `-- name: ListCorporateInvoicesByAccount :many
SELECT id, account_id, period_start, period_end, ride_count, total_cents, tax_cents, grand_total, status, due_date, sent_at, paid_at, created_at, updated_at FROM corporate_invoices
WHERE account_id = $1
ORDER BY period_end DESC
LIMIT $2 OFFSET $3
`

type ListCorporateInvoicesByAccountParams struct {
	AccountID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListCorporateInvoicesByAccount(ctx context.Context, arg ListCorporateInvoicesByAccountParams) ([]CorporateInvoice, error) {
	rows, err := q.db.Query(ctx, listCorporateInvoicesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CorporateInvoice
	for rows.Next() {
		var i CorporateInvoice
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RideCount,
			&i.TotalCents,
			&i.TaxCents,
			&i.GrandTotal,
			&i.Status,
			&i.DueDate,
			&i.SentAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostCentersByAccount = `-- name: ListCostCentersByAccount :many
SELECT id, account_id, name, code, budget_cents, spent_cents, active, created_at, updated_at FROM cost_centers
WHERE account_id = $1
ORDER BY name
`

func (q *Queries) ListCostCentersByAccount(ctx context.Context, accountID uuid.UUID) ([]CostCenter, error) {
	rows, err := q.db.Query(ctx, listCostCentersByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CostCenter
	for rows.Next() {
		var i CostCenter
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Code,
			&i.BudgetCents,
			&i.SpentCents,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceItems = `-- name: ListInvoiceItems :many
SELECT id, invoice_id, description, ride_id, date, amount_cents, cost_center_id, created_at FROM corporate_invoice_items
WHERE invoice_id = $1
ORDER BY date DESC
`

func (q *Queries) ListInvoiceItems(ctx context.Context, invoiceID uuid.UUID) ([]CorporateInvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CorporateInvoiceItem
	for rows.Next() {
		var i CorporateInvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Description,
			&i.RideID,
			&i.Date,
			&i.AmountCents,
			&i.CostCenterID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueInvoices = `-- name: ListOverdueInvoices :many
SELECT id, account_id, period_start, period_end, ride_count, total_cents, tax_cents, grand_total, status, due_date, sent_at, paid_at, created_at, updated_at FROM corporate_invoices
WHERE status = 'sent' AND due_date < NOW()
ORDER BY due_date ASC
`

func (q *Queries) ListOverdueInvoices(ctx context.Context) ([]CorporateInvoice, error) {
	rows, err := q.db.Query(ctx, listOverdueInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CorporateInvoice
	for rows.Next() {
		var i CorporateInvoice
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RideCount,
			&i.TotalCents,
			&i.TaxCents,
			&i.GrandTotal,
			&i.Status,
			&i.DueDate,
			&i.SentAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCorporateInvoiceStatus = `-- name: UpdateCorporateInvoiceStatus :one
UPDATE corporate_invoices
SET status = $2, sent_at = $3, paid_at = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, account_id, period_start, period_end, ride_count, total_cents, tax_cents, grand_total, status, due_date, sent_at, paid_at, created_at, updated_at
`

type UpdateCorporateInvoiceStatusParams struct {
	ID     uuid.UUID
	Status string
	SentAt pgtype.Timestamptz
	PaidAt pgtype.Timestamptz
}

func (q *Queries) UpdateCorporateInvoiceStatus(ctx context.Context, arg UpdateCorporateInvoiceStatusParams) (CorporateInvoice, error) {
	row := q.db.QueryRow(ctx, updateCorporateInvoiceStatus,
		arg.ID,
		arg.Status,
		arg.SentAt,
		arg.PaidAt,
	)
	var i CorporateInvoice
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.RideCount,
		&i.TotalCents,
		&i.TaxCents,
		&i.GrandTotal,
		&i.Status,
		&i.DueDate,
		&i.SentAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCostCenter = `-- name: UpdateCostCenter :one
UPDATE cost_centers
SET name = $2, budget_cents = $3, active = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, account_id, name, code, budget_cents, spent_cents, active, created_at, updated_at
`

type UpdateCostCenterParams struct {
	ID          uuid.UUID
	Name        string
	BudgetCents int64
	Active      bool
}

func (q *Queries) UpdateCostCenter(ctx context.Context, arg UpdateCostCenterParams) (CostCenter, error) {
	row := q.db.QueryRow(ctx, updateCostCenter,
		arg.ID,
		arg.Name,
		arg.BudgetCents,
		arg.Active,
	)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Code,
		&i.BudgetCents,
		&i.SpentCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCostCenterSpending = `-- name: UpdateCostCenterSpending :one
UPDATE cost_centers
SET spent_cents = spent_cents + $2, updated_at = NOW()
WHERE id = $1
RETURNING id, account_id, name, code, budget_cents, spent_cents, active, created_at, updated_at
`

type UpdateCostCenterSpendingParams struct {
	ID         uuid.UUID
	SpentCents int64
}

func (q *Queries) UpdateCostCenterSpending(ctx context.Context, arg UpdateCostCenterSpendingParams) (CostCenter, error) {
	row := q.db.QueryRow(ctx, updateCostCenterSpending, arg.ID, arg.SpentCents)
	var i CostCenter
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Code,
		&i.BudgetCents,
		&i.SpentCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
