// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: driver_vehicle_profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDriverVehicleProfile = `-- name: CreateDriverVehicleProfile :one
INSERT INTO driver_vehicle_profiles (
    driver_id,
    license_plate,
    make,
    model,
    year,
    color,
    license_expiry_date,
    insurance_expiry_date,
    registration_expiry_date,
    inspection_expiry_date
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING driver_id, license_plate, make, model, year, color, license_expiry_date, insurance_expiry_date, registration_expiry_date, inspection_expiry_date, created_at, updated_at
`

type CreateDriverVehicleProfileParams struct {
	DriverID               uuid.UUID
	LicensePlate           string
	Make                   string
	Model                  string
	Year                   int32
	Color                  string
	LicenseExpiryDate      pgtype.Date
	InsuranceExpiryDate    pgtype.Date
	RegistrationExpiryDate pgtype.Date
	InspectionExpiryDate   pgtype.Date
}

func (q *Queries) CreateDriverVehicleProfile(ctx context.Context, arg CreateDriverVehicleProfileParams) (DriverVehicleProfile, error) {
	row := q.db.QueryRow(ctx, createDriverVehicleProfile,
		arg.DriverID,
		arg.LicensePlate,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Color,
		arg.LicenseExpiryDate,
		arg.InsuranceExpiryDate,
		arg.RegistrationExpiryDate,
		arg.InspectionExpiryDate,
	)
	var i DriverVehicleProfile
	err := row.Scan(
		&i.DriverID,
		&i.LicensePlate,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Color,
		&i.LicenseExpiryDate,
		&i.InsuranceExpiryDate,
		&i.RegistrationExpiryDate,
		&i.InspectionExpiryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriverVehicleProfile = `-- name: GetDriverVehicleProfile :one
SELECT driver_id, license_plate, make, model, year, color, license_expiry_date, insurance_expiry_date, registration_expiry_date, inspection_expiry_date, created_at, updated_at
FROM driver_vehicle_profiles
WHERE driver_id = $1
`

func (q *Queries) GetDriverVehicleProfile(ctx context.Context, driverID uuid.UUID) (DriverVehicleProfile, error) {
	row := q.db.QueryRow(ctx, getDriverVehicleProfile, driverID)
	var i DriverVehicleProfile
	err := row.Scan(
		&i.DriverID,
		&i.LicensePlate,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Color,
		&i.LicenseExpiryDate,
		&i.InsuranceExpiryDate,
		&i.RegistrationExpiryDate,
		&i.InspectionExpiryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDriverVehicleProfile = `-- name: UpdateDriverVehicleProfile :one
UPDATE driver_vehicle_profiles
SET license_plate = $2,
    make = $3,
    model = $4,
    year = $5,
    color = $6,
    license_expiry_date = $7,
    insurance_expiry_date = $8,
    registration_expiry_date = $9,
    inspection_expiry_date = $10,
    updated_at = NOW()
WHERE driver_id = $1
RETURNING driver_id, license_plate, make, model, year, color, license_expiry_date, insurance_expiry_date, registration_expiry_date, inspection_expiry_date, created_at, updated_at
`

type UpdateDriverVehicleProfileParams struct {
	DriverID               uuid.UUID
	LicensePlate           string
	Make                   string
	Model                  string
	Year                   int32
	Color                  string
	LicenseExpiryDate      pgtype.Date
	InsuranceExpiryDate    pgtype.Date
	RegistrationExpiryDate pgtype.Date
	InspectionExpiryDate   pgtype.Date
}

func (q *Queries) UpdateDriverVehicleProfile(ctx context.Context, arg UpdateDriverVehicleProfileParams) (DriverVehicleProfile, error) {
	row := q.db.QueryRow(ctx, updateDriverVehicleProfile,
		arg.DriverID,
		arg.LicensePlate,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.Color,
		arg.LicenseExpiryDate,
		arg.InsuranceExpiryDate,
		arg.RegistrationExpiryDate,
		arg.InspectionExpiryDate,
	)
	var i DriverVehicleProfile
	err := row.Scan(
		&i.DriverID,
		&i.LicensePlate,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.Color,
		&i.LicenseExpiryDate,
		&i.InsuranceExpiryDate,
		&i.RegistrationExpiryDate,
		&i.InspectionExpiryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
