// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: driver_availability.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getDriverAvailability = `-- name: GetDriverAvailability :one
SELECT driver_id, is_online, updated_at
FROM driver_availability
WHERE driver_id = $1
`

func (q *Queries) GetDriverAvailability(ctx context.Context, driverID uuid.UUID) (DriverAvailability, error) {
	row := q.db.QueryRow(ctx, getDriverAvailability, driverID)
	var i DriverAvailability
	err := row.Scan(&i.DriverID, &i.IsOnline, &i.UpdatedAt)
	return i, err
}

const setDriverAvailability = `-- name: SetDriverAvailability :one
INSERT INTO driver_availability (driver_id, is_online, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (driver_id)
DO UPDATE SET is_online = EXCLUDED.is_online, updated_at = NOW()
RETURNING driver_id, is_online, updated_at
`

type SetDriverAvailabilityParams struct {
	DriverID uuid.UUID
	IsOnline bool
}

func (q *Queries) SetDriverAvailability(ctx context.Context, arg SetDriverAvailabilityParams) (DriverAvailability, error) {
	row := q.db.QueryRow(ctx, setDriverAvailability, arg.DriverID, arg.IsOnline)
	var i DriverAvailability
	err := row.Scan(&i.DriverID, &i.IsOnline, &i.UpdatedAt)
	return i, err
}
