// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: driver_locations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStaleDriverLocations = `-- name: DeleteStaleDriverLocations :exec
DELETE FROM driver_locations
WHERE updated_at < NOW() - interval '1 hour'
`

func (q *Queries) DeleteStaleDriverLocations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteStaleDriverLocations)
	return err
}

const findNearbyDrivers = `-- name: FindNearbyDrivers :many
SELECT d.driver_id, d.location, d.heading, d.updated_at,
       u.name AS driver_name, u.rating,
       sqrt(power((d.location[0] - ($2::point)[0])::numeric, 2) +
            power((d.location[1] - ($2::point)[1])::numeric, 2)) * 111320 AS distance_meters
FROM driver_locations d
JOIN users u ON u.id = d.driver_id AND u.is_active = true AND u.role = 'driver'
JOIN driver_kyc k ON k.driver_id = d.driver_id AND k.status = 'approved'
WHERE d.updated_at > NOW() - interval '10 minutes'
  AND sqrt(power((d.location[0] - ($2::point)[0])::numeric, 2) +
           power((d.location[1] - ($2::point)[1])::numeric, 2)) * 111320 < $3::float8
ORDER BY distance_meters ASC
LIMIT $1
`

type FindNearbyDriversParams struct {
	Limit        int32
	Location     pgtype.Point
	RadiusMeters float64
}

type FindNearbyDriversRow struct {
	DriverID       uuid.UUID
	Location       pgtype.Point
	Heading        pgtype.Numeric
	UpdatedAt      pgtype.Timestamptz
	DriverName     string
	Rating         pgtype.Numeric
	DistanceMeters int32
}

func (q *Queries) FindNearbyDrivers(ctx context.Context, arg FindNearbyDriversParams) ([]FindNearbyDriversRow, error) {
	rows, err := q.db.Query(ctx, findNearbyDrivers, arg.Limit, arg.Location, arg.RadiusMeters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNearbyDriversRow
	for rows.Next() {
		var i FindNearbyDriversRow
		if err := rows.Scan(
			&i.DriverID,
			&i.Location,
			&i.Heading,
			&i.UpdatedAt,
			&i.DriverName,
			&i.Rating,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDriverLocation = `-- name: GetDriverLocation :one
SELECT driver_id, location, heading, updated_at FROM driver_locations
WHERE driver_id = $1
`

func (q *Queries) GetDriverLocation(ctx context.Context, driverID uuid.UUID) (DriverLocation, error) {
	row := q.db.QueryRow(ctx, getDriverLocation, driverID)
	var i DriverLocation
	err := row.Scan(
		&i.DriverID,
		&i.Location,
		&i.Heading,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDriverLocation = `-- name: UpsertDriverLocation :one
INSERT INTO driver_locations (driver_id, location, heading, updated_at)
VALUES ($1, $2::point, $3, NOW())
ON CONFLICT (driver_id)
DO UPDATE SET location = EXCLUDED.location, heading = EXCLUDED.heading, updated_at = NOW()
RETURNING driver_id, location, heading, updated_at
`

type UpsertDriverLocationParams struct {
	DriverID uuid.UUID
	Column2  pgtype.Point
	Heading  pgtype.Numeric
}

func (q *Queries) UpsertDriverLocation(ctx context.Context, arg UpsertDriverLocationParams) (DriverLocation, error) {
	row := q.db.QueryRow(ctx, upsertDriverLocation, arg.DriverID, arg.Column2, arg.Heading)
	var i DriverLocation
	err := row.Scan(
		&i.DriverID,
		&i.Location,
		&i.Heading,
		&i.UpdatedAt,
	)
	return i, err
}
