// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: driver_wallets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDriverBalance = `-- name: AddDriverBalance :one
UPDATE driver_wallets
SET balance_cents = balance_cents + $2,
    total_earned_cents = total_earned_cents + CASE WHEN $2 > 0 THEN $2 ELSE 0 END,
    updated_at = NOW()
WHERE driver_id = $1
RETURNING driver_id, balance_cents, pending_cents, total_earned_cents, total_paid_cents, currency, last_payout_at, updated_at, created_at
`

type AddDriverBalanceParams struct {
	DriverID     uuid.UUID
	BalanceCents int64
}

func (q *Queries) AddDriverBalance(ctx context.Context, arg AddDriverBalanceParams) (DriverWallet, error) {
	row := q.db.QueryRow(ctx, addDriverBalance, arg.DriverID, arg.BalanceCents)
	var i DriverWallet
	err := row.Scan(
		&i.DriverID,
		&i.BalanceCents,
		&i.PendingCents,
		&i.TotalEarnedCents,
		&i.TotalPaidCents,
		&i.Currency,
		&i.LastPayoutAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const addDriverEarning = `-- name: AddDriverEarning :one
UPDATE driver_wallets
SET balance_cents = balance_cents + $2,
    pending_cents = pending_cents + $2,
    total_earned_cents = total_earned_cents + $2,
    updated_at = NOW()
WHERE driver_id = $1
RETURNING driver_id, balance_cents, pending_cents, total_earned_cents, total_paid_cents, currency, last_payout_at, updated_at, created_at
`

type AddDriverEarningParams struct {
	DriverID     uuid.UUID
	BalanceCents int64
}

func (q *Queries) AddDriverEarning(ctx context.Context, arg AddDriverEarningParams) (DriverWallet, error) {
	row := q.db.QueryRow(ctx, addDriverEarning, arg.DriverID, arg.BalanceCents)
	var i DriverWallet
	err := row.Scan(
		&i.DriverID,
		&i.BalanceCents,
		&i.PendingCents,
		&i.TotalEarnedCents,
		&i.TotalPaidCents,
		&i.Currency,
		&i.LastPayoutAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const clearPendingEarnings = `-- name: ClearPendingEarnings :one
UPDATE driver_wallets
SET pending_cents = GREATEST(0, pending_cents - $2),
    updated_at = NOW()
WHERE driver_id = $1
RETURNING driver_id, balance_cents, pending_cents, total_earned_cents, total_paid_cents, currency, last_payout_at, updated_at, created_at
`

type ClearPendingEarningsParams struct {
	DriverID     uuid.UUID
	PendingCents int64
}

func (q *Queries) ClearPendingEarnings(ctx context.Context, arg ClearPendingEarningsParams) (DriverWallet, error) {
	row := q.db.QueryRow(ctx, clearPendingEarnings, arg.DriverID, arg.PendingCents)
	var i DriverWallet
	err := row.Scan(
		&i.DriverID,
		&i.BalanceCents,
		&i.PendingCents,
		&i.TotalEarnedCents,
		&i.TotalPaidCents,
		&i.Currency,
		&i.LastPayoutAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDriverWallet = `-- name: CreateDriverWallet :exec
INSERT INTO driver_wallets (driver_id)
VALUES ($1)
ON CONFLICT (driver_id) DO NOTHING
`

func (q *Queries) CreateDriverWallet(ctx context.Context, driverID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createDriverWallet, driverID)
	return err
}

const createWalletTransaction = `-- name: CreateWalletTransaction :exec
INSERT INTO wallet_transactions (driver_id, type, amount_cents, balance_after, reference_id, reference_type, description, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateWalletTransactionParams struct {
	DriverID      uuid.UUID
	Type          string
	AmountCents   int64
	BalanceAfter  int64
	ReferenceID   pgtype.UUID
	ReferenceType pgtype.Text
	Description   pgtype.Text
	Status        string
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) error {
	_, err := q.db.Exec(ctx, createWalletTransaction,
		arg.DriverID,
		arg.Type,
		arg.AmountCents,
		arg.BalanceAfter,
		arg.ReferenceID,
		arg.ReferenceType,
		arg.Description,
		arg.Status,
	)
	return err
}

const deductDriverBalance = `-- name: DeductDriverBalance :one
UPDATE driver_wallets
SET balance_cents = balance_cents - $2,
    total_paid_cents = total_paid_cents + CASE WHEN $2 > 0 THEN $2 ELSE 0 END,
    updated_at = NOW()
WHERE driver_id = $1 AND balance_cents >= $2
RETURNING driver_id, balance_cents, pending_cents, total_earned_cents, total_paid_cents, currency, last_payout_at, updated_at, created_at
`

type DeductDriverBalanceParams struct {
	DriverID     uuid.UUID
	BalanceCents int64
}

func (q *Queries) DeductDriverBalance(ctx context.Context, arg DeductDriverBalanceParams) (DriverWallet, error) {
	row := q.db.QueryRow(ctx, deductDriverBalance, arg.DriverID, arg.BalanceCents)
	var i DriverWallet
	err := row.Scan(
		&i.DriverID,
		&i.BalanceCents,
		&i.PendingCents,
		&i.TotalEarnedCents,
		&i.TotalPaidCents,
		&i.Currency,
		&i.LastPayoutAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDriverWallet = `-- name: GetDriverWallet :one
SELECT driver_id, balance_cents, pending_cents, total_earned_cents, total_paid_cents, currency, last_payout_at, updated_at, created_at FROM driver_wallets
WHERE driver_id = $1
`

func (q *Queries) GetDriverWallet(ctx context.Context, driverID uuid.UUID) (DriverWallet, error) {
	row := q.db.QueryRow(ctx, getDriverWallet, driverID)
	var i DriverWallet
	err := row.Scan(
		&i.DriverID,
		&i.BalanceCents,
		&i.PendingCents,
		&i.TotalEarnedCents,
		&i.TotalPaidCents,
		&i.Currency,
		&i.LastPayoutAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletEarningsSummary = `-- name: GetWalletEarningsSummary :one
SELECT 
    COALESCE(SUM(CASE WHEN type = 'earning' AND created_at >= NOW() - INTERVAL '1 day' THEN amount_cents ELSE 0 END), 0) as today_cents,
    COALESCE(SUM(CASE WHEN type = 'earning' AND created_at >= NOW() - INTERVAL '7 days' THEN amount_cents ELSE 0 END), 0) as week_cents,
    COALESCE(SUM(CASE WHEN type = 'earning' AND created_at >= NOW() - INTERVAL '30 days' THEN amount_cents ELSE 0 END), 0) as month_cents,
    COALESCE(SUM(CASE WHEN type = 'earning' THEN amount_cents ELSE 0 END), 0) as total_cents
FROM wallet_transactions
WHERE driver_id = $1 AND type = 'earning' AND status = 'completed'
`

type GetWalletEarningsSummaryRow struct {
	TodayCents interface{}
	WeekCents  interface{}
	MonthCents interface{}
	TotalCents interface{}
}

func (q *Queries) GetWalletEarningsSummary(ctx context.Context, driverID uuid.UUID) (GetWalletEarningsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getWalletEarningsSummary, driverID)
	var i GetWalletEarningsSummaryRow
	err := row.Scan(
		&i.TodayCents,
		&i.WeekCents,
		&i.MonthCents,
		&i.TotalCents,
	)
	return i, err
}

const getWalletTransactionByID = `-- name: GetWalletTransactionByID :one
SELECT id, driver_id, type, amount_cents, balance_after, reference_id, reference_type, description, status, created_at FROM wallet_transactions
WHERE id = $1
`

func (q *Queries) GetWalletTransactionByID(ctx context.Context, id uuid.UUID) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, getWalletTransactionByID, id)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.Type,
		&i.AmountCents,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, driver_id, type, amount_cents, balance_after, reference_id, reference_type, description, status, created_at FROM wallet_transactions
WHERE driver_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	DriverID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, arg.DriverID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletTransaction
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.Type,
			&i.AmountCents,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastPayout = `-- name: UpdateLastPayout :exec
UPDATE driver_wallets
SET last_payout_at = NOW(),
    updated_at = NOW()
WHERE driver_id = $1
`

func (q *Queries) UpdateLastPayout(ctx context.Context, driverID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastPayout, driverID)
	return err
}
