// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emergency_contacts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEmergencyContact = `-- name: CreateEmergencyContact :one
INSERT INTO emergency_contacts (user_id, name, phone, relationship)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, phone, relationship, created_at, updated_at
`

type CreateEmergencyContactParams struct {
	UserID       uuid.UUID
	Name         string
	Phone        string
	Relationship string
}

func (q *Queries) CreateEmergencyContact(ctx context.Context, arg CreateEmergencyContactParams) (EmergencyContact, error) {
	row := q.db.QueryRow(ctx, createEmergencyContact,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Relationship,
	)
	var i EmergencyContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Relationship,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmergencyContact = `-- name: DeleteEmergencyContact :one
DELETE FROM emergency_contacts
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, phone, relationship, created_at, updated_at
`

type DeleteEmergencyContactParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteEmergencyContact(ctx context.Context, arg DeleteEmergencyContactParams) (EmergencyContact, error) {
	row := q.db.QueryRow(ctx, deleteEmergencyContact, arg.ID, arg.UserID)
	var i EmergencyContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Relationship,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmergencyContact = `-- name: GetEmergencyContact :one
SELECT id, user_id, name, phone, relationship, created_at, updated_at FROM emergency_contacts
WHERE id = $1 AND user_id = $2
`

type GetEmergencyContactParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetEmergencyContact(ctx context.Context, arg GetEmergencyContactParams) (EmergencyContact, error) {
	row := q.db.QueryRow(ctx, getEmergencyContact, arg.ID, arg.UserID)
	var i EmergencyContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Relationship,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmergencyContacts = `-- name: ListEmergencyContacts :many
SELECT id, user_id, name, phone, relationship, created_at, updated_at FROM emergency_contacts
WHERE user_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListEmergencyContacts(ctx context.Context, userID uuid.UUID) ([]EmergencyContact, error) {
	rows, err := q.db.Query(ctx, listEmergencyContacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmergencyContact
	for rows.Next() {
		var i EmergencyContact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Relationship,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmergencyContact = `-- name: UpdateEmergencyContact :one
UPDATE emergency_contacts
SET name = $3, phone = $4, relationship = $5, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, phone, relationship, created_at, updated_at
`

type UpdateEmergencyContactParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Phone        string
	Relationship string
}

func (q *Queries) UpdateEmergencyContact(ctx context.Context, arg UpdateEmergencyContactParams) (EmergencyContact, error) {
	row := q.db.QueryRow(ctx, updateEmergencyContact,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Relationship,
	)
	var i EmergencyContact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Relationship,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
