// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRideDispute = `-- name: CreateRideDispute :one
INSERT INTO ride_disputes (ride_id, filed_by, category, description)
SELECT $1, $2, $3, $4
FROM rides
WHERE id = $1
  AND (rider_id = $2 OR driver_id = $2)
RETURNING id, ride_id, filed_by, category, description, status, resolution_note, resolved_by, created_at, updated_at, resolved_at
`

type CreateRideDisputeParams struct {
	RideID      uuid.UUID
	FiledBy     uuid.UUID
	Category    string
	Description string
}

func (q *Queries) CreateRideDispute(ctx context.Context, arg CreateRideDisputeParams) (RideDispute, error) {
	row := q.db.QueryRow(ctx, createRideDispute,
		arg.RideID,
		arg.FiledBy,
		arg.Category,
		arg.Description,
	)
	var i RideDispute
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.FiledBy,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.ResolutionNote,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createRideReview = `-- name: CreateRideReview :one
INSERT INTO ride_reviews (ride_id, reviewer_id, reviewee_id, rating, comment)
SELECT $1, $2, $3, $4, $5
FROM rides
WHERE id = $1
  AND status = 'completed'
  AND (
      (rider_id = $2 AND driver_id = $3)
      OR (driver_id = $2 AND rider_id = $3)
  )
ON CONFLICT (ride_id, reviewer_id) DO NOTHING
RETURNING id, ride_id, reviewer_id, reviewee_id, rating, comment, created_at
`

type CreateRideReviewParams struct {
	RideID     uuid.UUID
	ReviewerID uuid.UUID
	RevieweeID uuid.UUID
	Rating     int16
	Comment    string
}

func (q *Queries) CreateRideReview(ctx context.Context, arg CreateRideReviewParams) (RideReview, error) {
	row := q.db.QueryRow(ctx, createRideReview,
		arg.RideID,
		arg.ReviewerID,
		arg.RevieweeID,
		arg.Rating,
		arg.Comment,
	)
	var i RideReview
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.ReviewerID,
		&i.RevieweeID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const createSupportTicket = `-- name: CreateSupportTicket :one
INSERT INTO support_tickets (ride_id, created_by, category, subject, description)
SELECT $1, $2, $3, $4, $5
FROM rides
WHERE id = $1
  AND (rider_id = $2 OR driver_id = $2)
RETURNING id, ride_id, created_by, category, subject, description, status, resolution_note, updated_by, created_at, updated_at, resolved_at
`

type CreateSupportTicketParams struct {
	RideID      uuid.UUID
	CreatedBy   uuid.UUID
	Category    string
	Subject     string
	Description string
}

func (q *Queries) CreateSupportTicket(ctx context.Context, arg CreateSupportTicketParams) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, createSupportTicket,
		arg.RideID,
		arg.CreatedBy,
		arg.Category,
		arg.Subject,
		arg.Description,
	)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.CreatedBy,
		&i.Category,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.ResolutionNote,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getDriverEarningsSummary = `-- name: GetDriverEarningsSummary :one
WITH completed_rides AS (
    SELECT
        r.id,
        COALESCE(r.accepted_fare_cents, r.suggested_fare_cents) AS gross_fare
    FROM rides r
    WHERE r.driver_id = $1
      AND r.status = 'completed'
),
completed_charges AS (
    SELECT DISTINCT ON (pc.ride_id)
        pc.ride_id,
        pc.amount_cents
    FROM payment_charges pc
    JOIN completed_rides cr ON cr.id = pc.ride_id
    WHERE pc.status = 'completed'
    ORDER BY pc.ride_id, pc.completed_at DESC NULLS LAST, pc.created_at DESC, pc.id DESC
)
SELECT
    COUNT(*)::bigint AS completed_rides,
    COALESCE(SUM(cr.gross_fare), 0)::numeric AS gross_fares,
    COALESCE(SUM(CASE WHEN cp.ride_id IS NOT NULL THEN cp.amount_due ELSE 0 END), 0)::numeric AS cash_earnings,
    COALESCE(SUM(CASE WHEN cc.ride_id IS NOT NULL THEN cc.amount_cents ELSE 0 END), 0)::numeric AS digital_earnings,
    COALESCE(SUM(CASE
        WHEN cp.ride_id IS NOT NULL THEN cp.amount_due
        WHEN cc.ride_id IS NOT NULL THEN cc.amount_cents
        ELSE 0
    END), 0)::numeric AS total_earnings,
    COALESCE(SUM(CASE
        WHEN cp.ride_id IS NULL AND cc.ride_id IS NULL THEN cr.gross_fare
        ELSE 0
    END), 0)::numeric AS unpaid_fares
FROM completed_rides cr
LEFT JOIN cash_payments cp ON cp.ride_id = cr.id
LEFT JOIN completed_charges cc ON cc.ride_id = cr.id
`

type GetDriverEarningsSummaryRow struct {
	CompletedRides  int64
	GrossFares      pgtype.Numeric
	CashEarnings    pgtype.Numeric
	DigitalEarnings pgtype.Numeric
	TotalEarnings   pgtype.Numeric
	UnpaidFares     pgtype.Numeric
}

func (q *Queries) GetDriverEarningsSummary(ctx context.Context, driverID pgtype.UUID) (GetDriverEarningsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDriverEarningsSummary, driverID)
	var i GetDriverEarningsSummaryRow
	err := row.Scan(
		&i.CompletedRides,
		&i.GrossFares,
		&i.CashEarnings,
		&i.DigitalEarnings,
		&i.TotalEarnings,
		&i.UnpaidFares,
	)
	return i, err
}

const getRideDispute = `-- name: GetRideDispute :one
SELECT id, ride_id, filed_by, category, description, status, resolution_note, resolved_by, created_at, updated_at, resolved_at FROM ride_disputes
WHERE id = $1
`

func (q *Queries) GetRideDispute(ctx context.Context, id uuid.UUID) (RideDispute, error) {
	row := q.db.QueryRow(ctx, getRideDispute, id)
	var i RideDispute
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.FiledBy,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.ResolutionNote,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getRideReviews = `-- name: GetRideReviews :many
SELECT id, ride_id, reviewer_id, reviewee_id, rating, comment, created_at FROM ride_reviews
WHERE ride_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) GetRideReviews(ctx context.Context, rideID uuid.UUID) ([]RideReview, error) {
	rows, err := q.db.Query(ctx, getRideReviews, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideReview
	for rows.Next() {
		var i RideReview
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.ReviewerID,
			&i.RevieweeID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupportTicket = `-- name: GetSupportTicket :one
SELECT id, ride_id, created_by, category, subject, description, status, resolution_note, updated_by, created_at, updated_at, resolved_at FROM support_tickets
WHERE id = $1
`

func (q *Queries) GetSupportTicket(ctx context.Context, id uuid.UUID) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, getSupportTicket, id)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.CreatedBy,
		&i.Category,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.ResolutionNote,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listRideDisputes = `-- name: ListRideDisputes :many
SELECT id, ride_id, filed_by, category, description, status, resolution_note, resolved_by, created_at, updated_at, resolved_at FROM ride_disputes
WHERE ride_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListRideDisputes(ctx context.Context, rideID uuid.UUID) ([]RideDispute, error) {
	rows, err := q.db.Query(ctx, listRideDisputes, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideDispute
	for rows.Next() {
		var i RideDispute
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.FiledBy,
			&i.Category,
			&i.Description,
			&i.Status,
			&i.ResolutionNote,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRideDisputesAdmin = `-- name: ListRideDisputesAdmin :many
SELECT id, ride_id, filed_by, category, description, status, resolution_note, resolved_by, created_at, updated_at, resolved_at FROM ride_disputes
WHERE ($1::text = '' OR status = $1::text)
ORDER BY updated_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListRideDisputesAdminParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListRideDisputesAdmin(ctx context.Context, arg ListRideDisputesAdminParams) ([]RideDispute, error) {
	rows, err := q.db.Query(ctx, listRideDisputesAdmin, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideDispute
	for rows.Next() {
		var i RideDispute
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.FiledBy,
			&i.Category,
			&i.Description,
			&i.Status,
			&i.ResolutionNote,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportTicketsAdmin = `-- name: ListSupportTicketsAdmin :many
SELECT id, ride_id, created_by, category, subject, description, status, resolution_note, updated_by, created_at, updated_at, resolved_at FROM support_tickets
WHERE ($1::text = '' OR status = $1::text)
ORDER BY updated_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListSupportTicketsAdminParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListSupportTicketsAdmin(ctx context.Context, arg ListSupportTicketsAdminParams) ([]SupportTicket, error) {
	rows, err := q.db.Query(ctx, listSupportTicketsAdmin, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportTicket
	for rows.Next() {
		var i SupportTicket
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.CreatedBy,
			&i.Category,
			&i.Subject,
			&i.Description,
			&i.Status,
			&i.ResolutionNote,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportTicketsByUser = `-- name: ListSupportTicketsByUser :many
SELECT id, ride_id, created_by, category, subject, description, status, resolution_note, updated_by, created_at, updated_at, resolved_at FROM support_tickets
WHERE created_by = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListSupportTicketsByUserParams struct {
	CreatedBy uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListSupportTicketsByUser(ctx context.Context, arg ListSupportTicketsByUserParams) ([]SupportTicket, error) {
	rows, err := q.db.Query(ctx, listSupportTicketsByUser, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportTicket
	for rows.Next() {
		var i SupportTicket
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.CreatedBy,
			&i.Category,
			&i.Subject,
			&i.Description,
			&i.Status,
			&i.ResolutionNote,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportTicketsForRide = `-- name: ListSupportTicketsForRide :many
SELECT id, ride_id, created_by, category, subject, description, status, resolution_note, updated_by, created_at, updated_at, resolved_at FROM support_tickets
WHERE ride_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListSupportTicketsForRide(ctx context.Context, rideID uuid.UUID) ([]SupportTicket, error) {
	rows, err := q.db.Query(ctx, listSupportTicketsForRide, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportTicket
	for rows.Next() {
		var i SupportTicket
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.CreatedBy,
			&i.Category,
			&i.Subject,
			&i.Description,
			&i.Status,
			&i.ResolutionNote,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshUserRating = `-- name: RefreshUserRating :one
UPDATE users
SET rating = COALESCE((
    SELECT ROUND(AVG(rating)::numeric, 2)
    FROM ride_reviews
    WHERE reviewee_id = $1
), 0),
updated_at = NOW()
WHERE id = $1
RETURNING rating
`

func (q *Queries) RefreshUserRating(ctx context.Context, revieweeID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, refreshUserRating, revieweeID)
	var rating pgtype.Numeric
	err := row.Scan(&rating)
	return rating, err
}

const updateRideDisputeStatus = `-- name: UpdateRideDisputeStatus :one
UPDATE ride_disputes
SET status = $2,
    resolution_note = $3,
    resolved_by = CASE
        WHEN $2 IN ('resolved', 'rejected') THEN $4
        ELSE NULL
    END,
    updated_at = NOW(),
    resolved_at = CASE
        WHEN $2 IN ('resolved', 'rejected') THEN COALESCE(resolved_at, NOW())
        ELSE NULL
    END
WHERE id = $1
RETURNING id, ride_id, filed_by, category, description, status, resolution_note, resolved_by, created_at, updated_at, resolved_at
`

type UpdateRideDisputeStatusParams struct {
	ID             uuid.UUID
	Status         string
	ResolutionNote pgtype.Text
	ResolvedBy     pgtype.UUID
}

func (q *Queries) UpdateRideDisputeStatus(ctx context.Context, arg UpdateRideDisputeStatusParams) (RideDispute, error) {
	row := q.db.QueryRow(ctx, updateRideDisputeStatus,
		arg.ID,
		arg.Status,
		arg.ResolutionNote,
		arg.ResolvedBy,
	)
	var i RideDispute
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.FiledBy,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.ResolutionNote,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const updateSupportTicketStatus = `-- name: UpdateSupportTicketStatus :one
UPDATE support_tickets
SET status = $2,
    resolution_note = $3,
    updated_by = $4,
    updated_at = NOW(),
    resolved_at = CASE
        WHEN $2 IN ('resolved', 'closed') THEN COALESCE(resolved_at, NOW())
        ELSE NULL
    END
WHERE id = $1
RETURNING id, ride_id, created_by, category, subject, description, status, resolution_note, updated_by, created_at, updated_at, resolved_at
`

type UpdateSupportTicketStatusParams struct {
	ID             uuid.UUID
	Status         string
	ResolutionNote pgtype.Text
	UpdatedBy      pgtype.UUID
}

func (q *Queries) UpdateSupportTicketStatus(ctx context.Context, arg UpdateSupportTicketStatusParams) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, updateSupportTicketStatus,
		arg.ID,
		arg.Status,
		arg.ResolutionNote,
		arg.UpdatedBy,
	)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.CreatedBy,
		&i.Category,
		&i.Subject,
		&i.Description,
		&i.Status,
		&i.ResolutionNote,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
