// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_verifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveIdentityVerification = `-- name: ApproveIdentityVerification :one
UPDATE identity_verifications
SET status = 'verified', verified_at = NOW(), verified_by = $2, confidence_score = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, id_document_type, id_document_url, selfie_url, verified_at, verified_by, confidence_score, rejection_reason, expires_at, created_at, updated_at
`

type ApproveIdentityVerificationParams struct {
	ID              uuid.UUID
	VerifiedBy      pgtype.UUID
	ConfidenceScore pgtype.Numeric
}

func (q *Queries) ApproveIdentityVerification(ctx context.Context, arg ApproveIdentityVerificationParams) (IdentityVerification, error) {
	row := q.db.QueryRow(ctx, approveIdentityVerification, arg.ID, arg.VerifiedBy, arg.ConfidenceScore)
	var i IdentityVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.IDDocumentType,
		&i.IDDocumentUrl,
		&i.SelfieUrl,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.ConfidenceScore,
		&i.RejectionReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDriverBadge = `-- name: CreateDriverBadge :one
INSERT INTO driver_badges (driver_id, badge_type, display_name, description, valid_until)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, driver_id, badge_type, display_name, description, earned_at, valid_until, active, created_at
`

type CreateDriverBadgeParams struct {
	DriverID    uuid.UUID
	BadgeType   string
	DisplayName string
	Description pgtype.Text
	ValidUntil  pgtype.Timestamptz
}

func (q *Queries) CreateDriverBadge(ctx context.Context, arg CreateDriverBadgeParams) (DriverBadge, error) {
	row := q.db.QueryRow(ctx, createDriverBadge,
		arg.DriverID,
		arg.BadgeType,
		arg.DisplayName,
		arg.Description,
		arg.ValidUntil,
	)
	var i DriverBadge
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.BadgeType,
		&i.DisplayName,
		&i.Description,
		&i.EarnedAt,
		&i.ValidUntil,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createIdentityVerification = `-- name: CreateIdentityVerification :one
INSERT INTO identity_verifications (user_id, status, id_document_type, id_document_url, selfie_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, status, id_document_type, id_document_url, selfie_url, verified_at, verified_by, confidence_score, rejection_reason, expires_at, created_at, updated_at
`

type CreateIdentityVerificationParams struct {
	UserID         uuid.UUID
	Status         string
	IDDocumentType pgtype.Text
	IDDocumentUrl  pgtype.Text
	SelfieUrl      pgtype.Text
}

func (q *Queries) CreateIdentityVerification(ctx context.Context, arg CreateIdentityVerificationParams) (IdentityVerification, error) {
	row := q.db.QueryRow(ctx, createIdentityVerification,
		arg.UserID,
		arg.Status,
		arg.IDDocumentType,
		arg.IDDocumentUrl,
		arg.SelfieUrl,
	)
	var i IdentityVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.IDDocumentType,
		&i.IDDocumentUrl,
		&i.SelfieUrl,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.ConfidenceScore,
		&i.RejectionReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDriverBadge = `-- name: DeactivateDriverBadge :exec
UPDATE driver_badges
SET active = FALSE
WHERE id = $1
`

func (q *Queries) DeactivateDriverBadge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateDriverBadge, id)
	return err
}

const expireDriverBadges = `-- name: ExpireDriverBadges :exec
UPDATE driver_badges
SET active = FALSE
WHERE valid_until < NOW() AND active = TRUE
`

func (q *Queries) ExpireDriverBadges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireDriverBadges)
	return err
}

const getIdentityVerificationByID = `-- name: GetIdentityVerificationByID :one
SELECT id, user_id, status, id_document_type, id_document_url, selfie_url, verified_at, verified_by, confidence_score, rejection_reason, expires_at, created_at, updated_at FROM identity_verifications
WHERE id = $1
`

func (q *Queries) GetIdentityVerificationByID(ctx context.Context, id uuid.UUID) (IdentityVerification, error) {
	row := q.db.QueryRow(ctx, getIdentityVerificationByID, id)
	var i IdentityVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.IDDocumentType,
		&i.IDDocumentUrl,
		&i.SelfieUrl,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.ConfidenceScore,
		&i.RejectionReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityVerificationByUser = `-- name: GetIdentityVerificationByUser :one
SELECT id, user_id, status, id_document_type, id_document_url, selfie_url, verified_at, verified_by, confidence_score, rejection_reason, expires_at, created_at, updated_at FROM identity_verifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetIdentityVerificationByUser(ctx context.Context, userID uuid.UUID) (IdentityVerification, error) {
	row := q.db.QueryRow(ctx, getIdentityVerificationByUser, userID)
	var i IdentityVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.IDDocumentType,
		&i.IDDocumentUrl,
		&i.SelfieUrl,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.ConfidenceScore,
		&i.RejectionReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDriverBadges = `-- name: ListDriverBadges :many
SELECT id, driver_id, badge_type, display_name, description, earned_at, valid_until, active, created_at FROM driver_badges
WHERE driver_id = $1 AND active = TRUE
ORDER BY earned_at DESC
`

func (q *Queries) ListDriverBadges(ctx context.Context, driverID uuid.UUID) ([]DriverBadge, error) {
	rows, err := q.db.Query(ctx, listDriverBadges, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriverBadge
	for rows.Next() {
		var i DriverBadge
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.BadgeType,
			&i.DisplayName,
			&i.Description,
			&i.EarnedAt,
			&i.ValidUntil,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingVerifications = `-- name: ListPendingVerifications :many
SELECT id, user_id, status, id_document_type, id_document_url, selfie_url, verified_at, verified_by, confidence_score, rejection_reason, expires_at, created_at, updated_at FROM identity_verifications
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingVerifications(ctx context.Context, limit int32) ([]IdentityVerification, error) {
	rows, err := q.db.Query(ctx, listPendingVerifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityVerification
	for rows.Next() {
		var i IdentityVerification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.IDDocumentType,
			&i.IDDocumentUrl,
			&i.SelfieUrl,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.ConfidenceScore,
			&i.RejectionReason,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectIdentityVerification = `-- name: RejectIdentityVerification :one
UPDATE identity_verifications
SET status = 'rejected', rejection_reason = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, id_document_type, id_document_url, selfie_url, verified_at, verified_by, confidence_score, rejection_reason, expires_at, created_at, updated_at
`

type RejectIdentityVerificationParams struct {
	ID              uuid.UUID
	RejectionReason pgtype.Text
}

func (q *Queries) RejectIdentityVerification(ctx context.Context, arg RejectIdentityVerificationParams) (IdentityVerification, error) {
	row := q.db.QueryRow(ctx, rejectIdentityVerification, arg.ID, arg.RejectionReason)
	var i IdentityVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.IDDocumentType,
		&i.IDDocumentUrl,
		&i.SelfieUrl,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.ConfidenceScore,
		&i.RejectionReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIdentityVerificationStatus = `-- name: UpdateIdentityVerificationStatus :one
UPDATE identity_verifications
SET status = $2, verified_at = $3, verified_by = $4, confidence_score = $5, rejection_reason = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, id_document_type, id_document_url, selfie_url, verified_at, verified_by, confidence_score, rejection_reason, expires_at, created_at, updated_at
`

type UpdateIdentityVerificationStatusParams struct {
	ID              uuid.UUID
	Status          string
	VerifiedAt      pgtype.Timestamptz
	VerifiedBy      pgtype.UUID
	ConfidenceScore pgtype.Numeric
	RejectionReason pgtype.Text
}

func (q *Queries) UpdateIdentityVerificationStatus(ctx context.Context, arg UpdateIdentityVerificationStatusParams) (IdentityVerification, error) {
	row := q.db.QueryRow(ctx, updateIdentityVerificationStatus,
		arg.ID,
		arg.Status,
		arg.VerifiedAt,
		arg.VerifiedBy,
		arg.ConfidenceScore,
		arg.RejectionReason,
	)
	var i IdentityVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.IDDocumentType,
		&i.IDDocumentUrl,
		&i.SelfieUrl,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.ConfidenceScore,
		&i.RejectionReason,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
