// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AirportTransferStatus string

const (
	AirportTransferStatusPending   AirportTransferStatus = "pending"
	AirportTransferStatusAssigned  AirportTransferStatus = "assigned"
	AirportTransferStatusEnRoute   AirportTransferStatus = "en_route"
	AirportTransferStatusArrived   AirportTransferStatus = "arrived"
	AirportTransferStatusCompleted AirportTransferStatus = "completed"
	AirportTransferStatusCancelled AirportTransferStatus = "cancelled"
	AirportTransferStatusNoShow    AirportTransferStatus = "no_show"
)

func (e *AirportTransferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AirportTransferStatus(s)
	case string:
		*e = AirportTransferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AirportTransferStatus: %T", src)
	}
	return nil
}

type NullAirportTransferStatus struct {
	AirportTransferStatus AirportTransferStatus
	Valid                 bool // Valid is true if AirportTransferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAirportTransferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AirportTransferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AirportTransferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAirportTransferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AirportTransferStatus), nil
}

type Airport struct {
	ID            uuid.UUID
	Iata          string
	Name          string
	City          string
	Country       string
	CountryCode   string
	Latitude      float64
	Longitude     float64
	Timezone      string
	TerminalCount int32
	PickupZones   []string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AirportTransfer struct {
	ID               uuid.UUID
	RideID           uuid.UUID
	AirportID        uuid.UUID
	IsPickup         bool
	FlightNumber     pgtype.Text
	Airline          pgtype.Text
	ScheduledArrival pgtype.Timestamptz
	ActualArrival    pgtype.Timestamptz
	PassengerName    pgtype.Text
	PassengerPhone   pgtype.Text
	MeetAndGreet     bool
	WaitingMinutes   int32
	WaitingFeeCents  int32
	FixedFareCents   int32
	Status           AirportTransferStatus
	Notes            pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type AlertEvent struct {
	ID             uuid.UUID
	RuleID         uuid.UUID
	Severity       string
	Title          string
	Message        string
	Data           []byte
	Acknowledged   bool
	AcknowledgedBy pgtype.UUID
	AcknowledgedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type AlertRule struct {
	ID            uuid.UUID
	Name          string
	Description   pgtype.Text
	Condition     string
	Threshold     pgtype.Numeric
	Severity      string
	Action        string
	Recipients    []string
	Active        bool
	CooldownMin   int32
	LastTriggered pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type BusinessAccount struct {
	ID                  uuid.UUID
	OwnerID             uuid.UUID
	Name                string
	Currency            string
	MonthlyLimitCents   pgtype.Numeric
	RequireRideApproval bool
	IsActive            bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type BusinessMember struct {
	AccountID          uuid.UUID
	UserID             uuid.UUID
	Role               string
	SpendingLimitCents pgtype.Numeric
	Status             string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type CashPayment struct {
	RideID      uuid.UUID
	DriverID    uuid.UUID
	AmountDue   pgtype.Numeric
	AmountPaid  pgtype.Numeric
	ChangeCents pgtype.Numeric
	ConfirmedAt pgtype.Timestamptz
}

type Config struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}

type CorporateInvoice struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	RideCount   int32
	TotalCents  int64
	TaxCents    int64
	GrandTotal  int64
	Status      string
	DueDate     pgtype.Timestamptz
	SentAt      pgtype.Timestamptz
	PaidAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CorporateInvoiceItem struct {
	ID           uuid.UUID
	InvoiceID    uuid.UUID
	Description  string
	RideID       pgtype.UUID
	Date         pgtype.Timestamptz
	AmountCents  int64
	CostCenterID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type CostCenter struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Name        string
	Code        string
	BudgetCents int64
	SpentCents  int64
	Active      bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type DemandHeatmap struct {
	ID               uuid.UUID
	ZoneID           uuid.UUID
	ZoneName         string
	ActiveRiders     int32
	AvailableDrivers int32
	BusyDrivers      int32
	Ratio            pgtype.Numeric
	SurgeMultiplier  pgtype.Numeric
	DemandTrend      pgtype.Text
	RecordedAt       pgtype.Timestamptz
}

type DeviceToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	Platform  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type DriverAvailability struct {
	DriverID  uuid.UUID
	IsOnline  bool
	UpdatedAt pgtype.Timestamptz
}

type DriverBadge struct {
	ID          uuid.UUID
	DriverID    uuid.UUID
	BadgeType   string
	DisplayName string
	Description pgtype.Text
	EarnedAt    pgtype.Timestamptz
	ValidUntil  pgtype.Timestamptz
	Active      bool
	CreatedAt   pgtype.Timestamptz
}

type DriverKyc struct {
	DriverID      uuid.UUID
	IDDocument    string
	LicenseNumber string
	VehiclePlate  string
	Status        string
	SubmittedAt   pgtype.Timestamptz
	ReviewedAt    pgtype.Timestamptz
	ReviewNote    pgtype.Text
}

type DriverLocation struct {
	DriverID  uuid.UUID
	Location  pgtype.Point
	Heading   pgtype.Numeric
	UpdatedAt pgtype.Timestamptz
}

type DriverVehicleProfile struct {
	DriverID               uuid.UUID
	LicensePlate           string
	Make                   string
	Model                  string
	Year                   int32
	Color                  string
	LicenseExpiryDate      pgtype.Date
	InsuranceExpiryDate    pgtype.Date
	RegistrationExpiryDate pgtype.Date
	InspectionExpiryDate   pgtype.Date
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type DriverWallet struct {
	DriverID         uuid.UUID
	BalanceCents     int64
	PendingCents     int64
	TotalEarnedCents int64
	TotalPaidCents   int64
	Currency         string
	LastPayoutAt     pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type EmergencyContact struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Phone        string
	Relationship string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type IdentityVerification struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Status          string
	IDDocumentType  pgtype.Text
	IDDocumentUrl   pgtype.Text
	SelfieUrl       pgtype.Text
	VerifiedAt      pgtype.Timestamptz
	VerifiedBy      pgtype.UUID
	ConfidenceScore pgtype.Numeric
	RejectionReason pgtype.Text
	ExpiresAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type LoyaltyPoint struct {
	UserID        uuid.UUID
	Balance       int64
	TotalEarned   int64
	TotalRedeemed int64
	Tier          string
	UpdatedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type LoyaltyTransaction struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Points        int64
	Type          string
	Reason        pgtype.Text
	ReferenceID   pgtype.UUID
	ReferenceType pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Type      string
	Title     string
	Body      string
	Data      []byte
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type NotificationPreference struct {
	UserID         uuid.UUID
	RideUpdates    bool
	PaymentUpdates bool
	KycUpdates     bool
	Marketing      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type PaymentCharge struct {
	ID               uuid.UUID
	RideID           uuid.UUID
	Provider         string
	ProviderChargeID string
	AmountCents      pgtype.Numeric
	Currency         string
	Status           string
	RawResponse      []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	RefundedAt       pgtype.Timestamptz
	IdempotencyKey   pgtype.Text
}

type PaymentEvent struct {
	ID              uuid.UUID
	ChargeID        uuid.UUID
	EventType       string
	Payload         []byte
	Signature       pgtype.Text
	ReceivedAt      pgtype.Timestamptz
	ProviderEventID pgtype.Text
}

type PayoutMethod struct {
	ID            uuid.UUID
	DriverID      uuid.UUID
	Type          string
	AccountName   pgtype.Text
	AccountNumber pgtype.Text
	BankName      pgtype.Text
	IsDefault     bool
	Verified      bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type PayoutRequest struct {
	ID            uuid.UUID
	DriverID      uuid.UUID
	AmountCents   int64
	Method        string
	Status        string
	ReferenceID   pgtype.Text
	RequestedAt   pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
	FailureReason pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type PromoCode struct {
	ID               uuid.UUID
	Code             string
	DiscountType     string
	DiscountCents    int64
	MaxUses          int32
	CurrentUses      int32
	ValidFrom        pgtype.Timestamptz
	ValidUntil       pgtype.Timestamptz
	MinRideCents     int64
	MaxDiscountCents pgtype.Int8
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type PromoCodeUsage struct {
	ID            uuid.UUID
	PromoID       uuid.UUID
	UserID        uuid.UUID
	RideID        pgtype.UUID
	DiscountCents int64
	UsedAt        pgtype.Timestamptz
}

type Ride struct {
	ID                     uuid.UUID
	RiderID                uuid.UUID
	DriverID               pgtype.UUID
	PickupPoint            pgtype.Point
	DestinationPoint       pgtype.Point
	PickupAddress          string
	DestinationAddress     string
	Status                 string
	SuggestedFareCents     pgtype.Numeric
	AcceptedFareCents      pgtype.Numeric
	Currency               string
	PromoCode              pgtype.Text
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	PaymentMethod          string
	TripPinHash            pgtype.Text
	TripPinVerified        bool
	CancellationReason     pgtype.Text
	CancelledBy            pgtype.UUID
	ServiceZoneID          pgtype.UUID
	RequestedPickupAt      pgtype.Timestamptz
	BusinessAccountID      pgtype.UUID
	BusinessMemberID       pgtype.UUID
	IdempotencyKey         pgtype.Text
	IdempotencyPayloadHash pgtype.Text
}

type RideAuthorization struct {
	ID                   uuid.UUID
	RideID               uuid.UUID
	AccountID            uuid.UUID
	MemberID             uuid.UUID
	Status               string
	RequestedAmountCents pgtype.Numeric
	AuthorizedBy         pgtype.UUID
	DecisionNote         pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DecidedAt            pgtype.Timestamptz
}

type RideDispute struct {
	ID             uuid.UUID
	RideID         uuid.UUID
	FiledBy        uuid.UUID
	Category       string
	Description    string
	Status         string
	ResolutionNote pgtype.Text
	ResolvedBy     pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
}

type RideEvent struct {
	ID        uuid.UUID
	RideID    uuid.UUID
	EventType string
	Payload   []byte
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type RideIncidentReport struct {
	ID          uuid.UUID
	RideID      uuid.UUID
	ReportedBy  uuid.UUID
	Category    string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type RideOffer struct {
	ID          uuid.UUID
	RideID      uuid.UUID
	DriverID    uuid.UUID
	Status      string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	RespondedAt pgtype.Timestamptz
}

type RideReview struct {
	ID         uuid.UUID
	RideID     uuid.UUID
	ReviewerID uuid.UUID
	RevieweeID uuid.UUID
	Rating     int16
	Comment    string
	CreatedAt  pgtype.Timestamptz
}

type RideShareToken struct {
	ID        uuid.UUID
	RideID    uuid.UUID
	RiderID   uuid.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type RideSosEvent struct {
	ID          uuid.UUID
	RideID      uuid.UUID
	TriggeredBy uuid.UUID
	Status      string
	Location    pgtype.Point
	Note        pgtype.Text
	CreatedAt   pgtype.Timestamptz
	ResolvedAt  pgtype.Timestamptz
	ResolvedBy  pgtype.UUID
}

type SaftInvoice struct {
	ID            uuid.UUID
	RideID        uuid.UUID
	ChargeID      pgtype.UUID
	InvoiceNumber string
	IssueDate     pgtype.Date
	DueDate       pgtype.Date
	CustomerName  string
	CustomerTaxID pgtype.Text
	Items         []byte
	TotalCents    pgtype.Numeric
	Currency      string
	Status        string
	PdfContent    []byte
	CreatedAt     pgtype.Timestamptz
	IssuedAt      pgtype.Timestamptz
	PaidAt        pgtype.Timestamptz
}

type SavedPlace struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Address   string
	Latitude  float64
	Longitude float64
	Icon      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ServiceZone struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	MinLat      pgtype.Numeric
	MinLng      pgtype.Numeric
	MaxLat      pgtype.Numeric
	MaxLng      pgtype.Numeric
	IsActive    bool
	BaseCents   pgtype.Numeric
	PerKmCents  pgtype.Numeric
	PerMinCents pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	DeviceID         string
	IpAddress        string
	UserAgent        string
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RefreshTokenHash pgtype.Text
	RevokedAt        pgtype.Timestamptz
}

type SupportTicket struct {
	ID             uuid.UUID
	RideID         uuid.UUID
	CreatedBy      uuid.UUID
	Category       string
	Subject        string
	Description    string
	Status         string
	ResolutionNote pgtype.Text
	UpdatedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
}

type SurgeConfig struct {
	ID                uuid.UUID
	Enabled           bool
	MinMultiplier     pgtype.Numeric
	MaxMultiplier     pgtype.Numeric
	ThresholdLow      pgtype.Numeric
	ThresholdHigh     pgtype.Numeric
	ThresholdExtreme  pgtype.Numeric
	UpdateIntervalSec int32
	DecayRate         pgtype.Numeric
	UpdatedAt         pgtype.Timestamptz
}

type SurgeMultiplier struct {
	ID          uuid.UUID
	ZoneID      pgtype.UUID
	Multiplier  pgtype.Numeric
	DemandLevel string
	Reason      pgtype.Text
	ValidUntil  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type TripShare struct {
	ID            uuid.UUID
	RideID        uuid.UUID
	RiderID       uuid.UUID
	TokenHash     []byte
	Active        bool
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
}

type TripShareViewer struct {
	ID          uuid.UUID
	TripShareID uuid.UUID
	ContactID   pgtype.UUID
	UserID      pgtype.UUID
	AddedAt     pgtype.Timestamptz
}

type User struct {
	ID             uuid.UUID
	Phone          string
	Name           string
	Role           string
	PasswordHash   string
	Rating         pgtype.Numeric
	AcceptanceRate pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type VerificationCode struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CodeHash    pgtype.Text
	Purpose     string
	Attempts    int32
	MaxAttempts int32
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	VerifiedAt  pgtype.Timestamptz
}

type WalletTransaction struct {
	ID            uuid.UUID
	DriverID      uuid.UUID
	Type          string
	AmountCents   int64
	BalanceAfter  int64
	ReferenceID   pgtype.UUID
	ReferenceType pgtype.Text
	Description   pgtype.Text
	Status        string
	CreatedAt     pgtype.Timestamptz
}
