// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, data)
VALUES ($1, $2, $3, $4, COALESCE($5::jsonb, '{}'::jsonb))
RETURNING id, user_id, type, title, body, data, read_at, created_at
`

type CreateNotificationParams struct {
	UserID uuid.UUID
	Type   string
	Title  string
	Body   string
	Data   []byte
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE token = $1 AND user_id = $2
`

type DeleteDeviceTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.Token, arg.UserID)
	return err
}

const deleteInvalidDeviceToken = `-- name: DeleteInvalidDeviceToken :exec
DELETE FROM device_tokens WHERE token = $1
`

func (q *Queries) DeleteInvalidDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteInvalidDeviceToken, token)
	return err
}

const deleteNotificationPreferences = `-- name: DeleteNotificationPreferences :exec
DELETE FROM notification_preferences
WHERE user_id = $1
`

func (q *Queries) DeleteNotificationPreferences(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotificationPreferences, userID)
	return err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT user_id, ride_updates, payment_updates, kyc_updates, marketing, created_at, updated_at FROM notification_preferences
WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.RideUpdates,
		&i.PaymentUpdates,
		&i.KycUpdates,
		&i.Marketing,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many
SELECT id, user_id, token, platform, created_at, updated_at FROM device_tokens WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadNotifications = `-- name: ListReadNotifications :many
SELECT id, user_id, type, title, body, data, read_at, created_at FROM notifications
WHERE user_id = $1 AND read_at IS NOT NULL
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListReadNotificationsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListReadNotifications(ctx context.Context, arg ListReadNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listReadNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, type, title, body, data, read_at, created_at FROM notifications
WHERE user_id = $1 AND read_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListUnreadNotificationsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = COALESCE(read_at, NOW())
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, title, body, data, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    updated_at = NOW()
RETURNING id, user_id, token, platform, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID
	Token    string
	Platform string
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.UserID, arg.Token, arg.Platform)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (
    user_id, ride_updates, payment_updates, kyc_updates, marketing
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    ride_updates = EXCLUDED.ride_updates,
    payment_updates = EXCLUDED.payment_updates,
    kyc_updates = EXCLUDED.kyc_updates,
    marketing = EXCLUDED.marketing,
    updated_at = NOW()
RETURNING user_id, ride_updates, payment_updates, kyc_updates, marketing, created_at, updated_at
`

type UpsertNotificationPreferencesParams struct {
	UserID         uuid.UUID
	RideUpdates    bool
	PaymentUpdates bool
	KycUpdates     bool
	Marketing      bool
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.RideUpdates,
		arg.PaymentUpdates,
		arg.KycUpdates,
		arg.Marketing,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.RideUpdates,
		&i.PaymentUpdates,
		&i.KycUpdates,
		&i.Marketing,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
