// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentEvent = `-- name: CreatePaymentEvent :one
INSERT INTO payment_events (charge_id, event_type, payload, signature)
VALUES ($1, $2, $3, $4)
RETURNING id, charge_id, event_type, payload, signature, received_at, provider_event_id
`

type CreatePaymentEventParams struct {
	ChargeID  uuid.UUID
	EventType string
	Payload   []byte
	Signature pgtype.Text
}

func (q *Queries) CreatePaymentEvent(ctx context.Context, arg CreatePaymentEventParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, createPaymentEvent,
		arg.ChargeID,
		arg.EventType,
		arg.Payload,
		arg.Signature,
	)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.ChargeID,
		&i.EventType,
		&i.Payload,
		&i.Signature,
		&i.ReceivedAt,
		&i.ProviderEventID,
	)
	return i, err
}

const getPaymentEventByProviderEventID = `-- name: GetPaymentEventByProviderEventID :one
SELECT id, charge_id, event_type, payload, signature, received_at, provider_event_id FROM payment_events
WHERE charge_id = $1 AND provider_event_id = $2
`

type GetPaymentEventByProviderEventIDParams struct {
	ChargeID        uuid.UUID
	ProviderEventID pgtype.Text
}

func (q *Queries) GetPaymentEventByProviderEventID(ctx context.Context, arg GetPaymentEventByProviderEventIDParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, getPaymentEventByProviderEventID, arg.ChargeID, arg.ProviderEventID)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.ChargeID,
		&i.EventType,
		&i.Payload,
		&i.Signature,
		&i.ReceivedAt,
		&i.ProviderEventID,
	)
	return i, err
}

const getPaymentEvents = `-- name: GetPaymentEvents :many
SELECT id, charge_id, event_type, payload, signature, received_at, provider_event_id FROM payment_events
WHERE charge_id = $1
ORDER BY received_at ASC
`

func (q *Queries) GetPaymentEvents(ctx context.Context, chargeID uuid.UUID) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, getPaymentEvents, chargeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentEvent
	for rows.Next() {
		var i PaymentEvent
		if err := rows.Scan(
			&i.ID,
			&i.ChargeID,
			&i.EventType,
			&i.Payload,
			&i.Signature,
			&i.ReceivedAt,
			&i.ProviderEventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPaymentEvent = `-- name: RecordPaymentEvent :one
INSERT INTO payment_events (
    charge_id, event_type, payload, signature, provider_event_id
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (charge_id, provider_event_id)
    WHERE provider_event_id IS NOT NULL
DO UPDATE SET charge_id = payment_events.charge_id
RETURNING id, charge_id, event_type, payload, signature, received_at, provider_event_id
`

type RecordPaymentEventParams struct {
	ChargeID        uuid.UUID
	EventType       string
	Payload         []byte
	Signature       pgtype.Text
	ProviderEventID pgtype.Text
}

func (q *Queries) RecordPaymentEvent(ctx context.Context, arg RecordPaymentEventParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, recordPaymentEvent,
		arg.ChargeID,
		arg.EventType,
		arg.Payload,
		arg.Signature,
		arg.ProviderEventID,
	)
	var i PaymentEvent
	err := row.Scan(
		&i.ID,
		&i.ChargeID,
		&i.EventType,
		&i.Payload,
		&i.Signature,
		&i.ReceivedAt,
		&i.ProviderEventID,
	)
	return i, err
}
