// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyPaymentEventStatus = `-- name: ApplyPaymentEventStatus :one
UPDATE payment_charges
SET status = $2,
    completed_at = CASE
        WHEN $2 = 'completed' THEN COALESCE(completed_at, NOW())
        ELSE completed_at
    END,
    refunded_at = CASE
        WHEN $2 = 'refunded' THEN COALESCE(refunded_at, NOW())
        ELSE refunded_at
    END,
    updated_at = NOW()
WHERE id = $1
  AND (
      ($2 = 'processing' AND status IN ('pending', 'processing'))
      OR ($2 = 'completed' AND status IN ('pending', 'processing', 'completed'))
      OR ($2 = 'failed' AND status IN ('pending', 'processing', 'failed'))
      OR ($2 = 'refunded' AND status IN ('completed', 'refunded'))
  )
RETURNING id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key
`

type ApplyPaymentEventStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) ApplyPaymentEventStatus(ctx context.Context, arg ApplyPaymentEventStatusParams) (PaymentCharge, error) {
	row := q.db.QueryRow(ctx, applyPaymentEventStatus, arg.ID, arg.Status)
	var i PaymentCharge
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RefundedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const completePaymentCharge = `-- name: CompletePaymentCharge :one
UPDATE payment_charges
SET status = 'completed', completed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key
`

func (q *Queries) CompletePaymentCharge(ctx context.Context, id uuid.UUID) (PaymentCharge, error) {
	row := q.db.QueryRow(ctx, completePaymentCharge, id)
	var i PaymentCharge
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RefundedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const createPaymentCharge = `-- name: CreatePaymentCharge :one
INSERT INTO payment_charges (ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key
`

type CreatePaymentChargeParams struct {
	RideID           uuid.UUID
	Provider         string
	ProviderChargeID string
	AmountCents      pgtype.Numeric
	Currency         string
	Status           string
	RawResponse      []byte
}

func (q *Queries) CreatePaymentCharge(ctx context.Context, arg CreatePaymentChargeParams) (PaymentCharge, error) {
	row := q.db.QueryRow(ctx, createPaymentCharge,
		arg.RideID,
		arg.Provider,
		arg.ProviderChargeID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.RawResponse,
	)
	var i PaymentCharge
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RefundedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const createPaymentIntent = `-- name: CreatePaymentIntent :one
INSERT INTO payment_charges (
    ride_id, provider, provider_charge_id, idempotency_key,
    amount_cents, currency, status, raw_response
)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', '{}'::jsonb)
ON CONFLICT (ride_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL
DO UPDATE SET updated_at = payment_charges.updated_at
RETURNING id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key
`

type CreatePaymentIntentParams struct {
	RideID           uuid.UUID
	Provider         string
	ProviderChargeID string
	IdempotencyKey   pgtype.Text
	AmountCents      pgtype.Numeric
	Currency         string
}

func (q *Queries) CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentCharge, error) {
	row := q.db.QueryRow(ctx, createPaymentIntent,
		arg.RideID,
		arg.Provider,
		arg.ProviderChargeID,
		arg.IdempotencyKey,
		arg.AmountCents,
		arg.Currency,
	)
	var i PaymentCharge
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RefundedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const failPaymentCharge = `-- name: FailPaymentCharge :one
UPDATE payment_charges
SET status = 'failed', updated_at = NOW()
WHERE id = $1
RETURNING id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key
`

func (q *Queries) FailPaymentCharge(ctx context.Context, id uuid.UUID) (PaymentCharge, error) {
	row := q.db.QueryRow(ctx, failPaymentCharge, id)
	var i PaymentCharge
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RefundedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentChargeByID = `-- name: GetPaymentChargeByID :one
SELECT id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key FROM payment_charges
WHERE id = $1
`

func (q *Queries) GetPaymentChargeByID(ctx context.Context, id uuid.UUID) (PaymentCharge, error) {
	row := q.db.QueryRow(ctx, getPaymentChargeByID, id)
	var i PaymentCharge
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RefundedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentChargeByIdempotencyKey = `-- name: GetPaymentChargeByIdempotencyKey :one
SELECT id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key FROM payment_charges
WHERE ride_id = $1 AND idempotency_key = $2
`

type GetPaymentChargeByIdempotencyKeyParams struct {
	RideID         uuid.UUID
	IdempotencyKey pgtype.Text
}

func (q *Queries) GetPaymentChargeByIdempotencyKey(ctx context.Context, arg GetPaymentChargeByIdempotencyKeyParams) (PaymentCharge, error) {
	row := q.db.QueryRow(ctx, getPaymentChargeByIdempotencyKey, arg.RideID, arg.IdempotencyKey)
	var i PaymentCharge
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RefundedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentChargeByProviderChargeID = `-- name: GetPaymentChargeByProviderChargeID :one
SELECT id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key FROM payment_charges
WHERE provider = $1 AND provider_charge_id = $2
`

type GetPaymentChargeByProviderChargeIDParams struct {
	Provider         string
	ProviderChargeID string
}

func (q *Queries) GetPaymentChargeByProviderChargeID(ctx context.Context, arg GetPaymentChargeByProviderChargeIDParams) (PaymentCharge, error) {
	row := q.db.QueryRow(ctx, getPaymentChargeByProviderChargeID, arg.Provider, arg.ProviderChargeID)
	var i PaymentCharge
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RefundedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentChargesByRide = `-- name: GetPaymentChargesByRide :many
SELECT id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key FROM payment_charges
WHERE ride_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetPaymentChargesByRide(ctx context.Context, rideID uuid.UUID) ([]PaymentCharge, error) {
	rows, err := q.db.Query(ctx, getPaymentChargesByRide, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentCharge
	for rows.Next() {
		var i PaymentCharge
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.Provider,
			&i.ProviderChargeID,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.RawResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RefundedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingCharges = `-- name: GetPendingCharges :many
SELECT id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key FROM payment_charges
WHERE status IN ('pending', 'processing')
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingCharges(ctx context.Context, limit int32) ([]PaymentCharge, error) {
	rows, err := q.db.Query(ctx, getPendingCharges, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentCharge
	for rows.Next() {
		var i PaymentCharge
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.Provider,
			&i.ProviderChargeID,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.RawResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RefundedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentCharges = `-- name: ListPaymentCharges :many
SELECT id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key FROM payment_charges
WHERE ($1::text = '' OR status = $1::text)
  AND ($2::text = '' OR provider = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListPaymentChargesParams struct {
	Column1 string
	Column2 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListPaymentCharges(ctx context.Context, arg ListPaymentChargesParams) ([]PaymentCharge, error) {
	rows, err := q.db.Query(ctx, listPaymentCharges,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentCharge
	for rows.Next() {
		var i PaymentCharge
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.Provider,
			&i.ProviderChargeID,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.RawResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RefundedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundPaymentCharge = `-- name: RefundPaymentCharge :one
UPDATE payment_charges
SET status = 'refunded', refunded_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key
`

func (q *Queries) RefundPaymentCharge(ctx context.Context, id uuid.UUID) (PaymentCharge, error) {
	row := q.db.QueryRow(ctx, refundPaymentCharge, id)
	var i PaymentCharge
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RefundedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const updatePaymentChargeStatus = `-- name: UpdatePaymentChargeStatus :one
UPDATE payment_charges
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, ride_id, provider, provider_charge_id, amount_cents, currency, status, raw_response, created_at, updated_at, completed_at, refunded_at, idempotency_key
`

type UpdatePaymentChargeStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdatePaymentChargeStatus(ctx context.Context, arg UpdatePaymentChargeStatusParams) (PaymentCharge, error) {
	row := q.db.QueryRow(ctx, updatePaymentChargeStatus, arg.ID, arg.Status)
	var i PaymentCharge
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.Provider,
		&i.ProviderChargeID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.RawResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RefundedAt,
		&i.IdempotencyKey,
	)
	return i, err
}
