// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const paymentAnalyticsSummary = `-- name: PaymentAnalyticsSummary :one

SELECT
    COUNT(*)                                                              AS total_charges,
    COUNT(*) FILTER (WHERE status = 'completed')                          AS completed_charges,
    COUNT(*) FILTER (WHERE status = 'failed')                             AS failed_charges,
    COUNT(*) FILTER (WHERE status = 'refunded')                           AS refunded_charges,
    COUNT(*) FILTER (WHERE status IN ('pending', 'processing'))           AS in_flight_charges,
    COALESCE(SUM(amount_cents) FILTER (WHERE status = 'completed'), 0)::bigint AS completed_volume_cents,
    COALESCE(SUM(amount_cents) FILTER (WHERE status = 'refunded'), 0)::bigint  AS refunded_volume_cents
FROM payment_charges
WHERE created_at >= $1
`

type PaymentAnalyticsSummaryRow struct {
	TotalCharges         int64
	CompletedCharges     int64
	FailedCharges        int64
	RefundedCharges      int64
	InFlightCharges      int64
	CompletedVolumeCents int64
	RefundedVolumeCents  int64
}

// Payment analytics for the admin dashboard. All queries are windowed on a
// single "since" timestamp so the HTTP layer can clamp the window (days).
// Counts and volumes for one status window. FILTER keeps each metric in one
// pass; ::bigint casts keep the JSON layer on plain int64s.
func (q *Queries) PaymentAnalyticsSummary(ctx context.Context, createdAt pgtype.Timestamptz) (PaymentAnalyticsSummaryRow, error) {
	row := q.db.QueryRow(ctx, paymentAnalyticsSummary, createdAt)
	var i PaymentAnalyticsSummaryRow
	err := row.Scan(
		&i.TotalCharges,
		&i.CompletedCharges,
		&i.FailedCharges,
		&i.RefundedCharges,
		&i.InFlightCharges,
		&i.CompletedVolumeCents,
		&i.RefundedVolumeCents,
	)
	return i, err
}

const paymentDailyVolume = `-- name: PaymentDailyVolume :many
SELECT
    date_trunc('day', created_at)::date                                        AS day,
    COUNT(*)                                                                   AS charges,
    COUNT(*) FILTER (WHERE status = 'completed')                               AS completed_charges,
    COALESCE(SUM(amount_cents) FILTER (WHERE status = 'completed'), 0)::bigint AS completed_volume_cents,
    COALESCE(SUM(amount_cents) FILTER (WHERE status = 'refunded'), 0)::bigint  AS refunded_volume_cents
FROM payment_charges
WHERE created_at >= $1
GROUP BY day
ORDER BY day
`

type PaymentDailyVolumeRow struct {
	Day                  pgtype.Date
	Charges              int64
	CompletedCharges     int64
	CompletedVolumeCents int64
	RefundedVolumeCents  int64
}

// Per-day completed volume and refunds for trend charts.
func (q *Queries) PaymentDailyVolume(ctx context.Context, createdAt pgtype.Timestamptz) ([]PaymentDailyVolumeRow, error) {
	rows, err := q.db.Query(ctx, paymentDailyVolume, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentDailyVolumeRow
	for rows.Next() {
		var i PaymentDailyVolumeRow
		if err := rows.Scan(
			&i.Day,
			&i.Charges,
			&i.CompletedCharges,
			&i.CompletedVolumeCents,
			&i.RefundedVolumeCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentProviderBreakdown = `-- name: PaymentProviderBreakdown :many
SELECT
    provider                                                                   AS provider,
    COUNT(*)                                                                   AS charges,
    COUNT(*) FILTER (WHERE status = 'completed')                               AS completed_charges,
    COUNT(*) FILTER (WHERE status = 'failed')                                  AS failed_charges,
    COALESCE(SUM(amount_cents) FILTER (WHERE status = 'completed'), 0)::bigint AS completed_volume_cents
FROM payment_charges
WHERE created_at >= $1
GROUP BY provider
ORDER BY charges DESC
`

type PaymentProviderBreakdownRow struct {
	Provider             string
	Charges              int64
	CompletedCharges     int64
	FailedCharges        int64
	CompletedVolumeCents int64
}

// Per-provider totals so a misbehaving provider is visible in one glance.
func (q *Queries) PaymentProviderBreakdown(ctx context.Context, createdAt pgtype.Timestamptz) ([]PaymentProviderBreakdownRow, error) {
	rows, err := q.db.Query(ctx, paymentProviderBreakdown, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentProviderBreakdownRow
	for rows.Next() {
		var i PaymentProviderBreakdownRow
		if err := rows.Scan(
			&i.Provider,
			&i.Charges,
			&i.CompletedCharges,
			&i.FailedCharges,
			&i.CompletedVolumeCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
