// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_fraud.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRiderChargeSignals = `-- name: GetRiderChargeSignals :one
SELECT
    COUNT(*) FILTER (WHERE pc.created_at >= $3)                          AS recent_charges,
    COUNT(*) FILTER (WHERE pc.created_at >= $4 AND pc.amount_cents = $5) AS duplicate_amounts
FROM payment_charges pc
JOIN rides r ON r.id = pc.ride_id
WHERE r.rider_id = $1 AND pc.created_at >= $2
`

type GetRiderChargeSignalsParams struct {
	RiderID     uuid.UUID
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
	CreatedAt_3 pgtype.Timestamptz
	AmountCents pgtype.Numeric
}

type GetRiderChargeSignalsRow struct {
	RecentCharges    int64
	DuplicateAmounts int64
}

// Fraud signal probe for charge creation: one pass over the rider's recent
// charges. $2 is the outer scan bound (the earlier of the two evaluation
// windows); $3/$4 are the velocity and duplicate sub-windows evaluated with
// FILTER inside the scan, so both signals cost a single scan.
func (q *Queries) GetRiderChargeSignals(ctx context.Context, arg GetRiderChargeSignalsParams) (GetRiderChargeSignalsRow, error) {
	row := q.db.QueryRow(ctx, getRiderChargeSignals,
		arg.RiderID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.CreatedAt_3,
		arg.AmountCents,
	)
	var i GetRiderChargeSignalsRow
	err := row.Scan(&i.RecentCharges, &i.DuplicateAmounts)
	return i, err
}
