// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payout_requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completePayoutRequest = `-- name: CompletePayoutRequest :one
UPDATE payout_requests
SET status = 'completed', processed_at = NOW()
WHERE id = $1 AND status = 'processing'
RETURNING id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at
`

func (q *Queries) CompletePayoutRequest(ctx context.Context, id uuid.UUID) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, completePayoutRequest, id)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.ReferenceID,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.FailureReason,
		&i.CreatedAt,
	)
	return i, err
}

const createPayoutRequest = `-- name: CreatePayoutRequest :one

INSERT INTO payout_requests (driver_id, amount_cents, method, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at
`

type CreatePayoutRequestParams struct {
	DriverID    uuid.UUID
	AmountCents int64
	Method      string
}

// Payout request lifecycle queries used by the payouts package. Status
// transitions are guarded in SQL so concurrent admin actions cannot double
// process a withdrawal.
func (q *Queries) CreatePayoutRequest(ctx context.Context, arg CreatePayoutRequestParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, createPayoutRequest, arg.DriverID, arg.AmountCents, arg.Method)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.ReferenceID,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.FailureReason,
		&i.CreatedAt,
	)
	return i, err
}

const failPayoutRequest = `-- name: FailPayoutRequest :one
UPDATE payout_requests
SET status = 'failed', processed_at = NOW(), failure_reason = $2
WHERE id = $1 AND status IN ('pending', 'processing')
RETURNING id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at
`

type FailPayoutRequestParams struct {
	ID            uuid.UUID
	FailureReason pgtype.Text
}

func (q *Queries) FailPayoutRequest(ctx context.Context, arg FailPayoutRequestParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, failPayoutRequest, arg.ID, arg.FailureReason)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.ReferenceID,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.FailureReason,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePayoutRequestsByDriver = `-- name: GetActivePayoutRequestsByDriver :many
SELECT id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at FROM payout_requests
WHERE driver_id = $1 AND status IN ('pending', 'processing')
ORDER BY requested_at DESC
`

func (q *Queries) GetActivePayoutRequestsByDriver(ctx context.Context, driverID uuid.UUID) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, getActivePayoutRequestsByDriver, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.AmountCents,
			&i.Method,
			&i.Status,
			&i.ReferenceID,
			&i.RequestedAt,
			&i.ProcessedAt,
			&i.FailureReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayoutRequestByID = `-- name: GetPayoutRequestByID :one
SELECT id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at FROM payout_requests
WHERE id = $1
`

func (q *Queries) GetPayoutRequestByID(ctx context.Context, id uuid.UUID) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, getPayoutRequestByID, id)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.ReferenceID,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.FailureReason,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletTransactionByReference = `-- name: GetWalletTransactionByReference :one
SELECT id, driver_id, type, amount_cents, balance_after, reference_id, reference_type, description, status, created_at FROM wallet_transactions
WHERE reference_id = $1 AND reference_type = 'payout'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetWalletTransactionByReference(ctx context.Context, referenceID pgtype.UUID) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, getWalletTransactionByReference, referenceID)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.Type,
		&i.AmountCents,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPayoutRequestsByDriver = `-- name: ListPayoutRequestsByDriver :many
SELECT id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at FROM payout_requests
WHERE driver_id = $1
ORDER BY requested_at DESC
LIMIT $2 OFFSET $3
`

type ListPayoutRequestsByDriverParams struct {
	DriverID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListPayoutRequestsByDriver(ctx context.Context, arg ListPayoutRequestsByDriverParams) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, listPayoutRequestsByDriver, arg.DriverID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.AmountCents,
			&i.Method,
			&i.Status,
			&i.ReferenceID,
			&i.RequestedAt,
			&i.ProcessedAt,
			&i.FailureReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutRequestsByStatus = `-- name: ListPayoutRequestsByStatus :many
SELECT id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at FROM payout_requests
WHERE ($1::text = '' OR status = $1::text)
ORDER BY requested_at ASC
LIMIT $2 OFFSET $3
`

type ListPayoutRequestsByStatusParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListPayoutRequestsByStatus(ctx context.Context, arg ListPayoutRequestsByStatusParams) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, listPayoutRequestsByStatus, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.AmountCents,
			&i.Method,
			&i.Status,
			&i.ReferenceID,
			&i.RequestedAt,
			&i.ProcessedAt,
			&i.FailureReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutRequestsInFlight = `-- name: ListPayoutRequestsInFlight :many
SELECT id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at FROM payout_requests
WHERE status = 'processing' AND reference_id IS NOT NULL
ORDER BY requested_at ASC
LIMIT $1
`

func (q *Queries) ListPayoutRequestsInFlight(ctx context.Context, limit int32) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, listPayoutRequestsInFlight, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.AmountCents,
			&i.Method,
			&i.Status,
			&i.ReferenceID,
			&i.RequestedAt,
			&i.ProcessedAt,
			&i.FailureReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutRequestsNeedingSubmission = `-- name: ListPayoutRequestsNeedingSubmission :many
SELECT id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at FROM payout_requests
WHERE status = 'processing' AND reference_id IS NULL
ORDER BY requested_at ASC
LIMIT $1
`

func (q *Queries) ListPayoutRequestsNeedingSubmission(ctx context.Context, limit int32) ([]PayoutRequest, error) {
	rows, err := q.db.Query(ctx, listPayoutRequestsNeedingSubmission, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayoutRequest
	for rows.Next() {
		var i PayoutRequest
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.AmountCents,
			&i.Method,
			&i.Status,
			&i.ReferenceID,
			&i.RequestedAt,
			&i.ProcessedAt,
			&i.FailureReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPayoutRequestProcessing = `-- name: MarkPayoutRequestProcessing :one
UPDATE payout_requests
SET status = 'processing'
WHERE id = $1 AND status = 'pending'
RETURNING id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at
`

func (q *Queries) MarkPayoutRequestProcessing(ctx context.Context, id uuid.UUID) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, markPayoutRequestProcessing, id)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.ReferenceID,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.FailureReason,
		&i.CreatedAt,
	)
	return i, err
}

const setPayoutRequestReference = `-- name: SetPayoutRequestReference :one
UPDATE payout_requests
SET reference_id = $2
WHERE id = $1 AND status = 'processing' AND reference_id IS NULL
RETURNING id, driver_id, amount_cents, method, status, reference_id, requested_at, processed_at, failure_reason, created_at
`

type SetPayoutRequestReferenceParams struct {
	ID          uuid.UUID
	ReferenceID pgtype.Text
}

func (q *Queries) SetPayoutRequestReference(ctx context.Context, arg SetPayoutRequestReferenceParams) (PayoutRequest, error) {
	row := q.db.QueryRow(ctx, setPayoutRequestReference, arg.ID, arg.ReferenceID)
	var i PayoutRequest
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.AmountCents,
		&i.Method,
		&i.Status,
		&i.ReferenceID,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.FailureReason,
		&i.CreatedAt,
	)
	return i, err
}

const setWalletTransactionStatus = `-- name: SetWalletTransactionStatus :exec
UPDATE wallet_transactions
SET status = $2
WHERE reference_id = $1 AND reference_type = 'payout' AND status = $3
`

type SetWalletTransactionStatusParams struct {
	ReferenceID pgtype.UUID
	Status      string
	Status_2    string
}

func (q *Queries) SetWalletTransactionStatus(ctx context.Context, arg SetWalletTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, setWalletTransactionStatus, arg.ReferenceID, arg.Status, arg.Status_2)
	return err
}
