// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promo_codes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addLoyaltyPoints = `-- name: AddLoyaltyPoints :one
UPDATE loyalty_points
SET balance = balance + $2,
    total_earned = total_earned + CASE WHEN $2 > 0 THEN $2 ELSE 0 END,
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, balance, total_earned, total_redeemed, tier, updated_at, created_at
`

type AddLoyaltyPointsParams struct {
	UserID  uuid.UUID
	Balance int64
}

func (q *Queries) AddLoyaltyPoints(ctx context.Context, arg AddLoyaltyPointsParams) (LoyaltyPoint, error) {
	row := q.db.QueryRow(ctx, addLoyaltyPoints, arg.UserID, arg.Balance)
	var i LoyaltyPoint
	err := row.Scan(
		&i.UserID,
		&i.Balance,
		&i.TotalEarned,
		&i.TotalRedeemed,
		&i.Tier,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const checkUserPromoUsage = `-- name: CheckUserPromoUsage :one
SELECT EXISTS(
    SELECT 1 FROM promo_code_usages
    WHERE promo_id = $1 AND user_id = $2
) as used
`

type CheckUserPromoUsageParams struct {
	PromoID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) CheckUserPromoUsage(ctx context.Context, arg CheckUserPromoUsageParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserPromoUsage, arg.PromoID, arg.UserID)
	var used bool
	err := row.Scan(&used)
	return used, err
}

const createLoyaltyPoints = `-- name: CreateLoyaltyPoints :exec
INSERT INTO loyalty_points (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) CreateLoyaltyPoints(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createLoyaltyPoints, userID)
	return err
}

const createLoyaltyTransaction = `-- name: CreateLoyaltyTransaction :exec
INSERT INTO loyalty_transactions (user_id, points, type, reason, reference_id, reference_type)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateLoyaltyTransactionParams struct {
	UserID        uuid.UUID
	Points        int64
	Type          string
	Reason        pgtype.Text
	ReferenceID   pgtype.UUID
	ReferenceType pgtype.Text
}

func (q *Queries) CreateLoyaltyTransaction(ctx context.Context, arg CreateLoyaltyTransactionParams) error {
	_, err := q.db.Exec(ctx, createLoyaltyTransaction,
		arg.UserID,
		arg.Points,
		arg.Type,
		arg.Reason,
		arg.ReferenceID,
		arg.ReferenceType,
	)
	return err
}

const createPromoCode = `-- name: CreatePromoCode :one
INSERT INTO promo_codes (code, discount_type, discount_cents, max_uses, valid_from, valid_until, min_ride_cents, max_discount_cents, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, discount_type, discount_cents, max_uses, current_uses, valid_from, valid_until, min_ride_cents, max_discount_cents, is_active, created_at, updated_at
`

type CreatePromoCodeParams struct {
	Code             string
	DiscountType     string
	DiscountCents    int64
	MaxUses          int32
	ValidFrom        pgtype.Timestamptz
	ValidUntil       pgtype.Timestamptz
	MinRideCents     int64
	MaxDiscountCents pgtype.Int8
	IsActive         bool
}

func (q *Queries) CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, createPromoCode,
		arg.Code,
		arg.DiscountType,
		arg.DiscountCents,
		arg.MaxUses,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.MinRideCents,
		arg.MaxDiscountCents,
		arg.IsActive,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountCents,
		&i.MaxUses,
		&i.CurrentUses,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.MinRideCents,
		&i.MaxDiscountCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivatePromoCode = `-- name: DeactivatePromoCode :exec
UPDATE promo_codes
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivatePromoCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivatePromoCode, id)
	return err
}

const deductLoyaltyPoints = `-- name: DeductLoyaltyPoints :one
UPDATE loyalty_points
SET balance = balance - $2,
    total_redeemed = total_redeemed + CASE WHEN $2 > 0 THEN $2 ELSE 0 END,
    updated_at = NOW()
WHERE user_id = $1 AND balance >= $2
RETURNING user_id, balance, total_earned, total_redeemed, tier, updated_at, created_at
`

type DeductLoyaltyPointsParams struct {
	UserID  uuid.UUID
	Balance int64
}

func (q *Queries) DeductLoyaltyPoints(ctx context.Context, arg DeductLoyaltyPointsParams) (LoyaltyPoint, error) {
	row := q.db.QueryRow(ctx, deductLoyaltyPoints, arg.UserID, arg.Balance)
	var i LoyaltyPoint
	err := row.Scan(
		&i.UserID,
		&i.Balance,
		&i.TotalEarned,
		&i.TotalRedeemed,
		&i.Tier,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLoyaltyBalance = `-- name: GetLoyaltyBalance :one
SELECT user_id, balance, total_earned, total_redeemed, tier, updated_at, created_at FROM loyalty_points
WHERE user_id = $1
`

func (q *Queries) GetLoyaltyBalance(ctx context.Context, userID uuid.UUID) (LoyaltyPoint, error) {
	row := q.db.QueryRow(ctx, getLoyaltyBalance, userID)
	var i LoyaltyPoint
	err := row.Scan(
		&i.UserID,
		&i.Balance,
		&i.TotalEarned,
		&i.TotalRedeemed,
		&i.Tier,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPromoCodeByCode = `-- name: GetPromoCodeByCode :one
SELECT id, code, discount_type, discount_cents, max_uses, current_uses, valid_from, valid_until, min_ride_cents, max_discount_cents, is_active, created_at, updated_at FROM promo_codes
WHERE code = $1
`

func (q *Queries) GetPromoCodeByCode(ctx context.Context, code string) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByCode, code)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountCents,
		&i.MaxUses,
		&i.CurrentUses,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.MinRideCents,
		&i.MaxDiscountCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromoCodeByID = `-- name: GetPromoCodeByID :one
SELECT id, code, discount_type, discount_cents, max_uses, current_uses, valid_from, valid_until, min_ride_cents, max_discount_cents, is_active, created_at, updated_at FROM promo_codes
WHERE id = $1
`

func (q *Queries) GetPromoCodeByID(ctx context.Context, id uuid.UUID) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByID, id)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountCents,
		&i.MaxUses,
		&i.CurrentUses,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.MinRideCents,
		&i.MaxDiscountCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPromoUsages = `-- name: GetUserPromoUsages :many
SELECT id, promo_id, user_id, ride_id, discount_cents, used_at FROM promo_code_usages
WHERE user_id = $1
ORDER BY used_at DESC
`

func (q *Queries) GetUserPromoUsages(ctx context.Context, userID uuid.UUID) ([]PromoCodeUsage, error) {
	rows, err := q.db.Query(ctx, getUserPromoUsages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoCodeUsage
	for rows.Next() {
		var i PromoCodeUsage
		if err := rows.Scan(
			&i.ID,
			&i.PromoID,
			&i.UserID,
			&i.RideID,
			&i.DiscountCents,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPromoUsage = `-- name: IncrementPromoUsage :one
UPDATE promo_codes
SET current_uses = current_uses + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, discount_type, discount_cents, max_uses, current_uses, valid_from, valid_until, min_ride_cents, max_discount_cents, is_active, created_at, updated_at
`

func (q *Queries) IncrementPromoUsage(ctx context.Context, id uuid.UUID) (PromoCode, error) {
	row := q.db.QueryRow(ctx, incrementPromoUsage, id)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountCents,
		&i.MaxUses,
		&i.CurrentUses,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.MinRideCents,
		&i.MaxDiscountCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePromoCodes = `-- name: ListActivePromoCodes :many
SELECT id, code, discount_type, discount_cents, max_uses, current_uses, valid_from, valid_until, min_ride_cents, max_discount_cents, is_active, created_at, updated_at FROM promo_codes
WHERE is_active = TRUE AND valid_from <= NOW() AND valid_until >= NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActivePromoCodes(ctx context.Context) ([]PromoCode, error) {
	rows, err := q.db.Query(ctx, listActivePromoCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoCode
	for rows.Next() {
		var i PromoCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DiscountType,
			&i.DiscountCents,
			&i.MaxUses,
			&i.CurrentUses,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.MinRideCents,
			&i.MaxDiscountCents,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoyaltyTransactions = `-- name: ListLoyaltyTransactions :many
SELECT id, user_id, points, type, reason, reference_id, reference_type, created_at FROM loyalty_transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLoyaltyTransactionsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListLoyaltyTransactions(ctx context.Context, arg ListLoyaltyTransactionsParams) ([]LoyaltyTransaction, error) {
	rows, err := q.db.Query(ctx, listLoyaltyTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoyaltyTransaction
	for rows.Next() {
		var i LoyaltyTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Points,
			&i.Type,
			&i.Reason,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPromoUsage = `-- name: RecordPromoUsage :exec
INSERT INTO promo_code_usages (promo_id, user_id, ride_id, discount_cents)
VALUES ($1, $2, $3, $4)
`

type RecordPromoUsageParams struct {
	PromoID       uuid.UUID
	UserID        uuid.UUID
	RideID        pgtype.UUID
	DiscountCents int64
}

func (q *Queries) RecordPromoUsage(ctx context.Context, arg RecordPromoUsageParams) error {
	_, err := q.db.Exec(ctx, recordPromoUsage,
		arg.PromoID,
		arg.UserID,
		arg.RideID,
		arg.DiscountCents,
	)
	return err
}

const updateLoyaltyTier = `-- name: UpdateLoyaltyTier :exec
UPDATE loyalty_points
SET tier = $2,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateLoyaltyTierParams struct {
	UserID uuid.UUID
	Tier   string
}

func (q *Queries) UpdateLoyaltyTier(ctx context.Context, arg UpdateLoyaltyTierParams) error {
	_, err := q.db.Exec(ctx, updateLoyaltyTier, arg.UserID, arg.Tier)
	return err
}
