// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptRideOffer(ctx context.Context, arg AcceptRideOfferParams) (Ride, error)
	AcknowledgeAlertEvent(ctx context.Context, arg AcknowledgeAlertEventParams) (AlertEvent, error)
	AddDriverBalance(ctx context.Context, arg AddDriverBalanceParams) (DriverWallet, error)
	AddDriverEarning(ctx context.Context, arg AddDriverEarningParams) (DriverWallet, error)
	AddInvoiceItem(ctx context.Context, arg AddInvoiceItemParams) (CorporateInvoiceItem, error)
	AddLoyaltyPoints(ctx context.Context, arg AddLoyaltyPointsParams) (LoyaltyPoint, error)
	AddTripShareViewer(ctx context.Context, arg AddTripShareViewerParams) error
	ApplyPaymentEventStatus(ctx context.Context, arg ApplyPaymentEventStatusParams) (PaymentCharge, error)
	ApproveIdentityVerification(ctx context.Context, arg ApproveIdentityVerificationParams) (IdentityVerification, error)
	ApproveRideAuthorization(ctx context.Context, arg ApproveRideAuthorizationParams) (RideAuthorization, error)
	CancelAirportTransfer(ctx context.Context, arg CancelAirportTransferParams) (AirportTransfer, error)
	CancelRide(ctx context.Context, arg CancelRideParams) (Ride, error)
	CancelRideByRider(ctx context.Context, arg CancelRideByRiderParams) (Ride, error)
	CheckUserPromoUsage(ctx context.Context, arg CheckUserPromoUsageParams) (bool, error)
	ClearPendingEarnings(ctx context.Context, arg ClearPendingEarningsParams) (DriverWallet, error)
	CompletePaymentCharge(ctx context.Context, id uuid.UUID) (PaymentCharge, error)
	CompletePayoutRequest(ctx context.Context, id uuid.UUID) (PayoutRequest, error)
	CompleteRide(ctx context.Context, id uuid.UUID) (Ride, error)
	ConsumeVerifiedVerificationCode(ctx context.Context, id uuid.UUID) error
	CountActiveServiceZones(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context) ([]CountUsersByRoleRow, error)
	CreateAirportTransfer(ctx context.Context, arg CreateAirportTransferParams) (AirportTransfer, error)
	CreateAlertEvent(ctx context.Context, arg CreateAlertEventParams) (AlertEvent, error)
	CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error)
	CreateBusinessAccount(ctx context.Context, arg CreateBusinessAccountParams) (BusinessAccount, error)
	CreateBusinessMember(ctx context.Context, arg CreateBusinessMemberParams) (BusinessMember, error)
	CreateCorporateInvoice(ctx context.Context, arg CreateCorporateInvoiceParams) (CorporateInvoice, error)
	CreateCostCenter(ctx context.Context, arg CreateCostCenterParams) (CostCenter, error)
	CreateDemandHeatmap(ctx context.Context, arg CreateDemandHeatmapParams) (DemandHeatmap, error)
	CreateDriverBadge(ctx context.Context, arg CreateDriverBadgeParams) (DriverBadge, error)
	CreateDriverVehicleProfile(ctx context.Context, arg CreateDriverVehicleProfileParams) (DriverVehicleProfile, error)
	CreateDriverWallet(ctx context.Context, driverID uuid.UUID) error
	CreateEmergencyContact(ctx context.Context, arg CreateEmergencyContactParams) (EmergencyContact, error)
	CreateIdentityVerification(ctx context.Context, arg CreateIdentityVerificationParams) (IdentityVerification, error)
	CreateLoyaltyPoints(ctx context.Context, userID uuid.UUID) error
	CreateLoyaltyTransaction(ctx context.Context, arg CreateLoyaltyTransactionParams) error
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePaymentCharge(ctx context.Context, arg CreatePaymentChargeParams) (PaymentCharge, error)
	CreatePaymentEvent(ctx context.Context, arg CreatePaymentEventParams) (PaymentEvent, error)
	CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentCharge, error)
	// Payout request lifecycle queries used by the payouts package. Status
	// transitions are guarded in SQL so concurrent admin actions cannot double
	// process a withdrawal.
	CreatePayoutRequest(ctx context.Context, arg CreatePayoutRequestParams) (PayoutRequest, error)
	CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error)
	CreateRide(ctx context.Context, arg CreateRideParams) (Ride, error)
	CreateRideAuthorization(ctx context.Context, arg CreateRideAuthorizationParams) (RideAuthorization, error)
	CreateRideDispute(ctx context.Context, arg CreateRideDisputeParams) (RideDispute, error)
	CreateRideEvent(ctx context.Context, arg CreateRideEventParams) (RideEvent, error)
	CreateRideIdempotent(ctx context.Context, arg CreateRideIdempotentParams) (Ride, error)
	CreateRideIncidentReport(ctx context.Context, arg CreateRideIncidentReportParams) (RideIncidentReport, error)
	CreateRideReview(ctx context.Context, arg CreateRideReviewParams) (RideReview, error)
	CreateRideSOSEvent(ctx context.Context, arg CreateRideSOSEventParams) (RideSosEvent, error)
	CreateRideShareToken(ctx context.Context, arg CreateRideShareTokenParams) (CreateRideShareTokenRow, error)
	CreateSAFTInvoice(ctx context.Context, arg CreateSAFTInvoiceParams) (SaftInvoice, error)
	CreateSavedPlace(ctx context.Context, arg CreateSavedPlaceParams) (SavedPlace, error)
	CreateServiceZone(ctx context.Context, arg CreateServiceZoneParams) (ServiceZone, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSupportTicket(ctx context.Context, arg CreateSupportTicketParams) (SupportTicket, error)
	CreateSurgeMultiplier(ctx context.Context, arg CreateSurgeMultiplierParams) (SurgeMultiplier, error)
	CreateTripShare(ctx context.Context, arg CreateTripShareParams) (TripShare, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error)
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) error
	DeactivateDriverBadge(ctx context.Context, id uuid.UUID) error
	DeactivateExpiredSurge(ctx context.Context) error
	DeactivateExpiredTripShares(ctx context.Context) error
	DeactivatePromoCode(ctx context.Context, id uuid.UUID) error
	DeactivateTripShare(ctx context.Context, rideID uuid.UUID) error
	DeactivateUser(ctx context.Context, id uuid.UUID) (User, error)
	DeclineRideOffer(ctx context.Context, arg DeclineRideOfferParams) error
	DeductDriverBalance(ctx context.Context, arg DeductDriverBalanceParams) (DriverWallet, error)
	DeductLoyaltyPoints(ctx context.Context, arg DeductLoyaltyPointsParams) (LoyaltyPoint, error)
	DeleteAlertRule(ctx context.Context, id uuid.UUID) error
	DeleteCostCenter(ctx context.Context, arg DeleteCostCenterParams) error
	DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error
	DeleteEmergencyContact(ctx context.Context, arg DeleteEmergencyContactParams) (EmergencyContact, error)
	DeleteExpiredCodes(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteInvalidDeviceToken(ctx context.Context, token string) error
	DeleteNotificationPreferences(ctx context.Context, userID uuid.UUID) error
	DeleteOldAlertEvents(ctx context.Context) error
	DeleteSavedPlace(ctx context.Context, arg DeleteSavedPlaceParams) error
	DeleteServiceZone(ctx context.Context, id uuid.UUID) (ServiceZone, error)
	DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error
	DeleteStaleDriverLocations(ctx context.Context) error
	ExpireDriverBadges(ctx context.Context) error
	// Rides still in 'requested' with no accepted driver after the cutoff are
	// expired in bulk by the background reaper. cancelled_by stays NULL: the
	// system, not a user, closed the ride.
	ExpireStaleRequestedRides(ctx context.Context, createdAt pgtype.Timestamptz) ([]ExpireStaleRequestedRidesRow, error)
	FailPaymentCharge(ctx context.Context, id uuid.UUID) (PaymentCharge, error)
	FailPayoutRequest(ctx context.Context, arg FailPayoutRequestParams) (PayoutRequest, error)
	FindNearbyDrivers(ctx context.Context, arg FindNearbyDriversParams) ([]FindNearbyDriversRow, error)
	FindServiceZoneForPoint(ctx context.Context, arg FindServiceZoneForPointParams) (ServiceZone, error)
	GetActivePayoutRequestsByDriver(ctx context.Context, driverID uuid.UUID) ([]PayoutRequest, error)
	GetActiveSurgeMultiplier(ctx context.Context, zoneID pgtype.UUID) (SurgeMultiplier, error)
	GetAirport(ctx context.Context, id uuid.UUID) (Airport, error)
	GetAirportByIATA(ctx context.Context, iata string) (Airport, error)
	GetAirportTransfer(ctx context.Context, id uuid.UUID) (AirportTransfer, error)
	GetAirportTransferByRideID(ctx context.Context, rideID uuid.UUID) (AirportTransfer, error)
	GetAlertEventByID(ctx context.Context, id uuid.UUID) (AlertEvent, error)
	GetAlertRuleByID(ctx context.Context, id uuid.UUID) (AlertRule, error)
	GetAllConfig(ctx context.Context) ([]Config, error)
	GetBusinessAccount(ctx context.Context, id uuid.UUID) (BusinessAccount, error)
	GetBusinessMember(ctx context.Context, arg GetBusinessMemberParams) (BusinessMember, error)
	GetBusinessMonthlyUsage(ctx context.Context, arg GetBusinessMonthlyUsageParams) (GetBusinessMonthlyUsageRow, error)
	GetConfig(ctx context.Context, key string) (Config, error)
	GetCorporateInvoiceByID(ctx context.Context, id uuid.UUID) (CorporateInvoice, error)
	GetCostCenterByID(ctx context.Context, id uuid.UUID) (CostCenter, error)
	GetDriverAvailability(ctx context.Context, driverID uuid.UUID) (DriverAvailability, error)
	GetDriverEarningsSummary(ctx context.Context, driverID pgtype.UUID) (GetDriverEarningsSummaryRow, error)
	GetDriverKYC(ctx context.Context, driverID uuid.UUID) (DriverKyc, error)
	GetDriverLocation(ctx context.Context, driverID uuid.UUID) (DriverLocation, error)
	GetDriverOffers(ctx context.Context, driverID uuid.UUID) ([]RideOffer, error)
	GetDriverOffersPage(ctx context.Context, arg GetDriverOffersPageParams) ([]RideOffer, error)
	GetDriverVehicleProfile(ctx context.Context, driverID uuid.UUID) (DriverVehicleProfile, error)
	GetDriverWallet(ctx context.Context, driverID uuid.UUID) (DriverWallet, error)
	GetEmergencyContact(ctx context.Context, arg GetEmergencyContactParams) (EmergencyContact, error)
	GetHeatmapHistory(ctx context.Context, arg GetHeatmapHistoryParams) ([]DemandHeatmap, error)
	GetIdentityVerificationByID(ctx context.Context, id uuid.UUID) (IdentityVerification, error)
	GetIdentityVerificationByUser(ctx context.Context, userID uuid.UUID) (IdentityVerification, error)
	GetLatestHeatmapByZone(ctx context.Context, zoneID uuid.UUID) (DemandHeatmap, error)
	GetLatestVerificationCode(ctx context.Context, arg GetLatestVerificationCodeParams) (VerificationCode, error)
	GetLoyaltyBalance(ctx context.Context, userID uuid.UUID) (LoyaltyPoint, error)
	GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error)
	GetOpenRides(ctx context.Context, limit int32) ([]Ride, error)
	GetOpenRidesPage(ctx context.Context, arg GetOpenRidesPageParams) ([]Ride, error)
	GetPaymentChargeByID(ctx context.Context, id uuid.UUID) (PaymentCharge, error)
	GetPaymentChargeByIdempotencyKey(ctx context.Context, arg GetPaymentChargeByIdempotencyKeyParams) (PaymentCharge, error)
	GetPaymentChargeByProviderChargeID(ctx context.Context, arg GetPaymentChargeByProviderChargeIDParams) (PaymentCharge, error)
	GetPaymentChargesByRide(ctx context.Context, rideID uuid.UUID) ([]PaymentCharge, error)
	GetPaymentEventByProviderEventID(ctx context.Context, arg GetPaymentEventByProviderEventIDParams) (PaymentEvent, error)
	GetPaymentEvents(ctx context.Context, chargeID uuid.UUID) ([]PaymentEvent, error)
	GetPayoutRequestByID(ctx context.Context, id uuid.UUID) (PayoutRequest, error)
	GetPendingCharges(ctx context.Context, limit int32) ([]PaymentCharge, error)
	GetPendingSAFTInvoices(ctx context.Context, limit int32) ([]SaftInvoice, error)
	GetPromoCodeByCode(ctx context.Context, code string) (PromoCode, error)
	GetPromoCodeByID(ctx context.Context, id uuid.UUID) (PromoCode, error)
	GetRideAuthorization(ctx context.Context, rideID uuid.UUID) (RideAuthorization, error)
	GetRideByID(ctx context.Context, id uuid.UUID) (Ride, error)
	GetRideByIDWithDriver(ctx context.Context, id uuid.UUID) (GetRideByIDWithDriverRow, error)
	GetRideByIDWithRider(ctx context.Context, id uuid.UUID) (GetRideByIDWithRiderRow, error)
	GetRideByIdempotencyKey(ctx context.Context, arg GetRideByIdempotencyKeyParams) (Ride, error)
	GetRideDispute(ctx context.Context, id uuid.UUID) (RideDispute, error)
	GetRideEvents(ctx context.Context, rideID uuid.UUID) ([]RideEvent, error)
	GetRideEventsByType(ctx context.Context, arg GetRideEventsByTypeParams) ([]RideEvent, error)
	GetRideEventsPage(ctx context.Context, arg GetRideEventsPageParams) ([]RideEvent, error)
	GetRideReviews(ctx context.Context, rideID uuid.UUID) ([]RideReview, error)
	GetRideShareByTokenHash(ctx context.Context, tokenHash []byte) (GetRideShareByTokenHashRow, error)
	GetRidesByDriver(ctx context.Context, driverID pgtype.UUID) ([]Ride, error)
	GetRidesByDriverPage(ctx context.Context, arg GetRidesByDriverPageParams) ([]Ride, error)
	GetRidesByRider(ctx context.Context, riderID uuid.UUID) ([]Ride, error)
	GetRidesByRiderPage(ctx context.Context, arg GetRidesByRiderPageParams) ([]Ride, error)
	// Uses Postgres built-in point distance (units are 3D-cartesian; for geo coords,
	// this is an approximation suitable for small-radius matching).
	GetRidesNearLocation(ctx context.Context, arg GetRidesNearLocationParams) ([]GetRidesNearLocationRow, error)
	GetSAFTInvoiceByID(ctx context.Context, id uuid.UUID) (SaftInvoice, error)
	GetSAFTInvoiceByNumber(ctx context.Context, invoiceNumber string) (SaftInvoice, error)
	GetSAFTInvoicesByRide(ctx context.Context, rideID uuid.UUID) ([]SaftInvoice, error)
	GetSAFTInvoicesByRider(ctx context.Context, arg GetSAFTInvoicesByRiderParams) ([]SaftInvoice, error)
	GetSAFTInvoicesByStatus(ctx context.Context, arg GetSAFTInvoicesByStatusParams) ([]SaftInvoice, error)
	GetSavedPlaceByID(ctx context.Context, arg GetSavedPlaceByIDParams) (SavedPlace, error)
	GetSavedPlaceByIcon(ctx context.Context, arg GetSavedPlaceByIconParams) ([]SavedPlace, error)
	GetServiceZone(ctx context.Context, id uuid.UUID) (ServiceZone, error)
	GetServiceZoneBySlug(ctx context.Context, slug string) (ServiceZone, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSupportTicket(ctx context.Context, id uuid.UUID) (SupportTicket, error)
	GetSurgeConfig(ctx context.Context) (SurgeConfig, error)
	GetSurgeMultipliersByZone(ctx context.Context, arg GetSurgeMultipliersByZoneParams) ([]SurgeMultiplier, error)
	GetTripShareByRide(ctx context.Context, rideID uuid.UUID) (TripShare, error)
	GetTripShareByToken(ctx context.Context, tokenHash []byte) (TripShare, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserPromoUsages(ctx context.Context, userID uuid.UUID) ([]PromoCodeUsage, error)
	GetVerificationCode(ctx context.Context, id uuid.UUID) (VerificationCode, error)
	GetVerifiedVerificationCode(ctx context.Context, id uuid.UUID) (VerificationCode, error)
	GetWalletEarningsSummary(ctx context.Context, driverID uuid.UUID) (GetWalletEarningsSummaryRow, error)
	GetWalletTransactionByID(ctx context.Context, id uuid.UUID) (WalletTransaction, error)
	GetWalletTransactionByReference(ctx context.Context, referenceID pgtype.UUID) (WalletTransaction, error)
	IncrementPromoUsage(ctx context.Context, id uuid.UUID) (PromoCode, error)
	InvalidateVerificationCodes(ctx context.Context, arg InvalidateVerificationCodesParams) error
	IssueSAFTInvoice(ctx context.Context, id uuid.UUID) (SaftInvoice, error)
	ListActiveAlertRules(ctx context.Context) ([]AlertRule, error)
	ListActivePromoCodes(ctx context.Context) ([]PromoCode, error)
	ListActiveSOSEvents(ctx context.Context, limit int32) ([]ListActiveSOSEventsRow, error)
	ListActiveSurgeMultipliers(ctx context.Context) ([]SurgeMultiplier, error)
	ListActiveTripShares(ctx context.Context, riderID uuid.UUID) ([]TripShare, error)
	ListAirportTransfers(ctx context.Context) ([]AirportTransfer, error)
	// Airport transfer queries used by the airport package. Kept in sqlc
	// -- name: format so the generated db layer stays synchronized.
	ListAirports(ctx context.Context) ([]Airport, error)
	ListAlertEvents(ctx context.Context, arg ListAlertEventsParams) ([]AlertEvent, error)
	ListAlertRules(ctx context.Context) ([]AlertRule, error)
	ListAlertsBySeverity(ctx context.Context, arg ListAlertsBySeverityParams) ([]AlertEvent, error)
	ListBusinessAccountsForUser(ctx context.Context, arg ListBusinessAccountsForUserParams) ([]BusinessAccount, error)
	ListBusinessMembers(ctx context.Context, arg ListBusinessMembersParams) ([]BusinessMember, error)
	ListCorporateInvoicesByAccount(ctx context.Context, arg ListCorporateInvoicesByAccountParams) ([]CorporateInvoice, error)
	ListCostCentersByAccount(ctx context.Context, accountID uuid.UUID) ([]CostCenter, error)
	ListDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error)
	ListDriverBadges(ctx context.Context, driverID uuid.UUID) ([]DriverBadge, error)
	ListDriverKYC(ctx context.Context, arg ListDriverKYCParams) ([]DriverKyc, error)
	ListDriverKYCPage(ctx context.Context, arg ListDriverKYCPageParams) ([]DriverKyc, error)
	ListEmergencyContacts(ctx context.Context, userID uuid.UUID) ([]EmergencyContact, error)
	ListInvoiceItems(ctx context.Context, invoiceID uuid.UUID) ([]CorporateInvoiceItem, error)
	ListLatestHeatmaps(ctx context.Context) ([]DemandHeatmap, error)
	ListLoyaltyTransactions(ctx context.Context, arg ListLoyaltyTransactionsParams) ([]LoyaltyTransaction, error)
	ListOverdueInvoices(ctx context.Context) ([]CorporateInvoice, error)
	ListPaymentCharges(ctx context.Context, arg ListPaymentChargesParams) ([]PaymentCharge, error)
	ListPayoutRequestsByDriver(ctx context.Context, arg ListPayoutRequestsByDriverParams) ([]PayoutRequest, error)
	ListPayoutRequestsByStatus(ctx context.Context, arg ListPayoutRequestsByStatusParams) ([]PayoutRequest, error)
	ListPayoutRequestsInFlight(ctx context.Context, limit int32) ([]PayoutRequest, error)
	ListPayoutRequestsNeedingSubmission(ctx context.Context, limit int32) ([]PayoutRequest, error)
	ListPendingRideAuthorizations(ctx context.Context, arg ListPendingRideAuthorizationsParams) ([]RideAuthorization, error)
	ListPendingVerifications(ctx context.Context, limit int32) ([]IdentityVerification, error)
	ListReadNotifications(ctx context.Context, arg ListReadNotificationsParams) ([]Notification, error)
	ListRideDisputes(ctx context.Context, rideID uuid.UUID) ([]RideDispute, error)
	ListRideDisputesAdmin(ctx context.Context, arg ListRideDisputesAdminParams) ([]RideDispute, error)
	ListRideIncidentReports(ctx context.Context, rideID uuid.UUID) ([]RideIncidentReport, error)
	ListRideSOSEvents(ctx context.Context, rideID uuid.UUID) ([]RideSosEvent, error)
	ListRideShareTokens(ctx context.Context, arg ListRideShareTokensParams) ([]ListRideShareTokensRow, error)
	ListRidesForAdmin(ctx context.Context, arg ListRidesForAdminParams) ([]Ride, error)
	ListSavedPlaces(ctx context.Context, userID uuid.UUID) ([]SavedPlace, error)
	ListServiceZones(ctx context.Context, dollar_1 bool) ([]ServiceZone, error)
	ListSupportTicketsAdmin(ctx context.Context, arg ListSupportTicketsAdminParams) ([]SupportTicket, error)
	ListSupportTicketsByUser(ctx context.Context, arg ListSupportTicketsByUserParams) ([]SupportTicket, error)
	ListSupportTicketsForRide(ctx context.Context, rideID uuid.UUID) ([]SupportTicket, error)
	ListTripShareViewers(ctx context.Context, tripShareID uuid.UUID) ([]TripShareViewer, error)
	ListUnacknowledgedAlerts(ctx context.Context, limit int32) ([]AlertEvent, error)
	ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error)
	MarkDriverArriving(ctx context.Context, id uuid.UUID) (Ride, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	MarkPayoutRequestProcessing(ctx context.Context, id uuid.UUID) (PayoutRequest, error)
	MarkRideInProgress(ctx context.Context, id uuid.UUID) (Ride, error)
	MarkRideMatched(ctx context.Context, id uuid.UUID) (Ride, error)
	MarkRideNoShow(ctx context.Context, arg MarkRideNoShowParams) (Ride, error)
	MarkSAFTInvoicePaid(ctx context.Context, id uuid.UUID) (SaftInvoice, error)
	MarkVerificationCodeVerified(ctx context.Context, id uuid.UUID) (VerificationCode, error)
	// Payment analytics for the admin dashboard. All queries are windowed on a
	// single "since" timestamp so the HTTP layer can clamp the window (days).
	// Counts and volumes for one status window. FILTER keeps each metric in one
	// pass; ::bigint casts keep the JSON layer on plain int64s.
	PaymentAnalyticsSummary(ctx context.Context, createdAt pgtype.Timestamptz) (PaymentAnalyticsSummaryRow, error)
	// Per-day completed volume and refunds for trend charts.
	PaymentDailyVolume(ctx context.Context, createdAt pgtype.Timestamptz) ([]PaymentDailyVolumeRow, error)
	// Per-provider totals so a misbehaving provider is visible in one glance.
	PaymentProviderBreakdown(ctx context.Context, createdAt pgtype.Timestamptz) ([]PaymentProviderBreakdownRow, error)
	// Automatic reassignment: when the assigned driver cancels a not-yet-started
	// ride, the ride returns to the open pool so other drivers can bid on it.
	ReassignRideToRequested(ctx context.Context, arg ReassignRideToRequestedParams) (Ride, error)
	RecordPaymentEvent(ctx context.Context, arg RecordPaymentEventParams) (PaymentEvent, error)
	RecordPromoUsage(ctx context.Context, arg RecordPromoUsageParams) error
	RecordVerificationAttempt(ctx context.Context, id uuid.UUID) (VerificationCode, error)
	RefreshUserRating(ctx context.Context, revieweeID uuid.UUID) (pgtype.Numeric, error)
	RefundPaymentCharge(ctx context.Context, id uuid.UUID) (PaymentCharge, error)
	RejectIdentityVerification(ctx context.Context, arg RejectIdentityVerificationParams) (IdentityVerification, error)
	RejectRideAuthorization(ctx context.Context, arg RejectRideAuthorizationParams) (RideAuthorization, error)
	ResolveRideSOSEvent(ctx context.Context, arg ResolveRideSOSEventParams) (RideSosEvent, error)
	ReviewDriverKYC(ctx context.Context, arg ReviewDriverKYCParams) (DriverKyc, error)
	RevokeRideShareToken(ctx context.Context, arg RevokeRideShareTokenParams) (RevokeRideShareTokenRow, error)
	RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error)
	SetAcceptedFare(ctx context.Context, arg SetAcceptedFareParams) (Ride, error)
	SetDriverAvailability(ctx context.Context, arg SetDriverAvailabilityParams) (DriverAvailability, error)
	SetDriverOnRide(ctx context.Context, arg SetDriverOnRideParams) (Ride, error)
	SetPayoutRequestReference(ctx context.Context, arg SetPayoutRequestReferenceParams) (PayoutRequest, error)
	SetRidePaymentMethod(ctx context.Context, arg SetRidePaymentMethodParams) (Ride, error)
	SetRideTripPIN(ctx context.Context, arg SetRideTripPINParams) (Ride, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error)
	SetWalletTransactionStatus(ctx context.Context, arg SetWalletTransactionStatusParams) error
	UpdateAirportTransfer(ctx context.Context, arg UpdateAirportTransferParams) (AirportTransfer, error)
	UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error)
	UpdateAlertRuleLastTriggered(ctx context.Context, id uuid.UUID) error
	UpdateBusinessAccountLimits(ctx context.Context, arg UpdateBusinessAccountLimitsParams) (BusinessAccount, error)
	UpdateBusinessMemberLimit(ctx context.Context, arg UpdateBusinessMemberLimitParams) (BusinessMember, error)
	UpdateCorporateInvoiceStatus(ctx context.Context, arg UpdateCorporateInvoiceStatusParams) (CorporateInvoice, error)
	UpdateCostCenter(ctx context.Context, arg UpdateCostCenterParams) (CostCenter, error)
	UpdateCostCenterSpending(ctx context.Context, arg UpdateCostCenterSpendingParams) (CostCenter, error)
	UpdateDriverVehicleProfile(ctx context.Context, arg UpdateDriverVehicleProfileParams) (DriverVehicleProfile, error)
	UpdateEmergencyContact(ctx context.Context, arg UpdateEmergencyContactParams) (EmergencyContact, error)
	UpdateIdentityVerificationStatus(ctx context.Context, arg UpdateIdentityVerificationStatusParams) (IdentityVerification, error)
	UpdateLastPayout(ctx context.Context, driverID uuid.UUID) error
	UpdateLoyaltyTier(ctx context.Context, arg UpdateLoyaltyTierParams) error
	UpdatePaymentChargeStatus(ctx context.Context, arg UpdatePaymentChargeStatusParams) (PaymentCharge, error)
	UpdateRideDisputeStatus(ctx context.Context, arg UpdateRideDisputeStatusParams) (RideDispute, error)
	UpdateSavedPlace(ctx context.Context, arg UpdateSavedPlaceParams) (SavedPlace, error)
	UpdateServiceZone(ctx context.Context, arg UpdateServiceZoneParams) (ServiceZone, error)
	UpdateSupportTicketStatus(ctx context.Context, arg UpdateSupportTicketStatusParams) (SupportTicket, error)
	UpdateSurgeConfig(ctx context.Context, arg UpdateSurgeConfigParams) (SurgeConfig, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error)
	UpsertDriverKYC(ctx context.Context, arg UpsertDriverKYCParams) (DriverKyc, error)
	UpsertDriverLocation(ctx context.Context, arg UpsertDriverLocationParams) (DriverLocation, error)
	UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error)
	VerifyRideTripPIN(ctx context.Context, arg VerifyRideTripPINParams) (Ride, error)
}

var _ Querier = (*Queries)(nil)
