// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ride_share_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRideShareToken = `-- name: CreateRideShareToken :one
INSERT INTO ride_share_tokens (ride_id, rider_id, token_hash, expires_at)
SELECT $1, $2, $3, $4
FROM rides
WHERE id = $1 AND rider_id = $2
RETURNING id, ride_id, created_at, expires_at, revoked_at
`

type CreateRideShareTokenParams struct {
	RideID    uuid.UUID
	RiderID   uuid.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type CreateRideShareTokenRow struct {
	ID        uuid.UUID
	RideID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) CreateRideShareToken(ctx context.Context, arg CreateRideShareTokenParams) (CreateRideShareTokenRow, error) {
	row := q.db.QueryRow(ctx, createRideShareToken,
		arg.RideID,
		arg.RiderID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i CreateRideShareTokenRow
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRideShareByTokenHash = `-- name: GetRideShareByTokenHash :one
SELECT
    st.id AS share_id,
    st.ride_id,
    st.expires_at,
    r.status,
    r.pickup_address,
    r.pickup_point,
    r.destination_address,
    r.destination_point,
    d.name AS driver_name,
    vp.license_plate AS vehicle_license_plate,
    vp.make AS vehicle_make,
    vp.model AS vehicle_model,
    vp.year AS vehicle_year,
    vp.color AS vehicle_color
FROM ride_share_tokens st
JOIN rides r ON r.id = st.ride_id
LEFT JOIN users d ON d.id = r.driver_id AND d.role = 'driver'
LEFT JOIN driver_vehicle_profiles vp ON vp.driver_id = r.driver_id
WHERE st.token_hash = $1
  AND st.revoked_at IS NULL
  AND st.expires_at > NOW()
`

type GetRideShareByTokenHashRow struct {
	ShareID             uuid.UUID
	RideID              uuid.UUID
	ExpiresAt           pgtype.Timestamptz
	Status              string
	PickupAddress       string
	PickupPoint         pgtype.Point
	DestinationAddress  string
	DestinationPoint    pgtype.Point
	DriverName          pgtype.Text
	VehicleLicensePlate pgtype.Text
	VehicleMake         pgtype.Text
	VehicleModel        pgtype.Text
	VehicleYear         pgtype.Int4
	VehicleColor        pgtype.Text
}

func (q *Queries) GetRideShareByTokenHash(ctx context.Context, tokenHash []byte) (GetRideShareByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getRideShareByTokenHash, tokenHash)
	var i GetRideShareByTokenHashRow
	err := row.Scan(
		&i.ShareID,
		&i.RideID,
		&i.ExpiresAt,
		&i.Status,
		&i.PickupAddress,
		&i.PickupPoint,
		&i.DestinationAddress,
		&i.DestinationPoint,
		&i.DriverName,
		&i.VehicleLicensePlate,
		&i.VehicleMake,
		&i.VehicleModel,
		&i.VehicleYear,
		&i.VehicleColor,
	)
	return i, err
}

const listRideShareTokens = `-- name: ListRideShareTokens :many
SELECT id, ride_id, created_at, expires_at, revoked_at
FROM ride_share_tokens
WHERE ride_id = $1 AND rider_id = $2
ORDER BY created_at DESC, id DESC
`

type ListRideShareTokensParams struct {
	RideID  uuid.UUID
	RiderID uuid.UUID
}

type ListRideShareTokensRow struct {
	ID        uuid.UUID
	RideID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) ListRideShareTokens(ctx context.Context, arg ListRideShareTokensParams) ([]ListRideShareTokensRow, error) {
	rows, err := q.db.Query(ctx, listRideShareTokens, arg.RideID, arg.RiderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRideShareTokensRow
	for rows.Next() {
		var i ListRideShareTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRideShareToken = `-- name: RevokeRideShareToken :one
UPDATE ride_share_tokens
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE id = $1 AND ride_id = $2 AND rider_id = $3
RETURNING id, ride_id, created_at, expires_at, revoked_at
`

type RevokeRideShareTokenParams struct {
	ID      uuid.UUID
	RideID  uuid.UUID
	RiderID uuid.UUID
}

type RevokeRideShareTokenRow struct {
	ID        uuid.UUID
	RideID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeRideShareToken(ctx context.Context, arg RevokeRideShareTokenParams) (RevokeRideShareTokenRow, error) {
	row := q.db.QueryRow(ctx, revokeRideShareToken, arg.ID, arg.RideID, arg.RiderID)
	var i RevokeRideShareTokenRow
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
