// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ride_offers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const acceptRideOffer = `-- name: AcceptRideOffer :one
WITH accepted AS (
    UPDATE ride_offers AS ro
    SET status = 'accepted', responded_at = NOW()
    WHERE ro.ride_id = $1 AND ro.driver_id = $2 AND ro.status = 'offered' AND ro.expires_at > NOW()
    RETURNING ro.ride_id, ro.driver_id
)
UPDATE rides r
SET driver_id = accepted.driver_id, status = 'matched', updated_at = NOW()
FROM accepted
WHERE r.id = accepted.ride_id AND r.status = 'requested' AND r.driver_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM ride_authorizations ra
                  WHERE ra.ride_id = r.id AND ra.status <> 'approved')
  AND (r.requested_pickup_at IS NULL OR r.requested_pickup_at <= NOW())
RETURNING r.id, r.rider_id, r.driver_id, r.pickup_point, r.destination_point, r.pickup_address, r.destination_address, r.status, r.suggested_fare_cents, r.accepted_fare_cents, r.currency, r.promo_code, r.created_at, r.updated_at, r.completed_at, r.cancelled_at, r.payment_method, r.trip_pin_hash, r.trip_pin_verified, r.cancellation_reason, r.cancelled_by, r.service_zone_id, r.requested_pickup_at, r.business_account_id, r.business_member_id, r.idempotency_key, r.idempotency_payload_hash
`

type AcceptRideOfferParams struct {
	RideID   uuid.UUID
	DriverID uuid.UUID
}

func (q *Queries) AcceptRideOffer(ctx context.Context, arg AcceptRideOfferParams) (Ride, error) {
	row := q.db.QueryRow(ctx, acceptRideOffer, arg.RideID, arg.DriverID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const declineRideOffer = `-- name: DeclineRideOffer :exec
UPDATE ride_offers
SET status = 'declined', responded_at = NOW()
WHERE ride_id = $1 AND driver_id = $2 AND status = 'offered'
`

type DeclineRideOfferParams struct {
	RideID   uuid.UUID
	DriverID uuid.UUID
}

func (q *Queries) DeclineRideOffer(ctx context.Context, arg DeclineRideOfferParams) error {
	_, err := q.db.Exec(ctx, declineRideOffer, arg.RideID, arg.DriverID)
	return err
}

const getDriverOffers = `-- name: GetDriverOffers :many
SELECT id, ride_id, driver_id, status, expires_at, created_at, responded_at
FROM ride_offers
WHERE driver_id = $1 AND status = 'offered' AND expires_at > NOW()
ORDER BY created_at ASC
`

func (q *Queries) GetDriverOffers(ctx context.Context, driverID uuid.UUID) ([]RideOffer, error) {
	rows, err := q.db.Query(ctx, getDriverOffers, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideOffer
	for rows.Next() {
		var i RideOffer
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.DriverID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDriverOffersPage = `-- name: GetDriverOffersPage :many
SELECT id, ride_id, driver_id, status, expires_at, created_at, responded_at
FROM ride_offers
WHERE driver_id = $1 AND status = 'offered' AND expires_at > NOW()
ORDER BY created_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type GetDriverOffersPageParams struct {
	DriverID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetDriverOffersPage(ctx context.Context, arg GetDriverOffersPageParams) ([]RideOffer, error) {
	rows, err := q.db.Query(ctx, getDriverOffersPage, arg.DriverID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideOffer
	for rows.Next() {
		var i RideOffer
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.DriverID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
