// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ride_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRideEvent = `-- name: CreateRideEvent :one
INSERT INTO ride_events (ride_id, event_type, payload, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, ride_id, event_type, payload, created_by, created_at
`

type CreateRideEventParams struct {
	RideID    uuid.UUID
	EventType string
	Payload   []byte
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateRideEvent(ctx context.Context, arg CreateRideEventParams) (RideEvent, error) {
	row := q.db.QueryRow(ctx, createRideEvent,
		arg.RideID,
		arg.EventType,
		arg.Payload,
		arg.CreatedBy,
	)
	var i RideEvent
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.EventType,
		&i.Payload,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRideEvents = `-- name: GetRideEvents :many
SELECT id, ride_id, event_type, payload, created_by, created_at FROM ride_events
WHERE ride_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetRideEvents(ctx context.Context, rideID uuid.UUID) ([]RideEvent, error) {
	rows, err := q.db.Query(ctx, getRideEvents, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideEvent
	for rows.Next() {
		var i RideEvent
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.EventType,
			&i.Payload,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRideEventsByType = `-- name: GetRideEventsByType :many
SELECT id, ride_id, event_type, payload, created_by, created_at FROM ride_events
WHERE ride_id = $1 AND event_type = $2
ORDER BY created_at ASC
`

type GetRideEventsByTypeParams struct {
	RideID    uuid.UUID
	EventType string
}

func (q *Queries) GetRideEventsByType(ctx context.Context, arg GetRideEventsByTypeParams) ([]RideEvent, error) {
	rows, err := q.db.Query(ctx, getRideEventsByType, arg.RideID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideEvent
	for rows.Next() {
		var i RideEvent
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.EventType,
			&i.Payload,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRideEventsPage = `-- name: GetRideEventsPage :many
SELECT id, ride_id, event_type, payload, created_by, created_at FROM ride_events
WHERE ride_id = $1
ORDER BY created_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type GetRideEventsPageParams struct {
	RideID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetRideEventsPage(ctx context.Context, arg GetRideEventsPageParams) ([]RideEvent, error) {
	rows, err := q.db.Query(ctx, getRideEventsPage, arg.RideID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideEvent
	for rows.Next() {
		var i RideEvent
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.EventType,
			&i.Payload,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
