// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rides.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRide = `-- name: CancelRide :one
UPDATE rides
SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW(),
    cancellation_reason = $2, cancelled_by = $3
WHERE id = $1 AND status IN ('requested', 'matched', 'driver_arriving', 'in_progress')
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type CancelRideParams struct {
	ID                 uuid.UUID
	CancellationReason pgtype.Text
	CancelledBy        pgtype.UUID
}

func (q *Queries) CancelRide(ctx context.Context, arg CancelRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, cancelRide, arg.ID, arg.CancellationReason, arg.CancelledBy)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const cancelRideByRider = `-- name: CancelRideByRider :one
UPDATE rides
SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW(),
    cancellation_reason = $3, cancelled_by = $4
WHERE id = $1 AND rider_id = $2
  AND status IN ('requested', 'matched', 'driver_arriving')
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type CancelRideByRiderParams struct {
	ID                 uuid.UUID
	RiderID            uuid.UUID
	CancellationReason pgtype.Text
	CancelledBy        pgtype.UUID
}

func (q *Queries) CancelRideByRider(ctx context.Context, arg CancelRideByRiderParams) (Ride, error) {
	row := q.db.QueryRow(ctx, cancelRideByRider,
		arg.ID,
		arg.RiderID,
		arg.CancellationReason,
		arg.CancelledBy,
	)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const completeRide = `-- name: CompleteRide :one
UPDATE rides
SET status = 'completed', completed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'in_progress'
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

func (q *Queries) CompleteRide(ctx context.Context, id uuid.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, completeRide, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const createRide = `-- name: CreateRide :one
INSERT INTO rides (rider_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, currency, promo_code, service_zone_id, requested_pickup_at)
VALUES ($1, $2::point, $3::point, $4, $5, 'requested', $6, $7, $8, $9, $10)
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type CreateRideParams struct {
	RiderID            uuid.UUID
	Column2            pgtype.Point
	Column3            pgtype.Point
	PickupAddress      string
	DestinationAddress string
	SuggestedFareCents pgtype.Numeric
	Currency           string
	PromoCode          pgtype.Text
	ServiceZoneID      pgtype.UUID
	RequestedPickupAt  pgtype.Timestamptz
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, createRide,
		arg.RiderID,
		arg.Column2,
		arg.Column3,
		arg.PickupAddress,
		arg.DestinationAddress,
		arg.SuggestedFareCents,
		arg.Currency,
		arg.PromoCode,
		arg.ServiceZoneID,
		arg.RequestedPickupAt,
	)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const createRideIdempotent = `-- name: CreateRideIdempotent :one
INSERT INTO rides (
    rider_id, pickup_point, destination_point, pickup_address,
    destination_address, status, suggested_fare_cents, currency, promo_code,
    service_zone_id, requested_pickup_at, business_account_id,
    business_member_id, idempotency_key, idempotency_payload_hash
)
VALUES ($1, $2::point, $3::point, $4, $5, 'requested', $6, $7, $8, $9, $10,
        $11, $12, $13, $14)
ON CONFLICT (rider_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL
DO NOTHING
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type CreateRideIdempotentParams struct {
	RiderID                uuid.UUID
	Column2                pgtype.Point
	Column3                pgtype.Point
	PickupAddress          string
	DestinationAddress     string
	SuggestedFareCents     pgtype.Numeric
	Currency               string
	PromoCode              pgtype.Text
	ServiceZoneID          pgtype.UUID
	RequestedPickupAt      pgtype.Timestamptz
	BusinessAccountID      pgtype.UUID
	BusinessMemberID       pgtype.UUID
	IdempotencyKey         pgtype.Text
	IdempotencyPayloadHash pgtype.Text
}

func (q *Queries) CreateRideIdempotent(ctx context.Context, arg CreateRideIdempotentParams) (Ride, error) {
	row := q.db.QueryRow(ctx, createRideIdempotent,
		arg.RiderID,
		arg.Column2,
		arg.Column3,
		arg.PickupAddress,
		arg.DestinationAddress,
		arg.SuggestedFareCents,
		arg.Currency,
		arg.PromoCode,
		arg.ServiceZoneID,
		arg.RequestedPickupAt,
		arg.BusinessAccountID,
		arg.BusinessMemberID,
		arg.IdempotencyKey,
		arg.IdempotencyPayloadHash,
	)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const expireStaleRequestedRides = `-- name: ExpireStaleRequestedRides :many
UPDATE rides
SET status = 'cancelled',
    cancellation_reason = 'expired',
    cancelled_at = NOW(),
    updated_at = NOW()
WHERE id IN (
    SELECT id FROM rides
    WHERE rides.status = 'requested'
      AND rides.driver_id IS NULL
      AND rides.created_at < $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, rider_id, suggested_fare_cents, currency
`

type ExpireStaleRequestedRidesRow struct {
	ID                 uuid.UUID
	RiderID            uuid.UUID
	SuggestedFareCents pgtype.Numeric
	Currency           string
}

// Rides still in 'requested' with no accepted driver after the cutoff are
// expired in bulk by the background reaper. cancelled_by stays NULL: the
// system, not a user, closed the ride.
func (q *Queries) ExpireStaleRequestedRides(ctx context.Context, createdAt pgtype.Timestamptz) ([]ExpireStaleRequestedRidesRow, error) {
	rows, err := q.db.Query(ctx, expireStaleRequestedRides, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpireStaleRequestedRidesRow
	for rows.Next() {
		var i ExpireStaleRequestedRidesRow
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.SuggestedFareCents,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenRides = `-- name: GetOpenRides :many
SELECT id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash FROM rides
WHERE status = 'requested' AND driver_id IS NULL
  AND (requested_pickup_at IS NULL OR requested_pickup_at <= NOW())
  AND NOT EXISTS (
      SELECT 1 FROM ride_authorizations ra
      WHERE ra.ride_id = rides.id AND ra.status <> 'approved'
  )
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetOpenRides(ctx context.Context, limit int32) ([]Ride, error) {
	rows, err := q.db.Query(ctx, getOpenRides, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.PickupPoint,
			&i.DestinationPoint,
			&i.PickupAddress,
			&i.DestinationAddress,
			&i.Status,
			&i.SuggestedFareCents,
			&i.AcceptedFareCents,
			&i.Currency,
			&i.PromoCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.PaymentMethod,
			&i.TripPinHash,
			&i.TripPinVerified,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.ServiceZoneID,
			&i.RequestedPickupAt,
			&i.BusinessAccountID,
			&i.BusinessMemberID,
			&i.IdempotencyKey,
			&i.IdempotencyPayloadHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenRidesPage = `-- name: GetOpenRidesPage :many
SELECT id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash FROM rides
WHERE status = 'requested' AND driver_id IS NULL
  AND (requested_pickup_at IS NULL OR requested_pickup_at <= NOW())
  AND NOT EXISTS (
      SELECT 1 FROM ride_authorizations ra
      WHERE ra.ride_id = rides.id AND ra.status = 'pending'
  )
ORDER BY created_at ASC, id ASC
LIMIT $1 OFFSET $2
`

type GetOpenRidesPageParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetOpenRidesPage(ctx context.Context, arg GetOpenRidesPageParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, getOpenRidesPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.PickupPoint,
			&i.DestinationPoint,
			&i.PickupAddress,
			&i.DestinationAddress,
			&i.Status,
			&i.SuggestedFareCents,
			&i.AcceptedFareCents,
			&i.Currency,
			&i.PromoCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.PaymentMethod,
			&i.TripPinHash,
			&i.TripPinVerified,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.ServiceZoneID,
			&i.RequestedPickupAt,
			&i.BusinessAccountID,
			&i.BusinessMemberID,
			&i.IdempotencyKey,
			&i.IdempotencyPayloadHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRideByID = `-- name: GetRideByID :one
SELECT id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash FROM rides
WHERE id = $1
`

func (q *Queries) GetRideByID(ctx context.Context, id uuid.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, getRideByID, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const getRideByIDWithDriver = `-- name: GetRideByIDWithDriver :one
SELECT r.id, r.rider_id, r.driver_id, r.pickup_point, r.destination_point, r.pickup_address, r.destination_address, r.status, r.suggested_fare_cents, r.accepted_fare_cents, r.currency, r.promo_code, r.created_at, r.updated_at, r.completed_at, r.cancelled_at, r.payment_method, r.trip_pin_hash, r.trip_pin_verified, r.cancellation_reason, r.cancelled_by, r.service_zone_id, r.requested_pickup_at, r.business_account_id, r.business_member_id, r.idempotency_key, r.idempotency_payload_hash, u.phone AS driver_phone, u.name AS driver_name, u.rating, u.acceptance_rate
FROM rides r
JOIN users u ON u.id = r.driver_id
WHERE r.id = $1
`

type GetRideByIDWithDriverRow struct {
	ID                     uuid.UUID
	RiderID                uuid.UUID
	DriverID               pgtype.UUID
	PickupPoint            pgtype.Point
	DestinationPoint       pgtype.Point
	PickupAddress          string
	DestinationAddress     string
	Status                 string
	SuggestedFareCents     pgtype.Numeric
	AcceptedFareCents      pgtype.Numeric
	Currency               string
	PromoCode              pgtype.Text
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	PaymentMethod          string
	TripPinHash            pgtype.Text
	TripPinVerified        bool
	CancellationReason     pgtype.Text
	CancelledBy            pgtype.UUID
	ServiceZoneID          pgtype.UUID
	RequestedPickupAt      pgtype.Timestamptz
	BusinessAccountID      pgtype.UUID
	BusinessMemberID       pgtype.UUID
	IdempotencyKey         pgtype.Text
	IdempotencyPayloadHash pgtype.Text
	DriverPhone            string
	DriverName             string
	Rating                 pgtype.Numeric
	AcceptanceRate         pgtype.Numeric
}

func (q *Queries) GetRideByIDWithDriver(ctx context.Context, id uuid.UUID) (GetRideByIDWithDriverRow, error) {
	row := q.db.QueryRow(ctx, getRideByIDWithDriver, id)
	var i GetRideByIDWithDriverRow
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
		&i.DriverPhone,
		&i.DriverName,
		&i.Rating,
		&i.AcceptanceRate,
	)
	return i, err
}

const getRideByIDWithRider = `-- name: GetRideByIDWithRider :one
SELECT r.id, r.rider_id, r.driver_id, r.pickup_point, r.destination_point, r.pickup_address, r.destination_address, r.status, r.suggested_fare_cents, r.accepted_fare_cents, r.currency, r.promo_code, r.created_at, r.updated_at, r.completed_at, r.cancelled_at, r.payment_method, r.trip_pin_hash, r.trip_pin_verified, r.cancellation_reason, r.cancelled_by, r.service_zone_id, r.requested_pickup_at, r.business_account_id, r.business_member_id, r.idempotency_key, r.idempotency_payload_hash, u.phone AS rider_phone, u.name AS rider_name
FROM rides r
JOIN users u ON u.id = r.rider_id
WHERE r.id = $1
`

type GetRideByIDWithRiderRow struct {
	ID                     uuid.UUID
	RiderID                uuid.UUID
	DriverID               pgtype.UUID
	PickupPoint            pgtype.Point
	DestinationPoint       pgtype.Point
	PickupAddress          string
	DestinationAddress     string
	Status                 string
	SuggestedFareCents     pgtype.Numeric
	AcceptedFareCents      pgtype.Numeric
	Currency               string
	PromoCode              pgtype.Text
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	CancelledAt            pgtype.Timestamptz
	PaymentMethod          string
	TripPinHash            pgtype.Text
	TripPinVerified        bool
	CancellationReason     pgtype.Text
	CancelledBy            pgtype.UUID
	ServiceZoneID          pgtype.UUID
	RequestedPickupAt      pgtype.Timestamptz
	BusinessAccountID      pgtype.UUID
	BusinessMemberID       pgtype.UUID
	IdempotencyKey         pgtype.Text
	IdempotencyPayloadHash pgtype.Text
	RiderPhone             string
	RiderName              string
}

func (q *Queries) GetRideByIDWithRider(ctx context.Context, id uuid.UUID) (GetRideByIDWithRiderRow, error) {
	row := q.db.QueryRow(ctx, getRideByIDWithRider, id)
	var i GetRideByIDWithRiderRow
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
		&i.RiderPhone,
		&i.RiderName,
	)
	return i, err
}

const getRideByIdempotencyKey = `-- name: GetRideByIdempotencyKey :one
SELECT id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash FROM rides
WHERE rider_id = $1 AND idempotency_key = $2
`

type GetRideByIdempotencyKeyParams struct {
	RiderID        uuid.UUID
	IdempotencyKey pgtype.Text
}

func (q *Queries) GetRideByIdempotencyKey(ctx context.Context, arg GetRideByIdempotencyKeyParams) (Ride, error) {
	row := q.db.QueryRow(ctx, getRideByIdempotencyKey, arg.RiderID, arg.IdempotencyKey)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const getRidesByDriver = `-- name: GetRidesByDriver :many
SELECT id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash FROM rides
WHERE driver_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRidesByDriver(ctx context.Context, driverID pgtype.UUID) ([]Ride, error) {
	rows, err := q.db.Query(ctx, getRidesByDriver, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.PickupPoint,
			&i.DestinationPoint,
			&i.PickupAddress,
			&i.DestinationAddress,
			&i.Status,
			&i.SuggestedFareCents,
			&i.AcceptedFareCents,
			&i.Currency,
			&i.PromoCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.PaymentMethod,
			&i.TripPinHash,
			&i.TripPinVerified,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.ServiceZoneID,
			&i.RequestedPickupAt,
			&i.BusinessAccountID,
			&i.BusinessMemberID,
			&i.IdempotencyKey,
			&i.IdempotencyPayloadHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRidesByDriverPage = `-- name: GetRidesByDriverPage :many
SELECT id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash FROM rides
WHERE driver_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type GetRidesByDriverPageParams struct {
	DriverID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetRidesByDriverPage(ctx context.Context, arg GetRidesByDriverPageParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, getRidesByDriverPage, arg.DriverID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.PickupPoint,
			&i.DestinationPoint,
			&i.PickupAddress,
			&i.DestinationAddress,
			&i.Status,
			&i.SuggestedFareCents,
			&i.AcceptedFareCents,
			&i.Currency,
			&i.PromoCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.PaymentMethod,
			&i.TripPinHash,
			&i.TripPinVerified,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.ServiceZoneID,
			&i.RequestedPickupAt,
			&i.BusinessAccountID,
			&i.BusinessMemberID,
			&i.IdempotencyKey,
			&i.IdempotencyPayloadHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRidesByRider = `-- name: GetRidesByRider :many
SELECT id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash FROM rides
WHERE rider_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRidesByRider(ctx context.Context, riderID uuid.UUID) ([]Ride, error) {
	rows, err := q.db.Query(ctx, getRidesByRider, riderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.PickupPoint,
			&i.DestinationPoint,
			&i.PickupAddress,
			&i.DestinationAddress,
			&i.Status,
			&i.SuggestedFareCents,
			&i.AcceptedFareCents,
			&i.Currency,
			&i.PromoCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.PaymentMethod,
			&i.TripPinHash,
			&i.TripPinVerified,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.ServiceZoneID,
			&i.RequestedPickupAt,
			&i.BusinessAccountID,
			&i.BusinessMemberID,
			&i.IdempotencyKey,
			&i.IdempotencyPayloadHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRidesByRiderPage = `-- name: GetRidesByRiderPage :many
SELECT id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash FROM rides
WHERE rider_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type GetRidesByRiderPageParams struct {
	RiderID uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) GetRidesByRiderPage(ctx context.Context, arg GetRidesByRiderPageParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, getRidesByRiderPage, arg.RiderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.PickupPoint,
			&i.DestinationPoint,
			&i.PickupAddress,
			&i.DestinationAddress,
			&i.Status,
			&i.SuggestedFareCents,
			&i.AcceptedFareCents,
			&i.Currency,
			&i.PromoCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.PaymentMethod,
			&i.TripPinHash,
			&i.TripPinVerified,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.ServiceZoneID,
			&i.RequestedPickupAt,
			&i.BusinessAccountID,
			&i.BusinessMemberID,
			&i.IdempotencyKey,
			&i.IdempotencyPayloadHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRidesNearLocation = `-- name: GetRidesNearLocation :many
SELECT id, rider_id, pickup_address, destination_address, status, suggested_fare_cents, currency, created_at,
       sqrt(power((pickup_point[0] - $2::point[0])::numeric, 2) + power((pickup_point[1] - $2::point[1])::numeric, 2)) * 111320 AS distance_meters
FROM rides
WHERE status = 'requested'
  AND driver_id IS NULL
  AND (requested_pickup_at IS NULL OR requested_pickup_at <= NOW())
  AND NOT EXISTS (SELECT 1 FROM ride_authorizations ra
                  WHERE ra.ride_id = rides.id AND ra.status = 'pending')
  AND sqrt(power((pickup_point[0] - $2::point[0])::numeric, 2) + power((pickup_point[1] - $2::point[1])::numeric, 2)) * 111320 < $3
ORDER BY distance_meters ASC
LIMIT $1
`

type GetRidesNearLocationParams struct {
	Limit       int32
	Column2     []pgtype.Point
	PickupPoint pgtype.Point
}

type GetRidesNearLocationRow struct {
	ID                 uuid.UUID
	RiderID            uuid.UUID
	PickupAddress      string
	DestinationAddress string
	Status             string
	SuggestedFareCents pgtype.Numeric
	Currency           string
	CreatedAt          pgtype.Timestamptz
	DistanceMeters     int32
}

// Uses Postgres built-in point distance (units are 3D-cartesian; for geo coords,
// this is an approximation suitable for small-radius matching).
func (q *Queries) GetRidesNearLocation(ctx context.Context, arg GetRidesNearLocationParams) ([]GetRidesNearLocationRow, error) {
	rows, err := q.db.Query(ctx, getRidesNearLocation, arg.Limit, arg.Column2, arg.PickupPoint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRidesNearLocationRow
	for rows.Next() {
		var i GetRidesNearLocationRow
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.PickupAddress,
			&i.DestinationAddress,
			&i.Status,
			&i.SuggestedFareCents,
			&i.Currency,
			&i.CreatedAt,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRidesForAdmin = `-- name: ListRidesForAdmin :many
SELECT id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash FROM rides
WHERE ($1::text = '' OR status = $1::text)
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListRidesForAdminParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListRidesForAdmin(ctx context.Context, arg ListRidesForAdminParams) ([]Ride, error) {
	rows, err := q.db.Query(ctx, listRidesForAdmin, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DriverID,
			&i.PickupPoint,
			&i.DestinationPoint,
			&i.PickupAddress,
			&i.DestinationAddress,
			&i.Status,
			&i.SuggestedFareCents,
			&i.AcceptedFareCents,
			&i.Currency,
			&i.PromoCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.PaymentMethod,
			&i.TripPinHash,
			&i.TripPinVerified,
			&i.CancellationReason,
			&i.CancelledBy,
			&i.ServiceZoneID,
			&i.RequestedPickupAt,
			&i.BusinessAccountID,
			&i.BusinessMemberID,
			&i.IdempotencyKey,
			&i.IdempotencyPayloadHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDriverArriving = `-- name: MarkDriverArriving :one
UPDATE rides
SET status = 'driver_arriving', updated_at = NOW()
WHERE id = $1 AND status = 'matched'
  AND (requested_pickup_at IS NULL OR requested_pickup_at <= NOW())
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

func (q *Queries) MarkDriverArriving(ctx context.Context, id uuid.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, markDriverArriving, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const markRideInProgress = `-- name: MarkRideInProgress :one
UPDATE rides
SET status = 'in_progress', updated_at = NOW()
WHERE id = $1 AND status = 'driver_arriving'
  AND (requested_pickup_at IS NULL OR requested_pickup_at <= NOW())
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

func (q *Queries) MarkRideInProgress(ctx context.Context, id uuid.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, markRideInProgress, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const markRideMatched = `-- name: MarkRideMatched :one
UPDATE rides
SET status = 'matched', updated_at = NOW()
WHERE rides.id = $1 AND rides.status = 'requested' AND rides.driver_id IS NULL
  AND (rides.requested_pickup_at IS NULL OR rides.requested_pickup_at <= NOW())
  AND NOT EXISTS (SELECT 1 FROM ride_authorizations ra
                  WHERE ra.ride_id = rides.id AND ra.status <> 'approved')
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

func (q *Queries) MarkRideMatched(ctx context.Context, id uuid.UUID) (Ride, error) {
	row := q.db.QueryRow(ctx, markRideMatched, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const markRideNoShow = `-- name: MarkRideNoShow :one
UPDATE rides
SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW(),
    cancellation_reason = 'rider_no_show', cancelled_by = $2
WHERE id = $1 AND driver_id = $2 AND status = 'driver_arriving'
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type MarkRideNoShowParams struct {
	ID          uuid.UUID
	CancelledBy pgtype.UUID
}

func (q *Queries) MarkRideNoShow(ctx context.Context, arg MarkRideNoShowParams) (Ride, error) {
	row := q.db.QueryRow(ctx, markRideNoShow, arg.ID, arg.CancelledBy)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const reassignRideToRequested = `-- name: ReassignRideToRequested :one
UPDATE rides
SET status = 'requested',
    driver_id = NULL,
    accepted_fare_cents = NULL,
    updated_at = NOW()
WHERE id = $1 AND driver_id = $2 AND status IN ('matched', 'driver_arriving')
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type ReassignRideToRequestedParams struct {
	ID       uuid.UUID
	DriverID pgtype.UUID
}

// Automatic reassignment: when the assigned driver cancels a not-yet-started
// ride, the ride returns to the open pool so other drivers can bid on it.
func (q *Queries) ReassignRideToRequested(ctx context.Context, arg ReassignRideToRequestedParams) (Ride, error) {
	row := q.db.QueryRow(ctx, reassignRideToRequested, arg.ID, arg.DriverID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const setAcceptedFare = `-- name: SetAcceptedFare :one
UPDATE rides
SET accepted_fare_cents = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type SetAcceptedFareParams struct {
	ID                uuid.UUID
	AcceptedFareCents pgtype.Numeric
}

func (q *Queries) SetAcceptedFare(ctx context.Context, arg SetAcceptedFareParams) (Ride, error) {
	row := q.db.QueryRow(ctx, setAcceptedFare, arg.ID, arg.AcceptedFareCents)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const setDriverOnRide = `-- name: SetDriverOnRide :one
UPDATE rides
SET driver_id = $2, status = 'matched', updated_at = NOW()
WHERE rides.id = $1 AND rides.status = 'requested' AND rides.driver_id IS NULL
  AND (rides.requested_pickup_at IS NULL OR rides.requested_pickup_at <= NOW())
  AND NOT EXISTS (SELECT 1 FROM ride_authorizations ra
                  WHERE ra.ride_id = rides.id AND ra.status <> 'approved')
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type SetDriverOnRideParams struct {
	ID       uuid.UUID
	DriverID pgtype.UUID
}

func (q *Queries) SetDriverOnRide(ctx context.Context, arg SetDriverOnRideParams) (Ride, error) {
	row := q.db.QueryRow(ctx, setDriverOnRide, arg.ID, arg.DriverID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}
