// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: safety.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRideIncidentReport = `-- name: CreateRideIncidentReport :one
INSERT INTO ride_incident_reports (ride_id, reported_by, category, description)
VALUES ($1, $2, $3, $4)
RETURNING id, ride_id, reported_by, category, description, created_at
`

type CreateRideIncidentReportParams struct {
	RideID      uuid.UUID
	ReportedBy  uuid.UUID
	Category    string
	Description string
}

func (q *Queries) CreateRideIncidentReport(ctx context.Context, arg CreateRideIncidentReportParams) (RideIncidentReport, error) {
	row := q.db.QueryRow(ctx, createRideIncidentReport,
		arg.RideID,
		arg.ReportedBy,
		arg.Category,
		arg.Description,
	)
	var i RideIncidentReport
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.ReportedBy,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createRideSOSEvent = `-- name: CreateRideSOSEvent :one
INSERT INTO ride_sos_events (ride_id, triggered_by, location, note)
VALUES ($1, $2, $3, $4)
RETURNING id, ride_id, triggered_by, status, location, note, created_at, resolved_at, resolved_by
`

type CreateRideSOSEventParams struct {
	RideID      uuid.UUID
	TriggeredBy uuid.UUID
	Location    pgtype.Point
	Note        pgtype.Text
}

func (q *Queries) CreateRideSOSEvent(ctx context.Context, arg CreateRideSOSEventParams) (RideSosEvent, error) {
	row := q.db.QueryRow(ctx, createRideSOSEvent,
		arg.RideID,
		arg.TriggeredBy,
		arg.Location,
		arg.Note,
	)
	var i RideSosEvent
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.TriggeredBy,
		&i.Status,
		&i.Location,
		&i.Note,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const listActiveSOSEvents = `-- name: ListActiveSOSEvents :many
SELECT e.id, e.ride_id, e.triggered_by, e.status, e.location, e.note, e.created_at, e.resolved_at, e.resolved_by, r.status AS ride_status, r.driver_id AS ride_driver_id,
       r.rider_id AS ride_rider_id
FROM ride_sos_events e
JOIN rides r ON r.id = e.ride_id
WHERE e.status = 'active'
ORDER BY e.created_at DESC
LIMIT $1
`

type ListActiveSOSEventsRow struct {
	ID           uuid.UUID
	RideID       uuid.UUID
	TriggeredBy  uuid.UUID
	Status       string
	Location     pgtype.Point
	Note         pgtype.Text
	CreatedAt    pgtype.Timestamptz
	ResolvedAt   pgtype.Timestamptz
	ResolvedBy   pgtype.UUID
	RideStatus   string
	RideDriverID pgtype.UUID
	RideRiderID  uuid.UUID
}

func (q *Queries) ListActiveSOSEvents(ctx context.Context, limit int32) ([]ListActiveSOSEventsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSOSEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSOSEventsRow
	for rows.Next() {
		var i ListActiveSOSEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.TriggeredBy,
			&i.Status,
			&i.Location,
			&i.Note,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.RideStatus,
			&i.RideDriverID,
			&i.RideRiderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRideIncidentReports = `-- name: ListRideIncidentReports :many
SELECT id, ride_id, reported_by, category, description, created_at FROM ride_incident_reports
WHERE ride_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRideIncidentReports(ctx context.Context, rideID uuid.UUID) ([]RideIncidentReport, error) {
	rows, err := q.db.Query(ctx, listRideIncidentReports, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideIncidentReport
	for rows.Next() {
		var i RideIncidentReport
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.ReportedBy,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRideSOSEvents = `-- name: ListRideSOSEvents :many
SELECT id, ride_id, triggered_by, status, location, note, created_at, resolved_at, resolved_by FROM ride_sos_events
WHERE ride_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRideSOSEvents(ctx context.Context, rideID uuid.UUID) ([]RideSosEvent, error) {
	rows, err := q.db.Query(ctx, listRideSOSEvents, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RideSosEvent
	for rows.Next() {
		var i RideSosEvent
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.TriggeredBy,
			&i.Status,
			&i.Location,
			&i.Note,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveRideSOSEvent = `-- name: ResolveRideSOSEvent :one
UPDATE ride_sos_events
SET status = 'resolved', resolved_at = NOW(), resolved_by = $2
WHERE id = $1 AND status = 'active'
RETURNING id, ride_id, triggered_by, status, location, note, created_at, resolved_at, resolved_by
`

type ResolveRideSOSEventParams struct {
	ID         uuid.UUID
	ResolvedBy pgtype.UUID
}

func (q *Queries) ResolveRideSOSEvent(ctx context.Context, arg ResolveRideSOSEventParams) (RideSosEvent, error) {
	row := q.db.QueryRow(ctx, resolveRideSOSEvent, arg.ID, arg.ResolvedBy)
	var i RideSosEvent
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.TriggeredBy,
		&i.Status,
		&i.Location,
		&i.Note,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}
