// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saft.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSAFTInvoice = `-- name: CreateSAFTInvoice :one
INSERT INTO saft_invoices (ride_id, charge_id, invoice_number, issue_date, due_date, customer_name, customer_tax_id, items, total_cents, currency, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'draft')
RETURNING id, ride_id, charge_id, invoice_number, issue_date, due_date, customer_name, customer_tax_id, items, total_cents, currency, status, pdf_content, created_at, issued_at, paid_at
`

type CreateSAFTInvoiceParams struct {
	RideID        uuid.UUID
	ChargeID      pgtype.UUID
	InvoiceNumber string
	IssueDate     pgtype.Date
	DueDate       pgtype.Date
	CustomerName  string
	CustomerTaxID pgtype.Text
	Items         []byte
	TotalCents    pgtype.Numeric
	Currency      string
}

func (q *Queries) CreateSAFTInvoice(ctx context.Context, arg CreateSAFTInvoiceParams) (SaftInvoice, error) {
	row := q.db.QueryRow(ctx, createSAFTInvoice,
		arg.RideID,
		arg.ChargeID,
		arg.InvoiceNumber,
		arg.IssueDate,
		arg.DueDate,
		arg.CustomerName,
		arg.CustomerTaxID,
		arg.Items,
		arg.TotalCents,
		arg.Currency,
	)
	var i SaftInvoice
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.ChargeID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.CustomerName,
		&i.CustomerTaxID,
		&i.Items,
		&i.TotalCents,
		&i.Currency,
		&i.Status,
		&i.PdfContent,
		&i.CreatedAt,
		&i.IssuedAt,
		&i.PaidAt,
	)
	return i, err
}

const getPendingSAFTInvoices = `-- name: GetPendingSAFTInvoices :many
SELECT id, ride_id, charge_id, invoice_number, issue_date, due_date, customer_name, customer_tax_id, items, total_cents, currency, status, pdf_content, created_at, issued_at, paid_at FROM saft_invoices
WHERE status = 'issued'
ORDER BY issued_at ASC
LIMIT $1
`

func (q *Queries) GetPendingSAFTInvoices(ctx context.Context, limit int32) ([]SaftInvoice, error) {
	rows, err := q.db.Query(ctx, getPendingSAFTInvoices, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaftInvoice
	for rows.Next() {
		var i SaftInvoice
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.ChargeID,
			&i.InvoiceNumber,
			&i.IssueDate,
			&i.DueDate,
			&i.CustomerName,
			&i.CustomerTaxID,
			&i.Items,
			&i.TotalCents,
			&i.Currency,
			&i.Status,
			&i.PdfContent,
			&i.CreatedAt,
			&i.IssuedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSAFTInvoiceByID = `-- name: GetSAFTInvoiceByID :one
SELECT id, ride_id, charge_id, invoice_number, issue_date, due_date, customer_name, customer_tax_id, items, total_cents, currency, status, pdf_content, created_at, issued_at, paid_at FROM saft_invoices
WHERE id = $1
`

func (q *Queries) GetSAFTInvoiceByID(ctx context.Context, id uuid.UUID) (SaftInvoice, error) {
	row := q.db.QueryRow(ctx, getSAFTInvoiceByID, id)
	var i SaftInvoice
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.ChargeID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.CustomerName,
		&i.CustomerTaxID,
		&i.Items,
		&i.TotalCents,
		&i.Currency,
		&i.Status,
		&i.PdfContent,
		&i.CreatedAt,
		&i.IssuedAt,
		&i.PaidAt,
	)
	return i, err
}

const getSAFTInvoiceByNumber = `-- name: GetSAFTInvoiceByNumber :one
SELECT id, ride_id, charge_id, invoice_number, issue_date, due_date, customer_name, customer_tax_id, items, total_cents, currency, status, pdf_content, created_at, issued_at, paid_at FROM saft_invoices
WHERE invoice_number = $1
`

func (q *Queries) GetSAFTInvoiceByNumber(ctx context.Context, invoiceNumber string) (SaftInvoice, error) {
	row := q.db.QueryRow(ctx, getSAFTInvoiceByNumber, invoiceNumber)
	var i SaftInvoice
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.ChargeID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.CustomerName,
		&i.CustomerTaxID,
		&i.Items,
		&i.TotalCents,
		&i.Currency,
		&i.Status,
		&i.PdfContent,
		&i.CreatedAt,
		&i.IssuedAt,
		&i.PaidAt,
	)
	return i, err
}

const getSAFTInvoicesByRide = `-- name: GetSAFTInvoicesByRide :many
SELECT id, ride_id, charge_id, invoice_number, issue_date, due_date, customer_name, customer_tax_id, items, total_cents, currency, status, pdf_content, created_at, issued_at, paid_at FROM saft_invoices
WHERE ride_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetSAFTInvoicesByRide(ctx context.Context, rideID uuid.UUID) ([]SaftInvoice, error) {
	rows, err := q.db.Query(ctx, getSAFTInvoicesByRide, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaftInvoice
	for rows.Next() {
		var i SaftInvoice
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.ChargeID,
			&i.InvoiceNumber,
			&i.IssueDate,
			&i.DueDate,
			&i.CustomerName,
			&i.CustomerTaxID,
			&i.Items,
			&i.TotalCents,
			&i.Currency,
			&i.Status,
			&i.PdfContent,
			&i.CreatedAt,
			&i.IssuedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSAFTInvoicesByRider = `-- name: GetSAFTInvoicesByRider :many
SELECT i.id, i.ride_id, i.charge_id, i.invoice_number, i.issue_date, i.due_date, i.customer_name, i.customer_tax_id, i.items, i.total_cents, i.currency, i.status, i.pdf_content, i.created_at, i.issued_at, i.paid_at
FROM saft_invoices i
JOIN rides r ON r.id = i.ride_id
WHERE r.rider_id = $1
ORDER BY i.created_at DESC
LIMIT $2
`

type GetSAFTInvoicesByRiderParams struct {
	RiderID uuid.UUID
	Limit   int32
}

func (q *Queries) GetSAFTInvoicesByRider(ctx context.Context, arg GetSAFTInvoicesByRiderParams) ([]SaftInvoice, error) {
	rows, err := q.db.Query(ctx, getSAFTInvoicesByRider, arg.RiderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaftInvoice
	for rows.Next() {
		var i SaftInvoice
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.ChargeID,
			&i.InvoiceNumber,
			&i.IssueDate,
			&i.DueDate,
			&i.CustomerName,
			&i.CustomerTaxID,
			&i.Items,
			&i.TotalCents,
			&i.Currency,
			&i.Status,
			&i.PdfContent,
			&i.CreatedAt,
			&i.IssuedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSAFTInvoicesByStatus = `-- name: GetSAFTInvoicesByStatus :many
SELECT id, ride_id, charge_id, invoice_number, issue_date, due_date, customer_name, customer_tax_id, items, total_cents, currency, status, pdf_content, created_at, issued_at, paid_at FROM saft_invoices
WHERE status = $1
ORDER BY created_at ASC
LIMIT $2
`

type GetSAFTInvoicesByStatusParams struct {
	Status string
	Limit  int32
}

func (q *Queries) GetSAFTInvoicesByStatus(ctx context.Context, arg GetSAFTInvoicesByStatusParams) ([]SaftInvoice, error) {
	rows, err := q.db.Query(ctx, getSAFTInvoicesByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaftInvoice
	for rows.Next() {
		var i SaftInvoice
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.ChargeID,
			&i.InvoiceNumber,
			&i.IssueDate,
			&i.DueDate,
			&i.CustomerName,
			&i.CustomerTaxID,
			&i.Items,
			&i.TotalCents,
			&i.Currency,
			&i.Status,
			&i.PdfContent,
			&i.CreatedAt,
			&i.IssuedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const issueSAFTInvoice = `-- name: IssueSAFTInvoice :one
UPDATE saft_invoices
SET status = 'issued', issued_at = NOW()
WHERE id = $1
RETURNING id, ride_id, charge_id, invoice_number, issue_date, due_date, customer_name, customer_tax_id, items, total_cents, currency, status, pdf_content, created_at, issued_at, paid_at
`

func (q *Queries) IssueSAFTInvoice(ctx context.Context, id uuid.UUID) (SaftInvoice, error) {
	row := q.db.QueryRow(ctx, issueSAFTInvoice, id)
	var i SaftInvoice
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.ChargeID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.CustomerName,
		&i.CustomerTaxID,
		&i.Items,
		&i.TotalCents,
		&i.Currency,
		&i.Status,
		&i.PdfContent,
		&i.CreatedAt,
		&i.IssuedAt,
		&i.PaidAt,
	)
	return i, err
}

const markSAFTInvoicePaid = `-- name: MarkSAFTInvoicePaid :one
UPDATE saft_invoices
SET status = 'paid', paid_at = NOW()
WHERE id = $1
RETURNING id, ride_id, charge_id, invoice_number, issue_date, due_date, customer_name, customer_tax_id, items, total_cents, currency, status, pdf_content, created_at, issued_at, paid_at
`

func (q *Queries) MarkSAFTInvoicePaid(ctx context.Context, id uuid.UUID) (SaftInvoice, error) {
	row := q.db.QueryRow(ctx, markSAFTInvoicePaid, id)
	var i SaftInvoice
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.ChargeID,
		&i.InvoiceNumber,
		&i.IssueDate,
		&i.DueDate,
		&i.CustomerName,
		&i.CustomerTaxID,
		&i.Items,
		&i.TotalCents,
		&i.Currency,
		&i.Status,
		&i.PdfContent,
		&i.CreatedAt,
		&i.IssuedAt,
		&i.PaidAt,
	)
	return i, err
}
