// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_places.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSavedPlace = `-- name: CreateSavedPlace :one
INSERT INTO saved_places (user_id, name, address, latitude, longitude, icon)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, address, latitude, longitude, icon, created_at, updated_at
`

type CreateSavedPlaceParams struct {
	UserID    uuid.UUID
	Name      string
	Address   string
	Latitude  float64
	Longitude float64
	Icon      string
}

func (q *Queries) CreateSavedPlace(ctx context.Context, arg CreateSavedPlaceParams) (SavedPlace, error) {
	row := q.db.QueryRow(ctx, createSavedPlace,
		arg.UserID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Icon,
	)
	var i SavedPlace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSavedPlace = `-- name: DeleteSavedPlace :exec
DELETE FROM saved_places
WHERE id = $1 AND user_id = $2
`

type DeleteSavedPlaceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSavedPlace(ctx context.Context, arg DeleteSavedPlaceParams) error {
	_, err := q.db.Exec(ctx, deleteSavedPlace, arg.ID, arg.UserID)
	return err
}

const getSavedPlaceByID = `-- name: GetSavedPlaceByID :one
SELECT id, user_id, name, address, latitude, longitude, icon, created_at, updated_at FROM saved_places
WHERE id = $1 AND user_id = $2
`

type GetSavedPlaceByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSavedPlaceByID(ctx context.Context, arg GetSavedPlaceByIDParams) (SavedPlace, error) {
	row := q.db.QueryRow(ctx, getSavedPlaceByID, arg.ID, arg.UserID)
	var i SavedPlace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSavedPlaceByIcon = `-- name: GetSavedPlaceByIcon :many
SELECT id, user_id, name, address, latitude, longitude, icon, created_at, updated_at FROM saved_places
WHERE user_id = $1 AND icon = $2
ORDER BY created_at DESC
`

type GetSavedPlaceByIconParams struct {
	UserID uuid.UUID
	Icon   string
}

func (q *Queries) GetSavedPlaceByIcon(ctx context.Context, arg GetSavedPlaceByIconParams) ([]SavedPlace, error) {
	rows, err := q.db.Query(ctx, getSavedPlaceByIcon, arg.UserID, arg.Icon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedPlace
	for rows.Next() {
		var i SavedPlace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedPlaces = `-- name: ListSavedPlaces :many
SELECT id, user_id, name, address, latitude, longitude, icon, created_at, updated_at FROM saved_places
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSavedPlaces(ctx context.Context, userID uuid.UUID) ([]SavedPlace, error) {
	rows, err := q.db.Query(ctx, listSavedPlaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedPlace
	for rows.Next() {
		var i SavedPlace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavedPlace = `-- name: UpdateSavedPlace :one
UPDATE saved_places
SET name = $3, address = $4, latitude = $5, longitude = $6, icon = $7
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, address, latitude, longitude, icon, created_at, updated_at
`

type UpdateSavedPlaceParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Address   string
	Latitude  float64
	Longitude float64
	Icon      string
}

func (q *Queries) UpdateSavedPlace(ctx context.Context, arg UpdateSavedPlaceParams) (SavedPlace, error) {
	row := q.db.QueryRow(ctx, updateSavedPlace,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Icon,
	)
	var i SavedPlace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
