// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_zones.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveServiceZones = `-- name: CountActiveServiceZones :one
SELECT COUNT(*)::bigint FROM service_zones
WHERE is_active = true
`

func (q *Queries) CountActiveServiceZones(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveServiceZones)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createServiceZone = `-- name: CreateServiceZone :one
INSERT INTO service_zones (
    name, slug, min_lat, min_lng, max_lat, max_lng, is_active,
    base_cents, per_km_cents, per_min_cents
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, slug, min_lat, min_lng, max_lat, max_lng, is_active, base_cents, per_km_cents, per_min_cents, created_at, updated_at
`

type CreateServiceZoneParams struct {
	Name        string
	Slug        string
	MinLat      pgtype.Numeric
	MinLng      pgtype.Numeric
	MaxLat      pgtype.Numeric
	MaxLng      pgtype.Numeric
	IsActive    bool
	BaseCents   pgtype.Numeric
	PerKmCents  pgtype.Numeric
	PerMinCents pgtype.Numeric
}

func (q *Queries) CreateServiceZone(ctx context.Context, arg CreateServiceZoneParams) (ServiceZone, error) {
	row := q.db.QueryRow(ctx, createServiceZone,
		arg.Name,
		arg.Slug,
		arg.MinLat,
		arg.MinLng,
		arg.MaxLat,
		arg.MaxLng,
		arg.IsActive,
		arg.BaseCents,
		arg.PerKmCents,
		arg.PerMinCents,
	)
	var i ServiceZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MinLat,
		&i.MinLng,
		&i.MaxLat,
		&i.MaxLng,
		&i.IsActive,
		&i.BaseCents,
		&i.PerKmCents,
		&i.PerMinCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceZone = `-- name: DeleteServiceZone :one
DELETE FROM service_zones
WHERE id = $1
RETURNING id, name, slug, min_lat, min_lng, max_lat, max_lng, is_active, base_cents, per_km_cents, per_min_cents, created_at, updated_at
`

func (q *Queries) DeleteServiceZone(ctx context.Context, id uuid.UUID) (ServiceZone, error) {
	row := q.db.QueryRow(ctx, deleteServiceZone, id)
	var i ServiceZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MinLat,
		&i.MinLng,
		&i.MaxLat,
		&i.MaxLng,
		&i.IsActive,
		&i.BaseCents,
		&i.PerKmCents,
		&i.PerMinCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findServiceZoneForPoint = `-- name: FindServiceZoneForPoint :one
SELECT id, name, slug, min_lat, min_lng, max_lat, max_lng, is_active, base_cents, per_km_cents, per_min_cents, created_at, updated_at FROM service_zones
WHERE is_active = true
  AND $1::numeric BETWEEN min_lat AND max_lat
  AND $2::numeric BETWEEN min_lng AND max_lng
ORDER BY (max_lat - min_lat) * (max_lng - min_lng) ASC, id ASC
LIMIT 1
`

type FindServiceZoneForPointParams struct {
	Column1 pgtype.Numeric
	Column2 pgtype.Numeric
}

func (q *Queries) FindServiceZoneForPoint(ctx context.Context, arg FindServiceZoneForPointParams) (ServiceZone, error) {
	row := q.db.QueryRow(ctx, findServiceZoneForPoint, arg.Column1, arg.Column2)
	var i ServiceZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MinLat,
		&i.MinLng,
		&i.MaxLat,
		&i.MaxLng,
		&i.IsActive,
		&i.BaseCents,
		&i.PerKmCents,
		&i.PerMinCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceZone = `-- name: GetServiceZone :one
SELECT id, name, slug, min_lat, min_lng, max_lat, max_lng, is_active, base_cents, per_km_cents, per_min_cents, created_at, updated_at FROM service_zones
WHERE id = $1
`

func (q *Queries) GetServiceZone(ctx context.Context, id uuid.UUID) (ServiceZone, error) {
	row := q.db.QueryRow(ctx, getServiceZone, id)
	var i ServiceZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MinLat,
		&i.MinLng,
		&i.MaxLat,
		&i.MaxLng,
		&i.IsActive,
		&i.BaseCents,
		&i.PerKmCents,
		&i.PerMinCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceZoneBySlug = `-- name: GetServiceZoneBySlug :one
SELECT id, name, slug, min_lat, min_lng, max_lat, max_lng, is_active, base_cents, per_km_cents, per_min_cents, created_at, updated_at FROM service_zones
WHERE slug = $1
`

func (q *Queries) GetServiceZoneBySlug(ctx context.Context, slug string) (ServiceZone, error) {
	row := q.db.QueryRow(ctx, getServiceZoneBySlug, slug)
	var i ServiceZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MinLat,
		&i.MinLng,
		&i.MaxLat,
		&i.MaxLng,
		&i.IsActive,
		&i.BaseCents,
		&i.PerKmCents,
		&i.PerMinCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceZones = `-- name: ListServiceZones :many
SELECT id, name, slug, min_lat, min_lng, max_lat, max_lng, is_active, base_cents, per_km_cents, per_min_cents, created_at, updated_at FROM service_zones
WHERE ($1::bool = false OR is_active = true)
ORDER BY name ASC, id ASC
`

func (q *Queries) ListServiceZones(ctx context.Context, dollar_1 bool) ([]ServiceZone, error) {
	rows, err := q.db.Query(ctx, listServiceZones, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceZone
	for rows.Next() {
		var i ServiceZone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.MinLat,
			&i.MinLng,
			&i.MaxLat,
			&i.MaxLng,
			&i.IsActive,
			&i.BaseCents,
			&i.PerKmCents,
			&i.PerMinCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceZone = `-- name: UpdateServiceZone :one
UPDATE service_zones
SET name = $2, slug = $3, min_lat = $4, min_lng = $5,
    max_lat = $6, max_lng = $7, is_active = $8,
    base_cents = $9, per_km_cents = $10, per_min_cents = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, min_lat, min_lng, max_lat, max_lng, is_active, base_cents, per_km_cents, per_min_cents, created_at, updated_at
`

type UpdateServiceZoneParams struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	MinLat      pgtype.Numeric
	MinLng      pgtype.Numeric
	MaxLat      pgtype.Numeric
	MaxLng      pgtype.Numeric
	IsActive    bool
	BaseCents   pgtype.Numeric
	PerKmCents  pgtype.Numeric
	PerMinCents pgtype.Numeric
}

func (q *Queries) UpdateServiceZone(ctx context.Context, arg UpdateServiceZoneParams) (ServiceZone, error) {
	row := q.db.QueryRow(ctx, updateServiceZone,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.MinLat,
		arg.MinLng,
		arg.MaxLat,
		arg.MaxLng,
		arg.IsActive,
		arg.BaseCents,
		arg.PerKmCents,
		arg.PerMinCents,
	)
	var i ServiceZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MinLat,
		&i.MinLng,
		&i.MaxLat,
		&i.MaxLng,
		&i.IsActive,
		&i.BaseCents,
		&i.PerKmCents,
		&i.PerMinCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
