// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, device_id, ip_address, user_agent, expires_at, refresh_token_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, device_id, ip_address, user_agent, created_at, expires_at, refresh_token_hash, revoked_at
`

type CreateSessionParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	DeviceID         string
	IpAddress        string
	UserAgent        string
	ExpiresAt        pgtype.Timestamptz
	RefreshTokenHash pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.RefreshTokenHash,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RefreshTokenHash,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < NOW()
   OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, device_id, ip_address, user_agent, created_at, expires_at, refresh_token_hash, revoked_at FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RefreshTokenHash,
		&i.RevokedAt,
	)
	return i, err
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions
SET revoked_at = NOW()
WHERE id = $1
  AND refresh_token_hash = $2
  AND revoked_at IS NULL
  AND expires_at > NOW()
RETURNING id, user_id, device_id, ip_address, user_agent, created_at, expires_at, refresh_token_hash, revoked_at
`

type RotateSessionParams struct {
	ID               uuid.UUID
	RefreshTokenHash pgtype.Text
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.ID, arg.RefreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RefreshTokenHash,
		&i.RevokedAt,
	)
	return i, err
}
