// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: surge.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDemandHeatmap = `-- name: CreateDemandHeatmap :one
INSERT INTO demand_heatmaps (zone_id, zone_name, active_riders, available_drivers, busy_drivers, ratio, surge_multiplier, demand_trend)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, zone_id, zone_name, active_riders, available_drivers, busy_drivers, ratio, surge_multiplier, demand_trend, recorded_at
`

type CreateDemandHeatmapParams struct {
	ZoneID           uuid.UUID
	ZoneName         string
	ActiveRiders     int32
	AvailableDrivers int32
	BusyDrivers      int32
	Ratio            pgtype.Numeric
	SurgeMultiplier  pgtype.Numeric
	DemandTrend      pgtype.Text
}

func (q *Queries) CreateDemandHeatmap(ctx context.Context, arg CreateDemandHeatmapParams) (DemandHeatmap, error) {
	row := q.db.QueryRow(ctx, createDemandHeatmap,
		arg.ZoneID,
		arg.ZoneName,
		arg.ActiveRiders,
		arg.AvailableDrivers,
		arg.BusyDrivers,
		arg.Ratio,
		arg.SurgeMultiplier,
		arg.DemandTrend,
	)
	var i DemandHeatmap
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.ZoneName,
		&i.ActiveRiders,
		&i.AvailableDrivers,
		&i.BusyDrivers,
		&i.Ratio,
		&i.SurgeMultiplier,
		&i.DemandTrend,
		&i.RecordedAt,
	)
	return i, err
}

const createSurgeMultiplier = `-- name: CreateSurgeMultiplier :one
INSERT INTO surge_multipliers (zone_id, multiplier, demand_level, reason, valid_until)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, zone_id, multiplier, demand_level, reason, valid_until, created_at
`

type CreateSurgeMultiplierParams struct {
	ZoneID      pgtype.UUID
	Multiplier  pgtype.Numeric
	DemandLevel string
	Reason      pgtype.Text
	ValidUntil  pgtype.Timestamptz
}

func (q *Queries) CreateSurgeMultiplier(ctx context.Context, arg CreateSurgeMultiplierParams) (SurgeMultiplier, error) {
	row := q.db.QueryRow(ctx, createSurgeMultiplier,
		arg.ZoneID,
		arg.Multiplier,
		arg.DemandLevel,
		arg.Reason,
		arg.ValidUntil,
	)
	var i SurgeMultiplier
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Multiplier,
		&i.DemandLevel,
		&i.Reason,
		&i.ValidUntil,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateExpiredSurge = `-- name: DeactivateExpiredSurge :exec
DELETE FROM surge_multipliers
WHERE valid_until < NOW()
`

func (q *Queries) DeactivateExpiredSurge(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateExpiredSurge)
	return err
}

const getActiveSurgeMultiplier = `-- name: GetActiveSurgeMultiplier :one
SELECT id, zone_id, multiplier, demand_level, reason, valid_until, created_at FROM surge_multipliers
WHERE zone_id = $1 AND valid_until > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSurgeMultiplier(ctx context.Context, zoneID pgtype.UUID) (SurgeMultiplier, error) {
	row := q.db.QueryRow(ctx, getActiveSurgeMultiplier, zoneID)
	var i SurgeMultiplier
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.Multiplier,
		&i.DemandLevel,
		&i.Reason,
		&i.ValidUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getHeatmapHistory = `-- name: GetHeatmapHistory :many
SELECT id, zone_id, zone_name, active_riders, available_drivers, busy_drivers, ratio, surge_multiplier, demand_trend, recorded_at FROM demand_heatmaps
WHERE zone_id = $1 AND recorded_at >= $2
ORDER BY recorded_at DESC
LIMIT $3
`

type GetHeatmapHistoryParams struct {
	ZoneID     uuid.UUID
	RecordedAt pgtype.Timestamptz
	Limit      int32
}

func (q *Queries) GetHeatmapHistory(ctx context.Context, arg GetHeatmapHistoryParams) ([]DemandHeatmap, error) {
	rows, err := q.db.Query(ctx, getHeatmapHistory, arg.ZoneID, arg.RecordedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemandHeatmap
	for rows.Next() {
		var i DemandHeatmap
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.ZoneName,
			&i.ActiveRiders,
			&i.AvailableDrivers,
			&i.BusyDrivers,
			&i.Ratio,
			&i.SurgeMultiplier,
			&i.DemandTrend,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestHeatmapByZone = `-- name: GetLatestHeatmapByZone :one
SELECT id, zone_id, zone_name, active_riders, available_drivers, busy_drivers, ratio, surge_multiplier, demand_trend, recorded_at FROM demand_heatmaps
WHERE zone_id = $1
ORDER BY recorded_at DESC
LIMIT 1
`

func (q *Queries) GetLatestHeatmapByZone(ctx context.Context, zoneID uuid.UUID) (DemandHeatmap, error) {
	row := q.db.QueryRow(ctx, getLatestHeatmapByZone, zoneID)
	var i DemandHeatmap
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.ZoneName,
		&i.ActiveRiders,
		&i.AvailableDrivers,
		&i.BusyDrivers,
		&i.Ratio,
		&i.SurgeMultiplier,
		&i.DemandTrend,
		&i.RecordedAt,
	)
	return i, err
}

const getSurgeConfig = `-- name: GetSurgeConfig :one
SELECT id, enabled, min_multiplier, max_multiplier, threshold_low, threshold_high, threshold_extreme, update_interval_sec, decay_rate, updated_at FROM surge_configs
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetSurgeConfig(ctx context.Context) (SurgeConfig, error) {
	row := q.db.QueryRow(ctx, getSurgeConfig)
	var i SurgeConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.MinMultiplier,
		&i.MaxMultiplier,
		&i.ThresholdLow,
		&i.ThresholdHigh,
		&i.ThresholdExtreme,
		&i.UpdateIntervalSec,
		&i.DecayRate,
		&i.UpdatedAt,
	)
	return i, err
}

const getSurgeMultipliersByZone = `-- name: GetSurgeMultipliersByZone :many
SELECT id, zone_id, multiplier, demand_level, reason, valid_until, created_at FROM surge_multipliers
WHERE zone_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetSurgeMultipliersByZoneParams struct {
	ZoneID pgtype.UUID
	Limit  int32
}

func (q *Queries) GetSurgeMultipliersByZone(ctx context.Context, arg GetSurgeMultipliersByZoneParams) ([]SurgeMultiplier, error) {
	rows, err := q.db.Query(ctx, getSurgeMultipliersByZone, arg.ZoneID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SurgeMultiplier
	for rows.Next() {
		var i SurgeMultiplier
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Multiplier,
			&i.DemandLevel,
			&i.Reason,
			&i.ValidUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSurgeMultipliers = `-- name: ListActiveSurgeMultipliers :many
SELECT id, zone_id, multiplier, demand_level, reason, valid_until, created_at FROM surge_multipliers
WHERE valid_until > NOW()
ORDER BY multiplier DESC
`

func (q *Queries) ListActiveSurgeMultipliers(ctx context.Context) ([]SurgeMultiplier, error) {
	rows, err := q.db.Query(ctx, listActiveSurgeMultipliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SurgeMultiplier
	for rows.Next() {
		var i SurgeMultiplier
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.Multiplier,
			&i.DemandLevel,
			&i.Reason,
			&i.ValidUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestHeatmaps = `-- name: ListLatestHeatmaps :many
SELECT DISTINCT ON (zone_id) id, zone_id, zone_name, active_riders, available_drivers, busy_drivers, ratio, surge_multiplier, demand_trend, recorded_at
FROM demand_heatmaps
ORDER BY zone_id, recorded_at DESC
`

func (q *Queries) ListLatestHeatmaps(ctx context.Context) ([]DemandHeatmap, error) {
	rows, err := q.db.Query(ctx, listLatestHeatmaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DemandHeatmap
	for rows.Next() {
		var i DemandHeatmap
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.ZoneName,
			&i.ActiveRiders,
			&i.AvailableDrivers,
			&i.BusyDrivers,
			&i.Ratio,
			&i.SurgeMultiplier,
			&i.DemandTrend,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSurgeConfig = `-- name: UpdateSurgeConfig :one
UPDATE surge_configs
SET enabled = $1, min_multiplier = $2, max_multiplier = $3, 
    threshold_low = $4, threshold_high = $5, threshold_extreme = $6,
    update_interval_sec = $7, decay_rate = $8,
    updated_at = NOW()
RETURNING id, enabled, min_multiplier, max_multiplier, threshold_low, threshold_high, threshold_extreme, update_interval_sec, decay_rate, updated_at
`

type UpdateSurgeConfigParams struct {
	Enabled           bool
	MinMultiplier     pgtype.Numeric
	MaxMultiplier     pgtype.Numeric
	ThresholdLow      pgtype.Numeric
	ThresholdHigh     pgtype.Numeric
	ThresholdExtreme  pgtype.Numeric
	UpdateIntervalSec int32
	DecayRate         pgtype.Numeric
}

func (q *Queries) UpdateSurgeConfig(ctx context.Context, arg UpdateSurgeConfigParams) (SurgeConfig, error) {
	row := q.db.QueryRow(ctx, updateSurgeConfig,
		arg.Enabled,
		arg.MinMultiplier,
		arg.MaxMultiplier,
		arg.ThresholdLow,
		arg.ThresholdHigh,
		arg.ThresholdExtreme,
		arg.UpdateIntervalSec,
		arg.DecayRate,
	)
	var i SurgeConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.MinMultiplier,
		&i.MaxMultiplier,
		&i.ThresholdLow,
		&i.ThresholdHigh,
		&i.ThresholdExtreme,
		&i.UpdateIntervalSec,
		&i.DecayRate,
		&i.UpdatedAt,
	)
	return i, err
}
