// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trip_shares.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTripShareViewer = `-- name: AddTripShareViewer :exec
INSERT INTO trip_share_viewers (trip_share_id, contact_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (trip_share_id, contact_id) DO NOTHING
`

type AddTripShareViewerParams struct {
	TripShareID uuid.UUID
	ContactID   pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) AddTripShareViewer(ctx context.Context, arg AddTripShareViewerParams) error {
	_, err := q.db.Exec(ctx, addTripShareViewer, arg.TripShareID, arg.ContactID, arg.UserID)
	return err
}

const createTripShare = `-- name: CreateTripShare :one
INSERT INTO trip_shares (ride_id, rider_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, ride_id, rider_id, token_hash, active, expires_at, created_at, deactivated_at
`

type CreateTripShareParams struct {
	RideID    uuid.UUID
	RiderID   uuid.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateTripShare(ctx context.Context, arg CreateTripShareParams) (TripShare, error) {
	row := q.db.QueryRow(ctx, createTripShare,
		arg.RideID,
		arg.RiderID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.RiderID,
		&i.TokenHash,
		&i.Active,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const deactivateExpiredTripShares = `-- name: DeactivateExpiredTripShares :exec
UPDATE trip_shares
SET active = FALSE, deactivated_at = NOW()
WHERE active = TRUE AND expires_at < NOW()
`

func (q *Queries) DeactivateExpiredTripShares(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateExpiredTripShares)
	return err
}

const deactivateTripShare = `-- name: DeactivateTripShare :exec
UPDATE trip_shares
SET active = FALSE, deactivated_at = NOW()
WHERE ride_id = $1
`

func (q *Queries) DeactivateTripShare(ctx context.Context, rideID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateTripShare, rideID)
	return err
}

const getTripShareByRide = `-- name: GetTripShareByRide :one
SELECT id, ride_id, rider_id, token_hash, active, expires_at, created_at, deactivated_at FROM trip_shares
WHERE ride_id = $1
`

func (q *Queries) GetTripShareByRide(ctx context.Context, rideID uuid.UUID) (TripShare, error) {
	row := q.db.QueryRow(ctx, getTripShareByRide, rideID)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.RiderID,
		&i.TokenHash,
		&i.Active,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getTripShareByToken = `-- name: GetTripShareByToken :one
SELECT id, ride_id, rider_id, token_hash, active, expires_at, created_at, deactivated_at FROM trip_shares
WHERE token_hash = $1 AND active = TRUE AND expires_at > NOW()
`

func (q *Queries) GetTripShareByToken(ctx context.Context, tokenHash []byte) (TripShare, error) {
	row := q.db.QueryRow(ctx, getTripShareByToken, tokenHash)
	var i TripShare
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.RiderID,
		&i.TokenHash,
		&i.Active,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const listActiveTripShares = `-- name: ListActiveTripShares :many
SELECT id, ride_id, rider_id, token_hash, active, expires_at, created_at, deactivated_at FROM trip_shares
WHERE rider_id = $1 AND active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListActiveTripShares(ctx context.Context, riderID uuid.UUID) ([]TripShare, error) {
	rows, err := q.db.Query(ctx, listActiveTripShares, riderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripShare
	for rows.Next() {
		var i TripShare
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.RiderID,
			&i.TokenHash,
			&i.Active,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripShareViewers = `-- name: ListTripShareViewers :many
SELECT id, trip_share_id, contact_id, user_id, added_at FROM trip_share_viewers
WHERE trip_share_id = $1
`

func (q *Queries) ListTripShareViewers(ctx context.Context, tripShareID uuid.UUID) ([]TripShareViewer, error) {
	rows, err := q.db.Query(ctx, listTripShareViewers, tripShareID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripShareViewer
	for rows.Next() {
		var i TripShareViewer
		if err := rows.Scan(
			&i.ID,
			&i.TripShareID,
			&i.ContactID,
			&i.UserID,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
