// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trust.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDriverKYC = `-- name: GetDriverKYC :one
SELECT driver_id, id_document, license_number, vehicle_plate, status, submitted_at, reviewed_at, review_note
FROM driver_kyc WHERE driver_id = $1
`

func (q *Queries) GetDriverKYC(ctx context.Context, driverID uuid.UUID) (DriverKyc, error) {
	row := q.db.QueryRow(ctx, getDriverKYC, driverID)
	var i DriverKyc
	err := row.Scan(
		&i.DriverID,
		&i.IDDocument,
		&i.LicenseNumber,
		&i.VehiclePlate,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewNote,
	)
	return i, err
}

const listDriverKYC = `-- name: ListDriverKYC :many
SELECT driver_id, id_document, license_number, vehicle_plate, status, submitted_at, reviewed_at, review_note
FROM driver_kyc
WHERE status = $1
ORDER BY submitted_at ASC
LIMIT $2
`

type ListDriverKYCParams struct {
	Status string
	Limit  int32
}

func (q *Queries) ListDriverKYC(ctx context.Context, arg ListDriverKYCParams) ([]DriverKyc, error) {
	rows, err := q.db.Query(ctx, listDriverKYC, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriverKyc
	for rows.Next() {
		var i DriverKyc
		if err := rows.Scan(
			&i.DriverID,
			&i.IDDocument,
			&i.LicenseNumber,
			&i.VehiclePlate,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriverKYCPage = `-- name: ListDriverKYCPage :many
SELECT driver_id, id_document, license_number, vehicle_plate, status, submitted_at, reviewed_at, review_note
FROM driver_kyc
WHERE status = $1
ORDER BY submitted_at ASC, driver_id ASC
LIMIT $2 OFFSET $3
`

type ListDriverKYCPageParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) ListDriverKYCPage(ctx context.Context, arg ListDriverKYCPageParams) ([]DriverKyc, error) {
	rows, err := q.db.Query(ctx, listDriverKYCPage, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriverKyc
	for rows.Next() {
		var i DriverKyc
		if err := rows.Scan(
			&i.DriverID,
			&i.IDDocument,
			&i.LicenseNumber,
			&i.VehiclePlate,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewDriverKYC = `-- name: ReviewDriverKYC :one
UPDATE driver_kyc
SET status = $2, reviewed_at = NOW(), review_note = $3
WHERE driver_id = $1
RETURNING driver_id, id_document, license_number, vehicle_plate, status, submitted_at, reviewed_at, review_note
`

type ReviewDriverKYCParams struct {
	DriverID   uuid.UUID
	Status     string
	ReviewNote pgtype.Text
}

func (q *Queries) ReviewDriverKYC(ctx context.Context, arg ReviewDriverKYCParams) (DriverKyc, error) {
	row := q.db.QueryRow(ctx, reviewDriverKYC, arg.DriverID, arg.Status, arg.ReviewNote)
	var i DriverKyc
	err := row.Scan(
		&i.DriverID,
		&i.IDDocument,
		&i.LicenseNumber,
		&i.VehiclePlate,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewNote,
	)
	return i, err
}

const setRidePaymentMethod = `-- name: SetRidePaymentMethod :one
UPDATE rides SET payment_method = $2, updated_at = NOW()
WHERE id = $1 AND rider_id = $3 AND status = 'requested'
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type SetRidePaymentMethodParams struct {
	ID            uuid.UUID
	PaymentMethod string
	RiderID       uuid.UUID
}

func (q *Queries) SetRidePaymentMethod(ctx context.Context, arg SetRidePaymentMethodParams) (Ride, error) {
	row := q.db.QueryRow(ctx, setRidePaymentMethod, arg.ID, arg.PaymentMethod, arg.RiderID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const setRideTripPIN = `-- name: SetRideTripPIN :one
UPDATE rides SET trip_pin_hash = $2, updated_at = NOW()
WHERE id = $1 AND rider_id = $3
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type SetRideTripPINParams struct {
	ID          uuid.UUID
	TripPinHash pgtype.Text
	RiderID     uuid.UUID
}

func (q *Queries) SetRideTripPIN(ctx context.Context, arg SetRideTripPINParams) (Ride, error) {
	row := q.db.QueryRow(ctx, setRideTripPIN, arg.ID, arg.TripPinHash, arg.RiderID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}

const upsertDriverKYC = `-- name: UpsertDriverKYC :one
INSERT INTO driver_kyc (driver_id, id_document, license_number, vehicle_plate, status)
VALUES ($1, $2, $3, $4, 'pending')
ON CONFLICT (driver_id) DO UPDATE SET
    id_document = EXCLUDED.id_document,
    license_number = EXCLUDED.license_number,
    vehicle_plate = EXCLUDED.vehicle_plate,
    status = 'pending',
    submitted_at = NOW(),
    reviewed_at = NULL,
    review_note = NULL
RETURNING driver_id, id_document, license_number, vehicle_plate, status, submitted_at, reviewed_at, review_note
`

type UpsertDriverKYCParams struct {
	DriverID      uuid.UUID
	IDDocument    string
	LicenseNumber string
	VehiclePlate  string
}

func (q *Queries) UpsertDriverKYC(ctx context.Context, arg UpsertDriverKYCParams) (DriverKyc, error) {
	row := q.db.QueryRow(ctx, upsertDriverKYC,
		arg.DriverID,
		arg.IDDocument,
		arg.LicenseNumber,
		arg.VehiclePlate,
	)
	var i DriverKyc
	err := row.Scan(
		&i.DriverID,
		&i.IDDocument,
		&i.LicenseNumber,
		&i.VehiclePlate,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewNote,
	)
	return i, err
}

const verifyRideTripPIN = `-- name: VerifyRideTripPIN :one
UPDATE rides SET trip_pin_verified = true, updated_at = NOW()
WHERE id = $1 AND driver_id = $2 AND trip_pin_verified = false
RETURNING id, rider_id, driver_id, pickup_point, destination_point, pickup_address, destination_address, status, suggested_fare_cents, accepted_fare_cents, currency, promo_code, created_at, updated_at, completed_at, cancelled_at, payment_method, trip_pin_hash, trip_pin_verified, cancellation_reason, cancelled_by, service_zone_id, requested_pickup_at, business_account_id, business_member_id, idempotency_key, idempotency_payload_hash
`

type VerifyRideTripPINParams struct {
	ID       uuid.UUID
	DriverID pgtype.UUID
}

func (q *Queries) VerifyRideTripPIN(ctx context.Context, arg VerifyRideTripPINParams) (Ride, error) {
	row := q.db.QueryRow(ctx, verifyRideTripPIN, arg.ID, arg.DriverID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DriverID,
		&i.PickupPoint,
		&i.DestinationPoint,
		&i.PickupAddress,
		&i.DestinationAddress,
		&i.Status,
		&i.SuggestedFareCents,
		&i.AcceptedFareCents,
		&i.Currency,
		&i.PromoCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.PaymentMethod,
		&i.TripPinHash,
		&i.TripPinVerified,
		&i.CancellationReason,
		&i.CancelledBy,
		&i.ServiceZoneID,
		&i.RequestedPickupAt,
		&i.BusinessAccountID,
		&i.BusinessMemberID,
		&i.IdempotencyKey,
		&i.IdempotencyPayloadHash,
	)
	return i, err
}
