// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByRole = `-- name: CountUsersByRole :many
SELECT role, COUNT(*) AS count
FROM users
WHERE is_active = true
GROUP BY role
`

type CountUsersByRoleRow struct {
	Role  string
	Count int64
}

func (q *Queries) CountUsersByRole(ctx context.Context) ([]CountUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, countUsersByRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountUsersByRoleRow
	for rows.Next() {
		var i CountUsersByRoleRow
		if err := rows.Scan(&i.Role, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone, name, role, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, phone, name, role, password_hash, rating, acceptance_rate, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Phone        string
	Name         string
	Role         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Phone,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Rating,
		&i.AcceptanceRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET is_active = false, updated_at = NOW()
WHERE id = $1
RETURNING id, phone, name, role, password_hash, rating, acceptance_rate, is_active, created_at, updated_at
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deactivateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Rating,
		&i.AcceptanceRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, name, role, password_hash, rating, acceptance_rate, is_active, created_at, updated_at FROM users
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Rating,
		&i.AcceptanceRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, name, role, password_hash, rating, acceptance_rate, is_active, created_at, updated_at FROM users
WHERE phone = $1 AND is_active = true
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Rating,
		&i.AcceptanceRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, phone, name, role, password_hash, rating, acceptance_rate, is_active, created_at, updated_at FROM users
WHERE ($1::text = '' OR phone ILIKE '%' || $1::text || '%' OR name ILIKE '%' || $1::text || '%')
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Name,
			&i.Role,
			&i.PasswordHash,
			&i.Rating,
			&i.AcceptanceRate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, phone, name, role, password_hash, rating, acceptance_rate, is_active, created_at, updated_at
`

type SetUserActiveParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Rating,
		&i.AcceptanceRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, rating = $3, acceptance_rate = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, phone, name, role, password_hash, rating, acceptance_rate, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID             uuid.UUID
	Name           string
	Rating         pgtype.Numeric
	AcceptanceRate pgtype.Numeric
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Rating,
		arg.AcceptanceRate,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Rating,
		&i.AcceptanceRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1 AND is_active = true
RETURNING id, phone, name, role, password_hash, rating, acceptance_rate, is_active, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.PasswordHash,
		&i.Rating,
		&i.AcceptanceRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
