// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeVerifiedVerificationCode = `-- name: ConsumeVerifiedVerificationCode :exec
UPDATE verification_codes
SET expires_at = NOW()
WHERE id = $1
  AND verified_at IS NOT NULL
`

func (q *Queries) ConsumeVerifiedVerificationCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeVerifiedVerificationCode, id)
	return err
}

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_codes (user_id, code_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, code_hash, purpose, attempts, max_attempts, created_at, expires_at, verified_at
`

type CreateVerificationCodeParams struct {
	UserID    uuid.UUID
	CodeHash  pgtype.Text
	Purpose   string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode,
		arg.UserID,
		arg.CodeHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const deleteExpiredCodes = `-- name: DeleteExpiredCodes :exec
DELETE FROM verification_codes
WHERE expires_at < NOW() OR verified_at IS NOT NULL
`

func (q *Queries) DeleteExpiredCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredCodes)
	return err
}

const getLatestVerificationCode = `-- name: GetLatestVerificationCode :one
SELECT id, user_id, code_hash, purpose, attempts, max_attempts, created_at, expires_at, verified_at FROM verification_codes
WHERE user_id = $1 AND purpose = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestVerificationCodeParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) GetLatestVerificationCode(ctx context.Context, arg GetLatestVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getLatestVerificationCode, arg.UserID, arg.Purpose)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getVerificationCode = `-- name: GetVerificationCode :one
SELECT id, user_id, code_hash, purpose, attempts, max_attempts, created_at, expires_at, verified_at FROM verification_codes
WHERE id = $1
  AND expires_at > NOW()
  AND verified_at IS NULL
  AND attempts < max_attempts
`

func (q *Queries) GetVerificationCode(ctx context.Context, id uuid.UUID) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCode, id)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getVerifiedVerificationCode = `-- name: GetVerifiedVerificationCode :one
SELECT id, user_id, code_hash, purpose, attempts, max_attempts, created_at, expires_at, verified_at FROM verification_codes
WHERE id = $1
  AND purpose = 'password_reset'
  AND verified_at IS NOT NULL
  AND expires_at > NOW()
`

func (q *Queries) GetVerifiedVerificationCode(ctx context.Context, id uuid.UUID) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerifiedVerificationCode, id)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const invalidateVerificationCodes = `-- name: InvalidateVerificationCodes :exec
UPDATE verification_codes
SET verified_at = COALESCE(verified_at, NOW()),
    expires_at = LEAST(expires_at, NOW())
WHERE user_id = $1
  AND purpose = $2
  AND verified_at IS NULL
  AND expires_at > NOW()
`

type InvalidateVerificationCodesParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) InvalidateVerificationCodes(ctx context.Context, arg InvalidateVerificationCodesParams) error {
	_, err := q.db.Exec(ctx, invalidateVerificationCodes, arg.UserID, arg.Purpose)
	return err
}

const markVerificationCodeVerified = `-- name: MarkVerificationCodeVerified :one
UPDATE verification_codes
SET verified_at = NOW()
WHERE id = $1
  AND expires_at > NOW()
  AND verified_at IS NULL
  AND attempts <= max_attempts
RETURNING id, user_id, code_hash, purpose, attempts, max_attempts, created_at, expires_at, verified_at
`

func (q *Queries) MarkVerificationCodeVerified(ctx context.Context, id uuid.UUID) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, markVerificationCodeVerified, id)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const recordVerificationAttempt = `-- name: RecordVerificationAttempt :one
UPDATE verification_codes
SET attempts = attempts + 1
WHERE id = $1
  AND expires_at > NOW()
  AND verified_at IS NULL
  AND attempts < max_attempts
RETURNING id, user_id, code_hash, purpose, attempts, max_attempts, created_at, expires_at, verified_at
`

func (q *Queries) RecordVerificationAttempt(ctx context.Context, id uuid.UUID) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, recordVerificationAttempt, id)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}
